// Bundles the flag SVGs for every playable country into src/generated/flags.ts.
// Flags are only ever served through random per-round tokens (anti-cheat), so they
// must not be deployed as publicly addressable files.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const flagDir = join(dirname(require.resolve('flag-icons/package.json')), 'flags', '4x3');
const regions = readFileSync(join(here, '../../shared/src/regions.ts'), 'utf8');
const codes = [...regions.matchAll(/'([A-Z]{2}(?: [A-Z]{2})*)'/g)].flatMap((m) => m[1].split(' '));

const flags = {};
for (const code of codes) flags[code] = readFileSync(join(flagDir, `${code.toLowerCase()}.svg`), 'utf8');

mkdirSync(join(here, '../src/generated'), { recursive: true });
writeFileSync(
  join(here, '../src/generated/flags.ts'),
  `// Generated by scripts/gen-flags.mjs — do not edit.\nexport const FLAGS: Record<string, string> = ${JSON.stringify(flags)};\n`,
);
console.log(`gen-flags: ${codes.length} flags`);
