// Bundles the flag SVGs for every playable country into src/generated/flags.ts.
// Flags are only ever served through random per-round tokens (anti-cheat), so they
// must not be deployed as publicly addressable files.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
// svg-country-flags keeps each flag's official proportions (flag-icons crops them all to 4:3).
const flagDir = join(dirname(require.resolve('svg-country-flags/package.json')), 'svg');
const regions = readFileSync(join(here, '../../shared/src/regions.ts'), 'utf8');
const codes = [...regions.matchAll(/'([A-Z]{2}(?: [A-Z]{2})*)'/g)].flatMap((m) => m[1].split(' '));

const flags = {};
for (const code of codes) flags[code] = withSize(readFileSync(join(flagDir, `${code.toLowerCase()}.svg`), 'utf8'), code);

/** Adds width/height (from the viewBox, 480 high) so an <img> knows the flag's real aspect ratio. */
function withSize(svg, code) {
  const open = svg.match(/<svg\b[^>]*>/);
  const box = open?.[0].match(/viewBox="([^"]+)"/);
  if (!box) throw new Error(`gen-flags: ${code} has no viewBox`);
  const [, , w, h] = box[1].trim().split(/[\s,]+/).map(Number);
  const tag = open[0].replace(/\s(width|height)="[^"]*"/g, '').replace(/^<svg/, `<svg width="${Math.round((480 * w) / h)}" height="480"`);
  return svg.slice(0, open.index) + tag + svg.slice(open.index + open[0].length);
}

mkdirSync(join(here, '../src/generated'), { recursive: true });
writeFileSync(
  join(here, '../src/generated/flags.ts'),
  `// Generated by scripts/gen-flags.mjs — do not edit.\nexport const FLAGS: Record<string, string> = ${JSON.stringify(flags)};\n`,
);
console.log(`gen-flags: ${codes.length} flags`);
