import { useEffect, useMemo } from 'preact/hooks';
import { DIVISIONS, type DivisionId } from '@flagduel/shared';
import bronze from '../assets/emblems/bronze.svg';
import silver from '../assets/emblems/silver.svg';
import gold from '../assets/emblems/gold.svg';
import platinum from '../assets/emblems/platinum.svg';
import diamond from '../assets/emblems/diamond.svg';

// Generated by scripts/gen-emblems.mjs
const EMBLEMS: Record<DivisionId, string> = { bronze, silver, gold, platinum, diamond };

/** Crossed-flags emblem of a division. Decorative unless `label` is set. */
export function Emblem({ division, size, label }: { division: DivisionId; size: number; label?: boolean }) {
  return (
    <img
      class="emblem"
      src={EMBLEMS[division]}
      width={size}
      height={size}
      alt={label ? `${DIVISIONS[division].label} division` : ''}
      draggable={false}
    />
  );
}

const CONFETTI = 48;

/** Full-screen celebration when the player reaches a division: promotion after a match, or placement. */
export function RankUp({
  division,
  kicker,
  detail,
  onClose,
}: {
  division: DivisionId;
  kicker: string;
  detail?: string;
  onClose: () => void;
}) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose();
    addEventListener('keydown', onKey);
    return () => removeEventListener('keydown', onKey);
  }, [onClose]);

  // Burst outward from the emblem, then fall; random per piece but fixed for this celebration
  const pieces = useMemo(
    () =>
      Array.from({ length: CONFETTI }, (_, i) => {
        const a = (i / CONFETTI) * Math.PI * 2 + Math.random() * 0.4;
        const d = 120 + Math.random() * 170;
        return {
          dx: Math.round(Math.cos(a) * d),
          dy: Math.round(Math.sin(a) * d * 0.8 - 60),
          rot: Math.round(Math.random() * 720 - 360),
          delay: Math.round(Math.random() * 180) + 350,
          tone: i % 4,
          round: i % 5 === 0,
        };
      }),
    [],
  );

  return (
    <div class={`rankup ${division}`} role="dialog" aria-modal="true" aria-labelledby="rankup-title" onClick={onClose}>
      <div class="rankup-body" onClick={(e) => e.stopPropagation()}>
        <div class="rankup-stage">
          <div class="rankup-rays" aria-hidden="true" />
          <div class="rankup-glow" aria-hidden="true" />
          <div class="rankup-emblem" style={{ '--emblem': `url(${EMBLEMS[division]})` }}>
            <Emblem division={division} size={176} label />
            <span class="rankup-shine" aria-hidden="true" />
          </div>
          <div class="rankup-confetti" aria-hidden="true">
            {pieces.map((p, i) => (
              <i
                key={i}
                class={`t${p.tone}${p.round ? ' round' : ''}`}
                style={{
                  '--dx': `${p.dx}px`,
                  '--dy': `${p.dy}px`,
                  '--rot': `${p.rot}deg`,
                  animationDelay: `${p.delay}ms`,
                }}
              />
            ))}
          </div>
        </div>
        <p class="rankup-kicker">{kicker}</p>
        <h1 id="rankup-title" class="rankup-title">
          {DIVISIONS[division].label}
        </h1>
        {detail && <p class="rankup-detail">{detail}</p>}
        <button class="btn btn-primary rankup-btn" onClick={onClose} autoFocus>
          Continue
        </button>
      </div>
    </div>
  );
}
