// Downloads the country statistics for Higher or Lower and writes shared/src/statsData.ts (checked in).
// Run by hand when the numbers should be refreshed:   node shared/scripts/fetch-stats.mjs
//
// Sources: World Bank indicators API (most recent non-empty value per country) and Wikipedia's
// "List of elevation extremes by country" for the highest points. A few gaps (Taiwan, Kosovo, Vatican
// City aren't in every World Bank series) are filled from MANUAL below; anything still missing just
// leaves that country out of that category.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '../src/statsData.ts');

// Game countries, read from the region table (the single source of truth).
const regions = readFileSync(join(here, '../src/regions.ts'), 'utf8');
const CODES = [...regions.slice(regions.indexOf('const TABLE')).matchAll(/'([A-Z ]{5,})'/g)]
  .flatMap((m) => m[1].split(/\s+/))
  .filter(Boolean);

/** stat id → World Bank indicator, decimals kept, and the oldest year still accepted. */
const WORLD_BANK = {
  population: { id: 'SP.POP.TOTL', digits: 0 },
  area: { id: 'AG.SRF.TOTL.K2', digits: 0 },
  density: { id: 'EN.POP.DNST', digits: 1 },
  gdp: { id: 'NY.GDP.MKTP.CD', digits: -6, minYear: 2019 },
  gdpPerCapita: { id: 'NY.GDP.PCAP.CD', digits: 0, minYear: 2019 },
  lifeExpectancy: { id: 'SP.DYN.LE00.IN', digits: 1 },
  forest: { id: 'AG.LND.FRST.ZS', digits: 1 },
  urban: { id: 'SP.URB.TOTL.IN.ZS', digits: 1 },
  fertility: { id: 'SP.DYN.TFRT.IN', digits: 2 },
  internet: { id: 'IT.NET.USER.ZS', digits: 1, minYear: 2019 },
  co2: { id: 'EN.GHG.CO2.PC.CE.AR5', digits: 2 },
  over65: { id: 'SP.POP.65UP.TO.ZS', digits: 1 },
  under15: { id: 'SP.POP.0014.TO.ZS', digits: 1 },
};

/** Gaps in the sources (approximate official figures). */
const MANUAL = {
  population: { TW: 23_400_000, VA: 882 },
  area: { TW: 36_197, XK: 10_887, VA: 0.49 },
  density: { TW: 650, XK: 150, VA: 1800 },
  gdp: { TW: 775_000_000_000 },
  gdpPerCapita: { TW: 33_100 },
  lifeExpectancy: { TW: 80.2 },
  fertility: { TW: 0.87 },
  over65: { TW: 19.2 },
  under15: { TW: 11.6 },
  forest: { TW: 60.7 },
  // Wikipedia rows the parser can't read, and the European Netherlands (not Mount Scenery in Saba).
  highestPoint: { XK: 2656, MM: 5881, SD: 3042, TG: 986, KN: 1156, NL: 322 },
};

const round = (v, digits) => {
  const f = 10 ** digits;
  return Math.round(v * f) / f;
};

async function worldBank(indicator) {
  const url = `https://api.worldbank.org/v2/country/all/indicator/${indicator}?format=json&mrnev=1&per_page=400`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${indicator}: HTTP ${res.status}`);
  const [, rows] = await res.json();
  return rows;
}

async function highestPoints(iso3to2) {
  const url = 'https://en.wikipedia.org/w/index.php?title=List_of_elevation_extremes_by_country&action=raw';
  const res = await fetch(url, { headers: { 'User-Agent': 'FlagDuel stats build (hobby project)' } });
  if (!res.ok) throw new Error(`Wikipedia: HTTP ${res.status}`);
  const out = {};
  for (const row of (await res.text()).split(/\n\|-[^\n]*\n/)) {
    const flag = /^\|\s*\{\{([A-Z]{3})\}\}/.exec(row);
    const elev = /\{\{epi\/moft\|(-?[\d,.]+)/.exec(row);
    const code = flag && iso3to2[flag[1]];
    if (code && elev) out[code] = Math.round(Number(elev[1].replace(/,/g, '')));
  }
  return out;
}

const data = {};
const years = {};
let iso3to2 = { TWN: 'TW', VAT: 'VA' };
for (const [stat, cfg] of Object.entries(WORLD_BANK)) {
  const rows = await worldBank(cfg.id);
  const byCode = Object.fromEntries(rows.map((r) => [r.country.id, r]));
  for (const r of rows) iso3to2[r.countryiso3code] = r.country.id;
  const values = {};
  const seen = {};
  for (const code of CODES) {
    const r = byCode[code];
    if (r?.value == null || (cfg.minYear && Number(r.date) < cfg.minYear)) continue;
    values[code] = round(r.value, cfg.digits);
    seen[r.date] = (seen[r.date] ?? 0) + 1;
  }
  data[stat] = values;
  // The year most countries' values are from.
  years[stat] = Object.entries(seen).sort((a, b) => b[1] - a[1])[0][0];
}
data.highestPoint = await highestPoints(iso3to2);
years.highestPoint = null;

for (const [stat, fill] of Object.entries(MANUAL)) {
  for (const [code, v] of Object.entries(fill)) data[stat][code] = v;
}

const lines = [
  '// Generated by shared/scripts/fetch-stats.mjs — edit MANUAL there, then re-run it. Do not edit by hand.',
  `// World Bank (most recent value per country) and Wikipedia (highest points), fetched ${new Date().toISOString().slice(0, 10)}.`,
  '',
  '/** stat id → year most values are from, and value by ISO code. */',
  'export const STAT_DATA: Record<string, { year: string | null; values: Record<string, number> }> = {',
];
for (const [stat, values] of Object.entries(data)) {
  const missing = CODES.filter((c) => values[c] === undefined);
  console.log(`${stat.padEnd(15)} ${Object.keys(values).length} countries${missing.length ? `, missing ${missing.join(' ')}` : ''}`);
  const body = CODES.filter((c) => values[c] !== undefined)
    .map((c) => `${c}:${values[c]}`)
    .join(',');
  lines.push(`  ${stat}: { year: ${years[stat] ? `'${years[stat]}'` : 'null'}, values: {${body}} },`);
}
lines.push('};', '');
writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${OUT}`);
