// Pre-renders the region-selector world map to SVG path strings (src/generated/worldmap.ts),
// so the app ships ~tens of KB of paths instead of d3 + TopoJSON.
// Countries are assigned to regions via shared/src/regions.ts (not the dataset's continents).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoCentroid, geoNaturalEarth1, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';

const require = createRequire(import.meta.url);
const iso = require('i18n-iso-countries');
const here = dirname(fileURLToPath(import.meta.url));

// Region table (parsed, so this script needs no TypeScript loader).
const regionsSrc = readFileSync(join(here, '../../shared/src/regions.ts'), 'utf8');
const table = /const TABLE[^{]*\{([\s\S]*?)\n\};/.exec(regionsSrc)[1];
const REGION_OF = {};
for (const m of table.matchAll(/'?([a-z-]+)'?:\s*\n?\s*'([A-Z ]+)'/g)) {
  for (const code of m[2].split(/\s+/)) REGION_OF[code] = m[1];
}
const REGIONS = [...new Set(Object.values(REGION_OF))];

const BY_NAME = { Kosovo: 'XK', 'N. Cyprus': 'CY', Somaliland: 'SO' };
const alpha2 = (f) => BY_NAME[f.properties.name] ?? iso.numericToAlpha2(f.id);
// Missing from both datasets
const MANUAL_POINTS = { TV: [179.2, -8.5] };

const w110 = require('world-atlas/countries-110m.json');
const w50 = require('world-atlas/countries-50m.json');
const countries = feature(w110, w110.objects.countries).features.filter((f) => f.id !== '010'); // no Antarctica
const detailed = feature(w50, w50.objects.countries).features;

const WIDTH = 1000;
const projection = geoNaturalEarth1().fitWidth(WIDTH, { type: 'FeatureCollection', features: countries });
const path = geoPath(projection).digits(1);
const [[, y0], [, y1]] = path.bounds({ type: 'FeatureCollection', features: countries });
projection.translate([projection.translate()[0], projection.translate()[1] - y0 + 4]);
const HEIGHT = Math.ceil(y1 - y0 + 8);

const regions = Object.fromEntries(REGIONS.map((r) => [r, '']));
const dots = Object.fromEntries(REGIONS.map((r) => [r, []]));
let other = '';
const drawn = new Set();

for (const f of countries) {
  const code = alpha2(f);
  const d = path(f) ?? '';
  const region = REGION_OF[code];
  if (region) {
    regions[region] += d;
    drawn.add(code);
  } else other += d;
}

// Microstates too small for the 110m data become dots.
for (const code of Object.keys(REGION_OF)) {
  if (drawn.has(code)) continue;
  const f = detailed.find((x) => alpha2(x) === code);
  const lonlat = f ? geoCentroid(f) : MANUAL_POINTS[code];
  if (!lonlat) throw new Error(`No location for ${code}`);
  const [px, py] = projection(lonlat);
  const x = Math.round(Math.min(WIDTH - 5, Math.max(5, px)) * 10) / 10;
  const y = Math.round(py * 10) / 10;
  dots[REGION_OF[code]].push([x, y]);
}

const out = { width: WIDTH, height: HEIGHT, other, regions, dots };
mkdirSync(join(here, '../src/generated'), { recursive: true });
writeFileSync(
  join(here, '../src/generated/worldmap.ts'),
  `// Generated by scripts/gen-map.mjs — do not edit.\n` +
    `import type { RegionId } from '@flagduel/shared';\n\n` +
    `export const WORLD_MAP: {\n  width: number;\n  height: number;\n  other: string;\n` +
    `  regions: Record<RegionId, string>;\n  dots: Record<RegionId, [number, number][]>;\n} = ${JSON.stringify(out)};\n`,
);
const size = JSON.stringify(out).length;
console.log(`gen-map: ${drawn.size} shapes, ${Object.values(dots).flat().length} dots, ${(size / 1024).toFixed(0)} KB`);
