// Capital cities for the "Capitals" minigame — keyed by ISO code like countries.ts.
// First entry is the display name; the rest are other accepted answers (matched after
// normalization). Countries with several official capitals accept each of them.

// [code, capital, ...aliases]
const RAW: [string, string, ...string[]][] = [
  // Europe
  ['AL', 'Tirana', 'Tirane'],
  ['AD', 'Andorra la Vella'],
  ['AT', 'Vienna', 'Wien'],
  ['BY', 'Minsk'],
  ['BE', 'Brussels', 'Bruxelles', 'Brussel'],
  ['BA', 'Sarajevo'],
  ['BG', 'Sofia'],
  ['HR', 'Zagreb'],
  ['CY', 'Nicosia', 'Lefkosia'],
  ['CZ', 'Prague', 'Praha'],
  ['DK', 'Copenhagen', 'Kobenhavn'],
  ['EE', 'Tallinn'],
  ['FI', 'Helsinki'],
  ['FR', 'Paris'],
  ['DE', 'Berlin'],
  ['GR', 'Athens', 'Athina'],
  ['HU', 'Budapest'],
  ['IS', 'Reykjavík'],
  ['IE', 'Dublin'],
  ['IT', 'Rome', 'Roma'],
  ['LV', 'Riga'],
  ['LI', 'Vaduz'],
  ['LT', 'Vilnius'],
  ['LU', 'Luxembourg', 'Luxembourg City'],
  ['MT', 'Valletta'],
  ['MD', 'Chișinău', 'Kishinev'],
  ['MC', 'Monaco'],
  ['ME', 'Podgorica'],
  ['NL', 'Amsterdam'],
  ['MK', 'Skopje'],
  ['NO', 'Oslo'],
  ['PL', 'Warsaw', 'Warszawa'],
  ['PT', 'Lisbon', 'Lisboa'],
  ['RO', 'Bucharest', 'Bucuresti'],
  ['RU', 'Moscow', 'Moskva'],
  ['SM', 'San Marino', 'City of San Marino'],
  ['RS', 'Belgrade', 'Beograd'],
  ['SK', 'Bratislava'],
  ['SI', 'Ljubljana'],
  ['ES', 'Madrid'],
  ['SE', 'Stockholm'],
  ['CH', 'Bern', 'Berne'],
  ['UA', 'Kyiv', 'Kiev'],
  ['GB', 'London'],
  ['VA', 'Vatican City', 'Vatican'],
  ['XK', 'Pristina', 'Prishtina', 'Prishtine'],
  // Asia
  ['AF', 'Kabul'],
  ['AM', 'Yerevan'],
  ['AZ', 'Baku'],
  ['BH', 'Manama'],
  ['BD', 'Dhaka', 'Dacca'],
  ['BT', 'Thimphu'],
  ['BN', 'Bandar Seri Begawan'],
  ['KH', 'Phnom Penh'],
  ['CN', 'Beijing', 'Peking'],
  ['GE', 'Tbilisi'],
  ['IN', 'New Delhi', 'Delhi'],
  ['ID', 'Jakarta'],
  ['IR', 'Tehran', 'Teheran'],
  ['IQ', 'Baghdad'],
  ['IL', 'Jerusalem'],
  ['JO', 'Amman'],
  ['JP', 'Tokyo'],
  ['KZ', 'Astana', 'Nur-Sultan'],
  ['KW', 'Kuwait City', 'Kuwait'],
  ['KG', 'Bishkek'],
  ['LA', 'Vientiane'],
  ['LB', 'Beirut'],
  ['MY', 'Kuala Lumpur'],
  ['MV', 'Malé'],
  ['MN', 'Ulaanbaatar', 'Ulan Bator', 'Ulaan Baatar'],
  ['MM', 'Naypyidaw', 'Nay Pyi Taw', 'Naypyitaw'],
  ['NP', 'Kathmandu'],
  ['KP', 'Pyongyang'],
  ['OM', 'Muscat'],
  ['PK', 'Islamabad'],
  ['PH', 'Manila'],
  ['QA', 'Doha'],
  ['SA', 'Riyadh'],
  ['SG', 'Singapore'],
  ['KR', 'Seoul'],
  ['LK', 'Sri Jayawardenepura Kotte', 'Kotte', 'Colombo'],
  ['SY', 'Damascus'],
  ['TJ', 'Dushanbe'],
  ['TH', 'Bangkok'],
  ['TL', 'Dili'],
  ['TR', 'Ankara'],
  ['TM', 'Ashgabat', 'Ashkhabad'],
  ['AE', 'Abu Dhabi'],
  ['UZ', 'Tashkent'],
  ['VN', 'Hanoi', 'Ha Noi'],
  ['YE', "Sana'a", 'Sanaa'],
  ['PS', 'Ramallah', 'East Jerusalem'],
  ['TW', 'Taipei'],
  // Africa
  ['DZ', 'Algiers'],
  ['AO', 'Luanda'],
  ['BJ', 'Porto-Novo'],
  ['BW', 'Gaborone'],
  ['BF', 'Ouagadougou'],
  ['BI', 'Gitega', 'Bujumbura'],
  ['CV', 'Praia'],
  ['CM', 'Yaoundé'],
  ['CF', 'Bangui'],
  ['TD', "N'Djamena"],
  ['KM', 'Moroni'],
  ['CG', 'Brazzaville'],
  ['CD', 'Kinshasa'],
  ['CI', 'Yamoussoukro', 'Abidjan'],
  ['DJ', 'Djibouti', 'Djibouti City'],
  ['EG', 'Cairo'],
  ['GQ', 'Malabo'],
  ['ER', 'Asmara'],
  ['SZ', 'Mbabane', 'Lobamba'],
  ['ET', 'Addis Ababa'],
  ['GA', 'Libreville'],
  ['GM', 'Banjul'],
  ['GH', 'Accra'],
  ['GN', 'Conakry'],
  ['GW', 'Bissau'],
  ['KE', 'Nairobi'],
  ['LS', 'Maseru'],
  ['LR', 'Monrovia'],
  ['LY', 'Tripoli'],
  ['MG', 'Antananarivo'],
  ['MW', 'Lilongwe'],
  ['ML', 'Bamako'],
  ['MR', 'Nouakchott'],
  ['MU', 'Port Louis'],
  ['MA', 'Rabat'],
  ['MZ', 'Maputo'],
  ['NA', 'Windhoek'],
  ['NE', 'Niamey'],
  ['NG', 'Abuja'],
  ['RW', 'Kigali'],
  ['ST', 'São Tomé'],
  ['SN', 'Dakar'],
  ['SC', 'Victoria'],
  ['SL', 'Freetown'],
  ['SO', 'Mogadishu'],
  ['ZA', 'Pretoria', 'Cape Town', 'Bloemfontein'],
  ['SS', 'Juba'],
  ['SD', 'Khartoum'],
  ['TZ', 'Dodoma'],
  ['TG', 'Lomé'],
  ['TN', 'Tunis'],
  ['UG', 'Kampala'],
  ['ZM', 'Lusaka'],
  ['ZW', 'Harare'],
  // Oceania
  ['AU', 'Canberra'],
  ['FJ', 'Suva'],
  ['KI', 'South Tarawa', 'Tarawa'],
  ['MH', 'Majuro'],
  ['FM', 'Palikir'],
  ['NR', 'Yaren'],
  ['NZ', 'Wellington'],
  ['PW', 'Ngerulmud', 'Melekeok'],
  ['PG', 'Port Moresby'],
  ['WS', 'Apia'],
  ['SB', 'Honiara'],
  ['TO', "Nuku'alofa"],
  ['TV', 'Funafuti'],
  ['VU', 'Port Vila'],
  // North America
  ['US', 'Washington, D.C.', 'Washington', 'Washington DC'],
  ['CA', 'Ottawa'],
  ['MX', 'Mexico City', 'Ciudad de Mexico'],
  // Central America
  ['BZ', 'Belmopan'],
  ['GT', 'Guatemala City', 'Guatemala', 'Ciudad de Guatemala'],
  ['HN', 'Tegucigalpa'],
  ['SV', 'San Salvador'],
  ['NI', 'Managua'],
  ['CR', 'San José'],
  ['PA', 'Panama City', 'Panama'],
  // Caribbean
  ['CU', 'Havana', 'La Habana', 'Habana'],
  ['JM', 'Kingston'],
  ['HT', 'Port-au-Prince'],
  ['DO', 'Santo Domingo'],
  ['BS', 'Nassau'],
  ['BB', 'Bridgetown'],
  ['TT', 'Port of Spain'],
  ['GD', "St. George's"],
  ['LC', 'Castries'],
  ['VC', 'Kingstown'],
  ['AG', "St. John's"],
  ['DM', 'Roseau'],
  ['KN', 'Basseterre'],
  // South America
  ['AR', 'Buenos Aires'],
  ['BO', 'Sucre', 'La Paz'],
  ['BR', 'Brasília'],
  ['CL', 'Santiago', 'Santiago de Chile'],
  ['CO', 'Bogotá'],
  ['EC', 'Quito'],
  ['GY', 'Georgetown'],
  ['PY', 'Asunción'],
  ['PE', 'Lima'],
  ['SR', 'Paramaribo'],
  ['UY', 'Montevideo'],
  ['VE', 'Caracas'],
];

export interface Capital {
  /** ISO code of the country */
  code: string;
  name: string;
  aliases: string[];
}

export const CAPITALS: Capital[] = RAW.map(([code, name, ...aliases]) => ({ code, name, aliases }));

export const CAPITAL_BY_CODE: Record<string, Capital> = Object.fromEntries(CAPITALS.map((c) => [c.code, c]));
