import { REGION_OF, type RegionId } from './regions';

export interface Country {
  /** ISO 3166-1 alpha-2, upper case */
  code: string;
  /** English display name */
  name: string;
  /** Other accepted answers (matched after normalization) */
  aliases: string[];
  region: RegionId;
}

// [code, name, ...aliases]
const RAW: [string, string, ...string[]][] = [
  // Europe
  ['AL', 'Albania'],
  ['AD', 'Andorra'],
  ['AT', 'Austria'],
  ['BY', 'Belarus', 'Byelorussia'],
  ['BE', 'Belgium'],
  ['BA', 'Bosnia and Herzegovina', 'Bosnia', 'Bosnia Herzegovina', 'BiH'],
  ['BG', 'Bulgaria'],
  ['HR', 'Croatia', 'Hrvatska'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czechia', 'Czech Republic'],
  ['DK', 'Denmark'],
  ['EE', 'Estonia'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['DE', 'Germany', 'Deutschland'],
  ['GR', 'Greece', 'Hellas'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['IE', 'Ireland', 'Republic of Ireland', 'Eire'],
  ['IT', 'Italy'],
  ['LV', 'Latvia'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MT', 'Malta'],
  ['MD', 'Moldova', 'Republic of Moldova'],
  ['MC', 'Monaco'],
  ['ME', 'Montenegro'],
  ['NL', 'Netherlands', 'The Netherlands'],
  ['MK', 'North Macedonia', 'Macedonia'],
  ['NO', 'Norway'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['RO', 'Romania'],
  ['RU', 'Russia', 'Russian Federation'],
  ['SM', 'San Marino'],
  ['RS', 'Serbia'],
  ['SK', 'Slovakia', 'Slovak Republic'],
  ['SI', 'Slovenia'],
  ['ES', 'Spain', 'Espana'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland', 'Swiss Confederation'],
  ['UA', 'Ukraine'],
  ['GB', 'United Kingdom', 'UK', 'U.K.', 'Great Britain', 'Britain', 'United Kingdom of Great Britain and Northern Ireland'],
  ['VA', 'Vatican City', 'Vatican', 'Holy See', 'Vatican City State'],
  ['XK', 'Kosovo'],
  // Asia
  ['AF', 'Afghanistan'],
  ['AM', 'Armenia'],
  ['AZ', 'Azerbaijan'],
  ['BH', 'Bahrain'],
  ['BD', 'Bangladesh'],
  ['BT', 'Bhutan'],
  ['BN', 'Brunei', 'Brunei Darussalam'],
  ['KH', 'Cambodia', 'Kampuchea'],
  ['CN', 'China', "People's Republic of China", 'PRC'],
  ['GE', 'Georgia'],
  ['IN', 'India'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran', 'Persia', 'Islamic Republic of Iran'],
  ['IQ', 'Iraq'],
  ['IL', 'Israel'],
  ['JP', 'Japan', 'Nippon'],
  ['JO', 'Jordan'],
  ['KZ', 'Kazakhstan', 'Kazakstan'],
  ['KW', 'Kuwait'],
  ['KG', 'Kyrgyzstan', 'Kirgizstan', 'Kyrgyz Republic'],
  ['LA', 'Laos', 'Lao PDR', "Lao People's Democratic Republic"],
  ['LB', 'Lebanon'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['MN', 'Mongolia'],
  ['MM', 'Myanmar', 'Burma'],
  ['NP', 'Nepal'],
  ['KP', 'North Korea', 'DPRK', "Democratic People's Republic of Korea"],
  ['OM', 'Oman'],
  ['PK', 'Pakistan'],
  ['PH', 'Philippines'],
  ['QA', 'Qatar'],
  ['SA', 'Saudi Arabia'],
  ['SG', 'Singapore'],
  ['KR', 'South Korea', 'Republic of Korea'],
  ['LK', 'Sri Lanka', 'Ceylon'],
  ['SY', 'Syria', 'Syrian Arab Republic'],
  ['TJ', 'Tajikistan'],
  ['TH', 'Thailand', 'Siam'],
  ['TL', 'Timor-Leste', 'East Timor'],
  ['TR', 'Turkey', 'Turkiye'],
  ['TM', 'Turkmenistan'],
  ['AE', 'United Arab Emirates', 'UAE', 'Emirates'],
  ['UZ', 'Uzbekistan'],
  ['VN', 'Vietnam', 'Viet Nam'],
  ['YE', 'Yemen'],
  ['PS', 'Palestine', 'State of Palestine', 'Palestinian Territories'],
  ['TW', 'Taiwan', 'Republic of China', 'Chinese Taipei'],
  // Africa
  ['DZ', 'Algeria'],
  ['AO', 'Angola'],
  ['BJ', 'Benin'],
  ['BW', 'Botswana'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['CV', 'Cabo Verde', 'Cape Verde'],
  ['CM', 'Cameroon'],
  ['CF', 'Central African Republic', 'CAR'],
  ['TD', 'Chad'],
  ['KM', 'Comoros'],
  ['CG', 'Republic of the Congo', 'Congo', 'Congo-Brazzaville', 'Congo Brazzaville'],
  ['CD', 'DR Congo', 'Democratic Republic of the Congo', 'DRC', 'Congo-Kinshasa', 'Congo Kinshasa', 'Zaire'],
  ['CI', "Côte d'Ivoire", 'Ivory Coast'],
  ['DJ', 'Djibouti'],
  ['EG', 'Egypt'],
  ['GQ', 'Equatorial Guinea'],
  ['ER', 'Eritrea'],
  ['SZ', 'Eswatini', 'Swaziland'],
  ['ET', 'Ethiopia'],
  ['GA', 'Gabon'],
  ['GM', 'Gambia', 'The Gambia'],
  ['GH', 'Ghana'],
  ['GN', 'Guinea', 'Guinea-Conakry'],
  ['GW', 'Guinea-Bissau'],
  ['KE', 'Kenya'],
  ['LS', 'Lesotho'],
  ['LR', 'Liberia'],
  ['LY', 'Libya'],
  ['MG', 'Madagascar'],
  ['MW', 'Malawi'],
  ['ML', 'Mali'],
  ['MR', 'Mauritania'],
  ['MU', 'Mauritius'],
  ['MA', 'Morocco'],
  ['MZ', 'Mozambique'],
  ['NA', 'Namibia'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['RW', 'Rwanda'],
  ['ST', 'São Tomé and Príncipe', 'Sao Tome'],
  ['SN', 'Senegal'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa', 'RSA'],
  ['SS', 'South Sudan'],
  ['SD', 'Sudan'],
  ['TZ', 'Tanzania'],
  ['TG', 'Togo'],
  ['TN', 'Tunisia'],
  ['UG', 'Uganda'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],
  // Oceania
  ['AU', 'Australia'],
  ['FJ', 'Fiji'],
  ['KI', 'Kiribati'],
  ['MH', 'Marshall Islands'],
  ['FM', 'Micronesia', 'Federated States of Micronesia'],
  ['NR', 'Nauru'],
  ['NZ', 'New Zealand', 'Aotearoa'],
  ['PW', 'Palau'],
  ['PG', 'Papua New Guinea', 'PNG'],
  ['WS', 'Samoa'],
  ['SB', 'Solomon Islands'],
  ['TO', 'Tonga'],
  ['TV', 'Tuvalu'],
  ['VU', 'Vanuatu'],
  // North America
  ['US', 'United States', 'USA', 'US', 'United States of America', 'America'],
  ['CA', 'Canada'],
  ['MX', 'Mexico'],
  // Central America
  ['BZ', 'Belize'],
  ['GT', 'Guatemala'],
  ['HN', 'Honduras'],
  ['SV', 'El Salvador'],
  ['NI', 'Nicaragua'],
  ['CR', 'Costa Rica'],
  ['PA', 'Panama'],
  // Caribbean
  ['CU', 'Cuba'],
  ['JM', 'Jamaica'],
  ['HT', 'Haiti'],
  ['DO', 'Dominican Republic'],
  ['BS', 'Bahamas', 'The Bahamas'],
  ['BB', 'Barbados'],
  ['TT', 'Trinidad and Tobago', 'Trinidad'],
  ['GD', 'Grenada'],
  ['LC', 'Saint Lucia'],
  ['VC', 'Saint Vincent and the Grenadines', 'Saint Vincent'],
  ['AG', 'Antigua and Barbuda', 'Antigua'],
  ['DM', 'Dominica'],
  ['KN', 'Saint Kitts and Nevis', 'Saint Kitts', 'Saint Christopher and Nevis'],
  // South America
  ['AR', 'Argentina'],
  ['BO', 'Bolivia'],
  ['BR', 'Brazil', 'Brasil'],
  ['CL', 'Chile'],
  ['CO', 'Colombia'],
  ['EC', 'Ecuador'],
  ['GY', 'Guyana'],
  ['PY', 'Paraguay'],
  ['PE', 'Peru'],
  ['SR', 'Suriname', 'Surinam'],
  ['UY', 'Uruguay'],
  ['VE', 'Venezuela'],
];

export const COUNTRIES: Country[] = RAW.map(([code, name, ...aliases]) => {
  const region = REGION_OF[code];
  if (!region) throw new Error(`No region for ${code}`);
  return { code, name, aliases, region };
});

export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c]),
);
