// Generated by worker/scripts/fetch-landmarks.mjs — do not edit (edit landmarks.ts and re-run).
export interface LandmarkMeta {
  lat: number | null;
  lon: number | null;
  /** Wikimedia Commons file */
  file: string;
  author: string;
  license: string;
  licenseUrl: string | null;
  /** Commons file page */
  source: string;
}

export const LANDMARK_META: Record<string, LandmarkMeta> = {
  "eiffel-tower": {
    "lat": 48.8582,
    "lon": 2.2945,
    "file": "Tour_Eiffel_Wikimedia_Commons_(cropped).jpg",
    "author": "Benh LIEU SONG",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wikimedia_Commons_(cropped).jpg"
  },
  "mont-saint-michel": {
    "lat": 48.636,
    "lon": -1.511,
    "file": "Mont-Saint-Michel_vu_du_ciel.jpg",
    "author": "Amaustan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mont-Saint-Michel_vu_du_ciel.jpg"
  },
  "colosseum": {
    "lat": 41.8903,
    "lon": 12.4922,
    "file": "Colosseo_2020.jpg",
    "author": "FeaturedPics",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Colosseo_2020.jpg"
  },
  "leaning-tower-of-pisa": {
    "lat": 43.7231,
    "lon": 10.3964,
    "file": "Italy_-_Pisa_-_Leaning_Tower.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Italy_-_Pisa_-_Leaning_Tower.jpg"
  },
  "sagrada-familia": {
    "lat": 41.4037,
    "lon": 2.1743,
    "file": "SF_maig_2_cropped.jpg",
    "author": "Canaan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SF_maig_2_cropped.jpg"
  },
  "alhambra": {
    "lat": 37.1775,
    "lon": -3.59,
    "file": "Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg",
    "author": "Jebulon",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg"
  },
  "big-ben": {
    "lat": 51.5007,
    "lon": -0.1245,
    "file": "Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg",
    "author": "Christian David",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg"
  },
  "stonehenge": {
    "lat": 51.1789,
    "lon": -1.8261,
    "file": "Stonehenge2007_07_30.jpg",
    "author": "garethwiscombe",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Stonehenge2007_07_30.jpg"
  },
  "tower-bridge": {
    "lat": 51.5056,
    "lon": -0.0753,
    "file": "Tower_Bridge_at_Dawn.jpg",
    "author": "Fuzzypiggy",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tower_Bridge_at_Dawn.jpg"
  },
  "brandenburg-gate": {
    "lat": 52.5163,
    "lon": 13.3777,
    "file": "Brandenburger_Tor_abends.jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Brandenburger_Tor_abends.jpg"
  },
  "neuschwanstein": {
    "lat": 47.5575,
    "lon": 10.7494,
    "file": "Schloss_Neuschwanstein_2013.jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Schloss_Neuschwanstein_2013.jpg"
  },
  "cologne-cathedral": {
    "lat": 50.9414,
    "lon": 6.9583,
    "file": "Kölner_Dom_-_Westfassade_2022_ohne_Gerüst-0968_b.jpg",
    "author": "Raimond Spekking",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:K%C3%B6lner_Dom_-_Westfassade_2022_ohne_Ger%C3%BCst-0968_b.jpg"
  },
  "parthenon": {
    "lat": 37.9715,
    "lon": 23.7266,
    "file": "The_Parthenon_in_Athens.jpg",
    "author": "Steve Swayne",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Parthenon_in_Athens.jpg"
  },
  "st-basils-cathedral": {
    "lat": 55.7525,
    "lon": 37.6231,
    "file": "Saint_Basil's_Cathedral_in_Moscow.jpg",
    "author": "Tsy1980",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Saint_Basil%27s_Cathedral_in_Moscow.jpg"
  },
  "charles-bridge": {
    "lat": 50.0864,
    "lon": 14.4119,
    "file": "Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg",
    "author": "A.Savin",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg"
  },
  "hungarian-parliament": {
    "lat": 47.5069,
    "lon": 19.0456,
    "file": "Hungarian_Parliament_Building_from_across_the_Danube,_2025-01-11.jpg",
    "author": "Kilyann Le Hen",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hungarian_Parliament_Building_from_across_the_Danube,_2025-01-11.jpg"
  },
  "belem-tower": {
    "lat": 38.6917,
    "lon": -9.2161,
    "file": "Torre_Belém_April_2009-4a.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Torre_Bel%C3%A9m_April_2009-4a.jpg"
  },
  "st-peters-basilica": {
    "lat": 41.9022,
    "lon": 12.4533,
    "file": "Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg"
  },
  "chapel-bridge": {
    "lat": 47.0517,
    "lon": 8.3075,
    "file": "Kapellbruecke.JPG",
    "author": "Simon Koopmann",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Kapellbruecke.JPG"
  },
  "kinderdijk": {
    "lat": 51.884,
    "lon": 4.639,
    "file": "KinderdijkMolens02.jpg",
    "author": "Lucas Hirschegger",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:KinderdijkMolens02.jpg"
  },
  "dubrovnik": {
    "lat": 42.641,
    "lon": 18.11,
    "file": "Dubrovnik_s_24.jpg",
    "author": "Miroslav.vajdic",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dubrovnik_s_24.jpg"
  },
  "hallgrimskirkja": {
    "lat": 64.1417,
    "lon": -21.9266,
    "file": "Hallgrimskirkja_mai_2026.jpg",
    "author": "Steinninn",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hallgrimskirkja_mai_2026.jpg"
  },
  "cliffs-of-moher": {
    "lat": 52.9718,
    "lon": -9.4263,
    "file": "Cliffs-Of-Moher-OBriens-From-South.JPG",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cliffs-Of-Moher-OBriens-From-South.JPG"
  },
  "geirangerfjord": {
    "lat": 62.121,
    "lon": 7.129,
    "file": "Geirangerfjord_.jpg",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Geirangerfjord_.jpg"
  },
  "atomium": {
    "lat": 50.8947,
    "lon": 4.3411,
    "file": "The_Atomium_during_civil_twilight_(DSCF1135).jpg",
    "author": "Trougnouf (Benoit Brummer)",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Atomium_during_civil_twilight_(DSCF1135).jpg"
  },
  "wawel-castle": {
    "lat": 50.0539,
    "lon": 19.9347,
    "file": "Wawel_(4).jpg",
    "author": "Monika Towiańska",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wawel_(4).jpg"
  },
  "schonbrunn": {
    "lat": 48.1845,
    "lon": 16.3119,
    "file": "Wien_-_Schloss_Schönbrunn.JPG",
    "author": "C.Stadler/Bwag",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wien_-_Schloss_Sch%C3%B6nbrunn.JPG"
  },
  "bran-castle": {
    "lat": 45.515,
    "lon": 25.3672,
    "file": "Castelul_Bran2.jpg",
    "author": "Dobre Cezar",
    "license": "CC BY-SA 3.0 ro",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/ro/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Castelul_Bran2.jpg"
  },
  "stari-most": {
    "lat": 43.3373,
    "lon": 17.815,
    "file": "Mostar_Old_Town_Panorama_2007.jpg",
    "author": "Ramirez",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mostar_Old_Town_Panorama_2007.jpg"
  },
  "taj-mahal": {
    "lat": 27.175,
    "lon": 78.0419,
    "file": "Taj_Mahal_(Edited).jpeg",
    "author": "Yann; edited by Jim Carter",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Taj_Mahal_(Edited).jpeg"
  },
  "golden-temple": {
    "lat": 31.62,
    "lon": 74.8764,
    "file": "The_Golden_Temple_of_Amrithsar_7.jpg",
    "author": "Shagil Kannur",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Golden_Temple_of_Amrithsar_7.jpg"
  },
  "great-wall": {
    "lat": 40.4314,
    "lon": 116.5644,
    "file": "The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
    "author": "Severin.stalder",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Great_Wall_of_China_at_Jinshanling-edit.jpg"
  },
  "forbidden-city": {
    "lat": 39.9158,
    "lon": 116.3908,
    "file": "Sunset of the Forbidden City 2006.JPG",
    "author": "User:kallgan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Sunset_of_the_Forbidden_City_2006.JPG"
  },
  "potala-palace": {
    "lat": 29.6578,
    "lon": 91.1169,
    "file": "Potala_Palace_HQ.jpg",
    "author": "Lhasa Government",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Potala_Palace_HQ.jpg"
  },
  "angkor-wat": {
    "lat": 13.4125,
    "lon": 103.8667,
    "file": "Angkor_Wat.jpg",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Angkor_Wat.jpg"
  },
  "petronas-towers": {
    "lat": 3.1578,
    "lon": 101.7117,
    "file": "2016 Kuala Lumpur, Petronas Towers (26).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Petronas_Towers_(26).jpg"
  },
  "burj-khalifa": {
    "lat": 25.1972,
    "lon": 55.2742,
    "file": "Dubai skyline 2015 (crop).jpg",
    "author": "Tim.Reckmann",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dubai_skyline_2015_(crop).jpg"
  },
  "mount-fuji": {
    "lat": 35.3608,
    "lon": 138.7275,
    "file": "View_of_Mount_Fuji_from_Ōwakudani_20211202.jpg",
    "author": "Suicasmo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg"
  },
  "fushimi-inari": {
    "lat": 34.9672,
    "lon": 135.7728,
    "file": "Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg"
  },
  "petra": {
    "lat": 30.3285,
    "lon": 35.4444,
    "file": "Al_Deir_Petra.JPG",
    "author": "Azurfrog",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Al_Deir_Petra.JPG"
  },
  "marina-bay-sands": {
    "lat": 1.2825,
    "lon": 103.86,
    "file": "Marina_Bay_Sands_(I).jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Sands_(I).jpg"
  },
  "borobudur": {
    "lat": -7.608,
    "lon": 110.204,
    "file": "Pradaksina.jpg",
    "author": "Heri nugroho",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pradaksina.jpg"
  },
  "hagia-sophia": {
    "lat": 41.0083,
    "lon": 28.98,
    "file": "Hagia_Sophia_(228968325).jpeg",
    "author": "Adli Wahid",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hagia_Sophia_(228968325).jpeg"
  },
  "shwedagon": {
    "lat": 16.7984,
    "lon": 96.1497,
    "file": "Shwedagon_Pagoda_2017.jpg",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Shwedagon_Pagoda_2017.jpg"
  },
  "wat-arun": {
    "lat": 13.7436,
    "lon": 100.4889,
    "file": "เจดีย์ประธานทรงปรางค์วัดอรุณ2.jpg",
    "author": "Mastertongapollo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%98%E0%B8%B2%E0%B8%99%E0%B8%97%E0%B8%A3%E0%B8%87%E0%B8%9B%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B9%8C%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AD%E0%B8%A3%E0%B8%B8%E0%B8%932.jpg"
  },
  "ha-long-bay": {
    "lat": 20.9,
    "lon": 107.2,
    "file": "Ha_Long_Bay_in_2019.jpg",
    "author": "Taewangkorea",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ha_Long_Bay_in_2019.jpg"
  },
  "registan": {
    "lat": 39.6547,
    "lon": 66.9756,
    "file": "RegistanSquare_Samarkand.jpg",
    "author": "Registan_-_Gusjer.jpg: Gustavo Jeronimo from Aranjuez, Spain derivative work: MrPanyGoff",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:RegistanSquare_Samarkand.jpg"
  },
  "taipei-101": {
    "lat": 25.0336,
    "lon": 121.5647,
    "file": "Taipei Taiwan Taipei-101-Tower-01.jpg",
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Taipei_Taiwan_Taipei-101-Tower-01.jpg"
  },
  "gyeongbokgung": {
    "lat": 37.5799,
    "lon": 126.9768,
    "file": "광화문_월대.jpg",
    "author": "서울관광 아카이브",
    "license": "KOGL Type 1",
    "licenseUrl": "http://www.kogl.or.kr/info/licenseType1.do",
    "source": "https://commons.wikimedia.org/wiki/File:%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg"
  },
  "sigiriya": {
    "lat": 7.9569,
    "lon": 80.7597,
    "file": "Sigiriya_(141688197).jpeg",
    "author": "Wrobell",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sigiriya_(141688197).jpeg"
  },
  "persepolis": {
    "lat": 29.935,
    "lon": 52.89,
    "file": "2018-09-21_Iran,_Persepolis,_Tachara_(from_the_southeast).jpg",
    "author": "Laurens R. Krol",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2018-09-21_Iran,_Persepolis,_Tachara_(from_the_southeast).jpg"
  },
  "tigers-nest": {
    "lat": 27.4919,
    "lon": 89.3635,
    "file": "Paro_Taktsang,_Bhutan_(edited).jpg",
    "author": "Original: Nina R from Africa Derivative work: UnpetitproleX",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Paro_Taktsang,_Bhutan_(edited).jpg"
  },
  "chocolate-hills": {
    "lat": 9.9167,
    "lon": 124.1667,
    "file": "Chocolate Hills overview.JPG",
    "author": "P199",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chocolate_Hills_overview.JPG"
  },
  "boudhanath": {
    "lat": 27.7214,
    "lon": 85.3619,
    "file": "Boudhanath_stupa_,_Kathmandu,_Nepal.jpg",
    "author": "Sumitbhatt222",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boudhanath_stupa_,_Kathmandu,_Nepal.jpg"
  },
  "pyramids-of-giza": {
    "lat": 29.9761,
    "lon": 31.1328,
    "file": "Pyramids_of_the_Giza_Necropolis.jpg",
    "author": "KennyOMG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pyramids_of_the_Giza_Necropolis.jpg"
  },
  "abu-simbel": {
    "lat": 22.3369,
    "lon": 31.6256,
    "file": "Ramsis,_Aswan_Governorate,_Egypt_-_panoramio.jpg",
    "author": "youssef_alam",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ramsis,_Aswan_Governorate,_Egypt_-_panoramio.jpg"
  },
  "table-mountain": {
    "lat": -33.9622,
    "lon": 18.4099,
    "file": "Table_Mountain_DanieVDM.jpg",
    "author": "Danie van der Merwe from Cape Town, South Africa",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Table_Mountain_DanieVDM.jpg"
  },
  "kilimanjaro": {
    "lat": -3.0674,
    "lon": 37.3556,
    "file": "Kilimanjaro_from_Amboseli.jpg",
    "author": "Sergey Pesterev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kilimanjaro_from_Amboseli.jpg"
  },
  "djenne-mosque": {
    "lat": 13.9053,
    "lon": -4.5556,
    "file": "Djenne_great_mud_mosque.jpg",
    "author": "Ruud Zwart",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Djenne_great_mud_mosque.jpg"
  },
  "ait-benhaddou": {
    "lat": 31.0472,
    "lon": -7.1289,
    "file": "Ksar_Aït_Benhaddou,_Marocco_(أيت_بن_حدو،_المغرب,_ⴰⵢⵜ_ⵃⴰⴷⴷⵓ).jpg",
    "author": "Petar Milošević",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ksar_A%C3%AFt_Benhaddou,_Marocco_(%D8%A3%D9%8A%D8%AA_%D8%A8%D9%86_%D8%AD%D8%AF%D9%88%D8%8C_%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8,_%E2%B4%B0%E2%B5%A2%E2%B5%9C_%E2%B5%83%E2%B4%B0%E2%B4%B7%E2%B4%B7%E2%B5%93).jpg"
  },
  "lalibela": {
    "lat": 12.0317,
    "lon": 39.0411,
    "file": "Lalibela,_san_giorgio,_esterno_24.jpg",
    "author": "Sailko",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lalibela,_san_giorgio,_esterno_24.jpg"
  },
  "avenue-of-the-baobabs": {
    "lat": -20.25,
    "lon": 44.4194,
    "file": "Adansonia_grandidieri_Pat_Hooper.jpg",
    "author": "Pat Hooper from Chicago, IL, USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Adansonia_grandidieri_Pat_Hooper.jpg"
  },
  "el-jem": {
    "lat": 35.2964,
    "lon": 10.7069,
    "file": "The_Amphitheatre_of_El_Jem,_built_around_AD_238_in_Thysdrus_in_Africa_Proconsularis,_the_estimated_capacity_is_35,000,_Tunisia_-_52717762494.jpg",
    "author": "Carole Raddato",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Amphitheatre_of_El_Jem,_built_around_AD_238_in_Thysdrus_in_Africa_Proconsularis,_the_estimated_capacity_is_35,000,_Tunisia_-_52717762494.jpg"
  },
  "sossusvlei": {
    "lat": -24.7398,
    "lon": 15.2877,
    "file": "Sossusvlei.jpg",
    "author": "Ikiwaner",
    "license": "GFDL 1.2",
    "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
    "source": "https://commons.wikimedia.org/wiki/File:Sossusvlei.jpg"
  },
  "great-zimbabwe": {
    "lat": -20.2667,
    "lon": 30.9333,
    "file": "Conical_Tower_-_Great_Enclosure_III_(33736918448).jpg",
    "author": "Andrew Moore from Johannesburg, South Africa",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Conical_Tower_-_Great_Enclosure_III_(33736918448).jpg"
  },
  "our-lady-of-peace": {
    "lat": 6.8111,
    "lon": -5.2969,
    "file": "Basilique notre Dame de la Paix de Yamoussoukro 9.jpg",
    "author": "Didierwiki",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Basilique_notre_Dame_de_la_Paix_de_Yamoussoukro_9.jpg"
  },
  "goree": {
    "lat": 14.6669,
    "lon": -17.3983,
    "file": "Ile-de-goree.jpg",
    "author": "Gregor Rom",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ile-de-goree.jpg"
  },
  "statue-of-liberty": {
    "lat": 40.6892,
    "lon": -74.0444,
    "file": "Front_view_of_Statue_of_Liberty_(cropped).jpg",
    "author": "AskALotl",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Front_view_of_Statue_of_Liberty_(cropped).jpg"
  },
  "golden-gate-bridge": {
    "lat": 37.8197,
    "lon": -122.4786,
    "file": "Golden_Gate_Bridge_as_seen_from_Battery_East.jpg",
    "author": "Frank Schulenburg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Golden_Gate_Bridge_as_seen_from_Battery_East.jpg"
  },
  "mount-rushmore": {
    "lat": 43.8789,
    "lon": -103.4592,
    "file": "Mount_Rushmore_detail_view_(100MP).jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mount_Rushmore_detail_view_(100MP).jpg"
  },
  "grand-canyon": {
    "lat": 36.3,
    "lon": -112.75,
    "file": "Canyon_River_Tree_(165872763).jpeg",
    "author": "Lennart Sikkema",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Canyon_River_Tree_(165872763).jpeg"
  },
  "space-needle": {
    "lat": 47.6204,
    "lon": -122.3491,
    "file": "Space_Needle_2011-07-04.jpg",
    "author": "Jordon Kalilich",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Space_Needle_2011-07-04.jpg"
  },
  "cn-tower": {
    "lat": 43.6426,
    "lon": -79.3871,
    "file": "Toronto - ON - Skyline bei Nacht.jpg",
    "author": "Wladyslaw (talk)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Toronto_-_ON_-_Skyline_bei_Nacht.jpg"
  },
  "chateau-frontenac": {
    "lat": 46.8119,
    "lon": -71.205,
    "file": "Château_Frontenac_02.jpg",
    "author": "Bernard Gagnon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_Frontenac_02.jpg"
  },
  "moraine-lake": {
    "lat": 51.3225,
    "lon": -116.1856,
    "file": "Moraine_Lake_17092005.jpg",
    "author": "Gorgo",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Moraine_Lake_17092005.jpg"
  },
  "chichen-itza": {
    "lat": 20.6831,
    "lon": -88.5686,
    "file": "Chichen_Itza_3.jpg",
    "author": "Daniel Schwen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chichen_Itza_3.jpg"
  },
  "teotihuacan": {
    "lat": 19.6925,
    "lon": -98.8439,
    "file": "ZA77_Teotihuacán_edo_de_mex_Herberto_de_la_rosa.jpg",
    "author": "Hdlrosa",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:ZA77_Teotihuac%C3%A1n_edo_de_mex_Herberto_de_la_rosa.jpg"
  },
  "bellas-artes": {
    "lat": 19.4353,
    "lon": -99.1414,
    "file": "Bellas_Artes_01.jpg",
    "author": "Xavier Quetzalcoatl Contreras Castillo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bellas_Artes_01.jpg"
  },
  "tikal": {
    "lat": 17.2219,
    "lon": -89.6236,
    "file": "Tikal_3.jpg",
    "author": "Mundo Maya",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tikal_3.jpg"
  },
  "santa-catalina-arch": {
    "lat": 14.5575,
    "lon": -90.7333,
    "file": "Antigua_-_Arco.jpg",
    "author": "Juan Francisco",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Antigua_-_Arco.jpg"
  },
  "panama-canal": {
    "lat": 8.9971,
    "lon": -79.5919,
    "file": "Panama Canal Miraflores Locks.jpg",
    "author": "User:Stan Shebs",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Panama_Canal_Miraflores_Locks.jpg"
  },
  "arenal": {
    "lat": 10.4625,
    "lon": -84.7033,
    "file": "Arenal_volcano_(70785p)_(cropped).jpg",
    "author": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arenal_volcano_(70785p)_(cropped).jpg"
  },
  "great-blue-hole": {
    "lat": 17.3153,
    "lon": -87.5344,
    "file": "Great_Blue_Hole.jpg",
    "author": "U.S. Geological Survey (USGS)",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Great_Blue_Hole.jpg"
  },
  "copan": {
    "lat": 14.8375,
    "lon": -89.1425,
    "file": "Copan_sculpture.jpg",
    "author": "Adalberto Hernandez Vega from Copan Ruinas, Honduras",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Copan_sculpture.jpg"
  },
  "leon-cathedral": {
    "lat": 12.435,
    "lon": -86.8781,
    "file": "Nicaragua_2017-03-13_(33663091692).jpg",
    "author": "Guillaume Baviere from Uppsala, Sweden",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nicaragua_2017-03-13_(33663091692).jpg"
  },
  "el-capitolio": {
    "lat": 23.1353,
    "lon": -82.3594,
    "file": "El_Capitolio_Havana_Cuba.jpg",
    "author": "Nigel Pacquette",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:El_Capitolio_Havana_Cuba.jpg"
  },
  "citadelle-laferriere": {
    "lat": 19.5736,
    "lon": -72.2439,
    "file": "Citadelle_Laferrière.jpg",
    "author": "Rémi Kaupp",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Citadelle_Laferri%C3%A8re.jpg"
  },
  "pitons": {
    "lat": 13.81,
    "lon": -61.0656,
    "file": "Pitons-aerial.jpg",
    "author": "Caribbeandy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pitons-aerial.jpg"
  },
  "dunns-river-falls": {
    "lat": 18.4158,
    "lon": -77.1381,
    "file": "Dunns_River_Falls_climb.JPG",
    "author": "Breakyunit at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Dunns_River_Falls_climb.JPG"
  },
  "alcazar-de-colon": {
    "lat": 18.4775,
    "lon": -69.8828,
    "file": "Maison_du_gouverneur_Don_Diego_Colomb.jpg",
    "author": "Caribeanvybz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Maison_du_gouverneur_Don_Diego_Colomb.jpg"
  },
  "machu-picchu": {
    "lat": -13.1633,
    "lon": -72.5456,
    "file": "Machu_Picchu,_2023_(012).jpg",
    "author": "Draceane",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Machu_Picchu,_2023_(012).jpg"
  },
  "christ-the-redeemer": {
    "lat": -22.9519,
    "lon": -43.2106,
    "file": "Christ_the_Redeemer_-_Cristo_Redentor.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Christ_the_Redeemer_-_Cristo_Redentor.jpg"
  },
  "sugarloaf": {
    "lat": -22.9494,
    "lon": -43.1567,
    "file": "Pão_de_Açucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:P%C3%A3o_de_A%C3%A7ucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg"
  },
  "moai": {
    "lat": -27.1258,
    "lon": -109.2767,
    "file": "AhuTongariki.JPG",
    "author": "Ian Sewell",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:AhuTongariki.JPG"
  },
  "torres-del-paine": {
    "lat": -51,
    "lon": -73,
    "file": "Towers of Paine - Torres del Paine National Park 13.jpg",
    "author": "Thomas Fuhrmann",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Towers_of_Paine_-_Torres_del_Paine_National_Park_13.jpg"
  },
  "salar-de-uyuni": {
    "lat": -20.1338,
    "lon": -67.4891,
    "file": "Salar_Uyuni_au01.jpg",
    "author": "Anouchka Unel",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:Salar_Uyuni_au01.jpg"
  },
  "angel-falls": {
    "lat": 5.9675,
    "lon": -62.5356,
    "file": "SaltoAngel1.jpg",
    "author": "Rich Childs",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:SaltoAngel1.jpg"
  },
  "perito-moreno": {
    "lat": -50.5,
    "lon": -73.1333,
    "file": "Perito_Moreno_Glacier_2023.jpg",
    "author": "Fernando",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Perito_Moreno_Glacier_2023.jpg"
  },
  "obelisco": {
    "lat": -34.6036,
    "lon": -58.3817,
    "file": "Buenos_Aires_(20234294752).jpg",
    "author": "Rodrigo Paredes from Ciudad Autónoma de Buenos Aires, Argentina",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Buenos_Aires_(20234294752).jpg"
  },
  "las-lajas": {
    "lat": 0.8055,
    "lon": -77.586,
    "file": "Santuario_de_Las_Lajas,_Ipiales,_Colombia,_2015-07-21,_DD_26-27_HDR.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Santuario_de_Las_Lajas,_Ipiales,_Colombia,_2015-07-21,_DD_26-27_HDR.JPG"
  },
  "kaieteur-falls": {
    "lat": 5.175,
    "lon": -59.4805,
    "file": "GuyanaKaieteurFalls2004.jpg",
    "author": "Sorenriise at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:GuyanaKaieteurFalls2004.jpg"
  },
  "galapagos": {
    "lat": -0.5,
    "lon": -90.5,
    "file": "Lobo_marino_(Zalophus_californianus_wollebaeki),_Punta_Pitt,_isla_de_San_Cristóbal,_islas_Galápagos,_Ecuador,_2015-07-24,_DD_11.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lobo_marino_(Zalophus_californianus_wollebaeki),_Punta_Pitt,_isla_de_San_Crist%C3%B3bal,_islas_Gal%C3%A1pagos,_Ecuador,_2015-07-24,_DD_11.JPG"
  },
  "sydney-opera-house": {
    "lat": -33.8568,
    "lon": 151.2151,
    "file": "Sydney_Australia._(21339175489).jpg",
    "author": "Bernard Spragg. NZ from Christchurch, New Zealand",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Sydney_Australia._(21339175489).jpg"
  },
  "uluru": {
    "lat": -25.345,
    "lon": 131.0361,
    "file": "ULURU.jpg",
    "author": "Ek2030372672",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:ULURU.jpg"
  },
  "twelve-apostles": {
    "lat": -38.665,
    "lon": 143.105,
    "file": "The_Twelve_Apostles_2011.jpg",
    "author": "Michael J Fromholtz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Twelve_Apostles_2011.jpg"
  },
  "milford-sound": {
    "lat": -44.6481,
    "lon": 167.9056,
    "file": "Milford_Sound_(New_Zealand).JPG",
    "author": "Maros M r a z (Maros)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Milford_Sound_(New_Zealand).JPG"
  },
  "sky-tower": {
    "lat": -36.8485,
    "lon": 174.7623,
    "file": "01_Auckland_New_Zealand-1000137.jpg",
    "author": "QFSE Media",
    "license": "CC BY-SA 3.0 nz",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/nz/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:01_Auckland_New_Zealand-1000137.jpg"
  },
  "nan-madol": {
    "lat": 6.8419,
    "lon": 158.3322,
    "file": "Nan_madol.jpg",
    "author": "NOAA",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Nan_madol.jpg"
  }
};
