// Landmarks game: famous places, shown as a zoomed-in photo; the answer is the country.
// The single place to edit the list. After adding one, run `node worker/scripts/fetch-landmarks.mjs`:
// it downloads the photo (the English Wikipedia article's lead image, or `file`) to worker/landmarks/<id>.jpg
// and writes coordinates + credits to landmarkMeta.ts. Photos are only served through random per-round
// tokens, like flags, so a file name never gives the answer away.
//
// Only landmarks that clearly belong to one country (no border waterfalls or mountains).

export interface Landmark {
  /** Also the photo's file name */
  id: string;
  name: string;
  /** ISO 3166-1 alpha-2 of the country it is in (the answer) */
  country: string;
  /** English Wikipedia article (its lead photo is used unless `file` is set) */
  wiki: string;
  /** Wikimedia Commons file to use instead of the article's lead photo */
  file?: string;
  /** Point the photo zooms out from, as fractions of its width and height (default: the centre) */
  focus?: [number, number];
}

// [id, name, country, wiki article, focus?, commons file?]
type Row = [string, string, string, string, ([number, number] | null)?, string?];

const RAW: Row[] = [
  // Europe
  ['eiffel-tower', 'Eiffel Tower', 'FR', 'Eiffel Tower', [0.5, 0.55]],
  ['mont-saint-michel', 'Mont-Saint-Michel', 'FR', 'Mont-Saint-Michel', [0.52, 0.38]],
  ['colosseum', 'Colosseum', 'IT', 'Colosseum', [0.3, 0.45]],
  ['leaning-tower-of-pisa', 'Leaning Tower of Pisa', 'IT', 'Leaning Tower of Pisa', [0.44, 0.5]],
  ['sagrada-familia', 'Sagrada Família', 'ES', 'Sagrada Família', [0.52, 0.5]],
  ['alhambra', 'Alhambra', 'ES', 'Alhambra', [0.3, 0.5]],
  ['big-ben', 'Big Ben', 'GB', 'Big Ben', [0.5, 0.55]],
  ['stonehenge', 'Stonehenge', 'GB', 'Stonehenge'],
  ['tower-bridge', 'Tower Bridge', 'GB', 'Tower Bridge', [0.43, 0.42]],
  ['brandenburg-gate', 'Brandenburg Gate', 'DE', 'Brandenburg Gate', [0.62, 0.6]],
  ['neuschwanstein', 'Neuschwanstein Castle', 'DE', 'Neuschwanstein Castle', [0.3, 0.45]],
  ['cologne-cathedral', 'Cologne Cathedral', 'DE', 'Cologne Cathedral', [0.5, 0.55]],
  ['parthenon', 'Parthenon', 'GR', 'Parthenon', [0.55, 0.45]],
  ['st-basils-cathedral', "Saint Basil's Cathedral", 'RU', "Saint Basil's Cathedral", [0.46, 0.5]],
  ['charles-bridge', 'Charles Bridge', 'CZ', 'Charles Bridge', [0.55, 0.65]],
  ['hungarian-parliament', 'Hungarian Parliament Building', 'HU', 'Hungarian Parliament Building', [0.5, 0.55]],
  ['belem-tower', 'Belém Tower', 'PT', 'Belém Tower', [0.55, 0.4]],
  ['st-peters-basilica', "St. Peter's Basilica", 'VA', "St. Peter's Basilica", [0.5, 0.45]],
  ['chapel-bridge', 'Chapel Bridge, Lucerne', 'CH', 'Chapel Bridge', [0.68, 0.3]],
  ['kinderdijk', 'Windmills of Kinderdijk', 'NL', 'Kinderdijk', [0.35, 0.45]],
  ['dubrovnik', 'Dubrovnik city walls', 'HR', 'Walls of Dubrovnik', [0.55, 0.5]],
  ['hallgrimskirkja', 'Hallgrímskirkja', 'IS', 'Hallgrímskirkja', [0.4, 0.45]],
  ['cliffs-of-moher', 'Cliffs of Moher', 'IE', 'Cliffs of Moher', [0.7, 0.55]],
  ['geirangerfjord', 'Geirangerfjord', 'NO', 'Geirangerfjord', [0.55, 0.6]],
  ['atomium', 'Atomium', 'BE', 'Atomium', [0.5, 0.45]],
  ['wawel-castle', 'Wawel Castle', 'PL', 'Wawel Castle', [0.45, 0.45]],
  ['schonbrunn', 'Schönbrunn Palace', 'AT', 'Schönbrunn Palace', [0.5, 0.52]],
  ['bran-castle', 'Bran Castle', 'RO', 'Bran Castle', [0.6, 0.4]],
  ['stari-most', 'Stari Most', 'BA', 'Stari Most', [0.42, 0.5]],
  ['louvre-pyramid', 'Louvre Pyramid', 'FR', 'Louvre Pyramid', [0.53, 0.45], 'Louvre Museum Wikimedia Commons.jpg'],
  ['arc-de-triomphe', 'Arc de Triomphe', 'FR', 'Arc de Triomphe', [0.5, 0.45]],
  ['trevi-fountain', 'Trevi Fountain', 'IT', 'Trevi Fountain'],
  ['florence-cathedral', 'Florence Cathedral', 'IT', 'Florence Cathedral', [0.72, 0.4]],
  ['grand-canal-venice', 'Grand Canal, Venice', 'IT', 'Grand Canal (Venice)', [0.55, 0.55]],
  ['plaza-de-espana-seville', 'Plaza de España, Seville', 'ES', 'Plaza de España, Seville', [0.25, 0.4]],
  ['edinburgh-castle', 'Edinburgh Castle', 'GB', 'Edinburgh Castle', [0.55, 0.55]],
  ['giants-causeway', "Giant's Causeway", 'GB', "Giant's Causeway", [0.6, 0.55]],
  ['meteora', 'Meteora', 'GR', 'Meteora', [0.7, 0.75]],
  ['oia-santorini', 'Oia, Santorini', 'GR', 'Oia, Greece', [0.55, 0.45]],
  ['moscow-kremlin', 'Moscow Kremlin', 'RU', 'Moscow Kremlin', [0.35, 0.45]],
  ['peterhof', 'Peterhof Palace', 'RU', 'Peterhof Palace', [0.6, 0.45]],
  ['nyhavn', 'Nyhavn', 'DK', 'Nyhavn', [0.45, 0.6]],
  ['little-mermaid', 'The Little Mermaid', 'DK', 'The Little Mermaid (statue)', [0.53, 0.48], 'Denmark, Copenhagen, Little Mermaid, Langelinie Promenade 150422-25.jpg'],
  ['helsinki-cathedral', 'Helsinki Cathedral', 'FI', 'Helsinki Cathedral', [0.4, 0.3]],
  ['chillon', 'Château de Chillon', 'CH', 'Chillon Castle', [0.4, 0.6]],
  ['hallstatt', 'Hallstatt', 'AT', 'Hallstatt', [0.35, 0.45]],
  ['prague-castle', 'Prague Castle', 'CZ', 'Prague Castle', [0.55, 0.45]],
  ['plitvice', 'Plitvice Lakes', 'HR', 'Plitvice Lakes National Park', [0.45, 0.5]],
  ['rila-monastery', 'Rila Monastery', 'BG', 'Rila Monastery', [0.4, 0.4]],
  ['pena-palace', 'Pena Palace', 'PT', 'Pena Palace', [0.3, 0.45]],
  ['tallinn-old-town', 'Tallinn Old Town', 'EE', 'Tallinn Old Town', [0.5, 0.55]],
  ['trakai', 'Trakai Island Castle', 'LT', 'Trakai Island Castle', [0.6, 0.3]],
  ['bled', 'Lake Bled', 'SI', 'Lake Bled', [0.5, 0.67]],
  ['kaneo', 'Church of St. John at Kaneo', 'MK', 'Church of St. John at Kaneo', [0.7, 0.55]],
  ['valletta', 'Valletta', 'MT', 'Valletta', [0.7, 0.4]],
  ['vianden-castle', 'Vianden Castle', 'LU', 'Vianden Castle', [0.5, 0.4]],
  ['st-sophia-kyiv', 'Saint Sophia Cathedral, Kyiv', 'UA', 'Saint Sophia Cathedral, Kyiv', [0.55, 0.35]],
  ['gergeti', 'Gergeti Trinity Church', 'GE', 'Gergeti Trinity Church', [0.3, 0.4]],
  ['khor-virap', 'Khor Virap', 'AM', 'Khor Virap', [0.3, 0.6]],
  ['notre-dame-paris', 'Notre-Dame de Paris', 'FR', 'Notre-Dame de Paris'],
  ['versailles', 'Palace of Versailles', 'FR', 'Palace of Versailles'],
  ['pont-du-gard', 'Pont du Gard', 'FR', 'Pont du Gard'],
  ['carcassonne', 'Cité de Carcassonne', 'FR', 'Cité de Carcassonne'],
  ['milan-cathedral', 'Milan Cathedral', 'IT', 'Milan Cathedral'],
  ['pompeii', 'Pompeii', 'IT', 'Pompeii'],
  ['manarola', 'Manarola, Cinque Terre', 'IT', 'Manarola'],
  ['guggenheim-bilbao', 'Guggenheim Museum Bilbao', 'ES', 'Guggenheim Museum Bilbao'],
  ['aqueduct-of-segovia', 'Aqueduct of Segovia', 'ES', 'Aqueduct of Segovia'],
  ['park-guell', 'Park Güell', 'ES', 'Park Güell'],
  ['buckingham-palace', 'Buckingham Palace', 'GB', 'Buckingham Palace'],
  ['eilean-donan', 'Eilean Donan', 'GB', 'Eilean Donan'],
  ['rhine-falls', 'Rhine Falls', 'CH', 'Rhine Falls'],
  ['grand-place', 'Grand-Place, Brussels', 'BE', 'Grand-Place'],
  ['dom-luis-bridge', 'Dom Luís I Bridge, Porto', 'PT', 'Dom Luís I Bridge'],
  ['navagio', 'Navagio Beach', 'GR', 'Navagio'],
  ['kotor', 'Kotor', 'ME', 'Kotor'],
  ['preikestolen', 'Preikestolen', 'NO', 'Preikestolen'],
  ['gamla-stan', 'Gamla stan, Stockholm', 'SE', 'Gamla stan'],
  ['house-of-blackheads', 'House of the Blackheads, Riga', 'LV', 'House of the Blackheads (Riga)'],
  ['malbork-castle', 'Malbork Castle', 'PL', 'Malbork Castle'],
  ['fishermans-bastion', "Fisherman's Bastion", 'HU', "Fisherman's Bastion"],
  ['peles-castle', 'Peleș Castle', 'RO', 'Peleș Castle'],
  ['spis-castle', 'Spiš Castle', 'SK', 'Spiš Castle', null, 'Spiš Castle Aerial 2018.jpg'],
  ['church-of-saint-sava', 'Church of Saint Sava', 'RS', 'Church of Saint Sava'],
  ['alexander-nevsky-sofia', 'Alexander Nevsky Cathedral, Sofia', 'BG', 'Alexander Nevsky Cathedral, Sofia'],
  ['kizhi', 'Kizhi Pogost', 'RU', 'Kizhi Pogost'],
  ['monte-carlo-casino', 'Monte Carlo Casino', 'MC', 'Monte Carlo Casino'],
  ['guaita', 'Guaita tower, San Marino', 'SM', 'Guaita'],
  ['berat', 'Berat', 'AL', 'Berat'],
  ['mir-castle', 'Mir Castle', 'BY', 'Mir Castle Complex'],
  ['flame-towers', 'Flame Towers, Baku', 'AZ', 'Flame Towers', null, 'Flame towers from Baku boulevard.JPG'],
  // Asia
  ['taj-mahal', 'Taj Mahal', 'IN', 'Taj Mahal'],
  ['golden-temple', 'Golden Temple', 'IN', 'Golden Temple', [0.5, 0.45]],
  ['great-wall', 'Great Wall of China', 'CN', 'Great Wall of China', [0.72, 0.5]],
  ['forbidden-city', 'Forbidden City', 'CN', 'Forbidden City', [0.5, 0.4], 'Sunset of the Forbidden City 2006.JPG'],
  ['potala-palace', 'Potala Palace', 'CN', 'Potala Palace', [0.5, 0.66]],
  ['angkor-wat', 'Angkor Wat', 'KH', 'Angkor Wat', [0.5, 0.4]],
  ['petronas-towers', 'Petronas Towers', 'MY', 'Petronas Towers', [0.6, 0.35], '2016 Kuala Lumpur, Petronas Towers (26).jpg'],
  ['burj-khalifa', 'Burj Khalifa', 'AE', 'Burj Khalifa', [0.78, 0.3], 'Dubai skyline 2015 (crop).jpg'],
  ['mount-fuji', 'Mount Fuji', 'JP', 'Mount Fuji'],
  ['fushimi-inari', 'Fushimi Inari-taisha', 'JP', 'Fushimi Inari-taisha', [0.6, 0.5]],
  ['petra', 'Petra', 'JO', 'Petra', [0.45, 0.5]],
  ['marina-bay-sands', 'Marina Bay Sands', 'SG', 'Marina Bay Sands', [0.5, 0.4]],
  ['borobudur', 'Borobudur', 'ID', 'Borobudur', [0.5, 0.45]],
  ['hagia-sophia', 'Hagia Sophia', 'TR', 'Hagia Sophia', [0.47, 0.5]],
  ['shwedagon', 'Shwedagon Pagoda', 'MM', 'Shwedagon Pagoda', [0.47, 0.55]],
  ['wat-arun', 'Wat Arun', 'TH', 'Wat Arun'],
  ['ha-long-bay', 'Ha Long Bay', 'VN', 'Ha Long Bay', [0.3, 0.62]],
  ['registan', 'Registan', 'UZ', 'Registan', [0.3, 0.6]],
  ['taipei-101', 'Taipei 101', 'TW', 'Taipei 101', [0.52, 0.3], 'Taipei Taiwan Taipei-101-Tower-01.jpg'],
  ['gyeongbokgung', 'Gyeongbokgung', 'KR', 'Gyeongbokgung', [0.5, 0.66]],
  ['sigiriya', 'Sigiriya', 'LK', 'Sigiriya', [0.45, 0.3]],
  ['persepolis', 'Persepolis', 'IR', 'Persepolis', [0.45, 0.45]],
  ['tigers-nest', "Tiger's Nest", 'BT', 'Paro Taktsang', [0.35, 0.6]],
  ['chocolate-hills', 'Chocolate Hills', 'PH', 'Chocolate Hills', [0.6, 0.6], 'Chocolate Hills overview.JPG'],
  ['boudhanath', 'Boudhanath', 'NP', 'Boudhanath', [0.5, 0.4]],
  ['himeji-castle', 'Himeji Castle', 'JP', 'Himeji Castle', [0.3, 0.3]],
  ['terracotta-army', 'Terracotta Army', 'CN', 'Terracotta Army', [0.5, 0.75]],
  ['temple-of-heaven', 'Temple of Heaven', 'CN', 'Temple of Heaven'],
  ['hawa-mahal', 'Hawa Mahal', 'IN', 'Hawa Mahal', [0.5, 0.4]],
  ['gateway-of-india', 'Gateway of India', 'IN', 'Gateway of India', [0.5, 0.4]],
  ['bagan', 'Bagan', 'MM', 'Bagan', [0.3, 0.6]],
  ['batu-caves', 'Batu Caves', 'MY', 'Batu Caves', [0.68, 0.5]],
  ['hegra', 'Hegra', 'SA', 'Hegra (Mada\'in Salih)', [0.4, 0.6], "Qasr al-Farid, a 1st-century AD Nabatean unfinished tomb carved into a giant boulder in Hegra (Mada'in Salih), the kingdom's second Nabatean capital after Petra, Saudi Arabia - 53535089614.jpg"],
  ['naqsh-e-jahan', 'Naqsh-e Jahan Square', 'IR', 'Naqsh-e Jahan Square', [0.7, 0.3], 'Sheikh Lotfallah Esfahan.JPG'],
  ['cappadocia', 'Cappadocia', 'TR', 'Cappadocia', [0.65, 0.45]],
  ['pamukkale', 'Pamukkale', 'TR', 'Pamukkale', [0.5, 0.65]],
  ['baalbek', 'Baalbek', 'LB', 'Baalbek', [0.6, 0.45]],
  ['badshahi-mosque', 'Badshahi Mosque', 'PK', 'Badshahi Mosque', [0.53, 0.55]],
  ['wat-xieng-thong', 'Wat Xieng Thong', 'LA', 'Wat Xieng Thong', [0.7, 0.55]],
  ['n-seoul-tower', 'N Seoul Tower', 'KR', 'N Seoul Tower', [0.5, 0.3], 'Namsan Seoul Tower (49174492933).jpg'],
  ['genghis-khan-statue', 'Genghis Khan Equestrian Statue', 'MN', 'Genghis Khan Equestrian Statue', [0.55, 0.45]],
  ['darvaza', 'Darvaza gas crater', 'TM', 'Darvaza gas crater'],
  ['banaue', 'Banaue Rice Terraces', 'PH', 'Banaue Rice Terraces'],
  ['omar-ali-saifuddien-mosque', 'Omar Ali Saifuddien Mosque', 'BN', 'Omar Ali Saifuddien Mosque', [0.55, 0.4]],
  ['hoi-an', 'Japanese Bridge, Hội An', 'VN', 'Japanese Covered Bridge', [0.6, 0.55]],
  ['grand-palace-bangkok', 'Grand Palace, Bangkok', 'TH', 'Grand Palace', [0.4, 0.5]],
  ['blue-mosque', 'Blue Mosque', 'TR', 'Blue Mosque, Istanbul'],
  ['kinkaku-ji', 'Kinkaku-ji', 'JP', 'Kinkaku-ji'],
  ['itsukushima', 'Itsukushima Shrine', 'JP', 'Itsukushima Shrine'],
  ['qutub-minar', 'Qutub Minar', 'IN', 'Qutub Minar'],
  ['mysore-palace', 'Mysore Palace', 'IN', 'Mysore Palace'],
  ['sultan-qaboos-mosque', 'Sultan Qaboos Grand Mosque', 'OM', 'Sultan Qaboos Grand Mosque', null, 'Sultan Qaboos Grand Mosque (1).jpg'],
  ['kuwait-towers', 'Kuwait Towers', 'KW', 'Kuwait Towers', null, 'Kuwait Towers (158990699).jpg'],
  ['museum-of-islamic-art', 'Museum of Islamic Art, Doha', 'QA', 'Museum of Islamic Art, Doha', null, 'IslamicArtMuseumDohaSkyline.jpg'],
  ['krak-des-chevaliers', 'Krak des Chevaliers', 'SY', 'Krak des Chevaliers'],
  ['ziggurat-of-ur', 'Ziggurat of Ur', 'IQ', 'Ziggurat of Ur'],
  ['shibam', 'Shibam', 'YE', 'Shibam'],
  ['masada', 'Masada', 'IL', 'Masada'],
  ['bayterek', 'Bayterek Tower', 'KZ', 'Bayterek Tower', null, 'Baiterek August.jpg'],
  ['burana-tower', 'Burana Tower', 'KG', 'Burana Tower'],
  ['faisal-mosque', 'Faisal Mosque', 'PK', 'Faisal Mosque'],
  ['national-parliament-dhaka', 'National Parliament House, Dhaka', 'BD', 'Jatiya Sangsad Bhaban'],
  ['temple-of-the-tooth', 'Temple of the Tooth', 'LK', 'Temple of the Tooth'],
  ['prambanan', 'Prambanan', 'ID', 'Prambanan'],
  ['tanah-lot', 'Tanah Lot', 'ID', 'Tanah Lot'],
  ['bayon', 'Bayon', 'KH', 'Bayon'],
  ['wat-rong-khun', 'Wat Rong Khun (White Temple)', 'TH', 'Wat Rong Khun'],
  ['pha-that-luang', 'Pha That Luang', 'LA', 'Pha That Luang'],
  ['bulguksa', 'Bulguksa', 'KR', 'Bulguksa'],
  ['juche-tower', 'Juche Tower', 'KP', 'Juche Tower'],
  ['zhangjiajie', 'Zhangjiajie National Forest Park', 'CN', 'Zhangjiajie National Forest Park'],
  ['the-bund', 'The Bund, Shanghai', 'CN', 'The Bund'],
  ['merlion', 'Merlion', 'SG', 'Merlion'],
  // Africa
  ['pyramids-of-giza', 'Pyramids of Giza', 'EG', 'Giza pyramid complex', [0.5, 0.45]],
  ['abu-simbel', 'Abu Simbel', 'EG', 'Abu Simbel', [0.3, 0.45]],
  ['table-mountain', 'Table Mountain', 'ZA', 'Table Mountain', [0.35, 0.52]],
  ['kilimanjaro', 'Mount Kilimanjaro', 'TZ', 'Mount Kilimanjaro', [0.6, 0.5]],
  ['djenne-mosque', 'Great Mosque of Djenné', 'ML', 'Great Mosque of Djenné', [0.5, 0.4]],
  ['ait-benhaddou', 'Aït Benhaddou', 'MA', 'Aït Benhaddou', [0.35, 0.5]],
  ['lalibela', 'Church of Saint George, Lalibela', 'ET', 'Church of Saint George, Lalibela', [0.5, 0.4]],
  ['avenue-of-the-baobabs', 'Avenue of the Baobabs', 'MG', 'Avenue of the Baobabs', [0.6, 0.5]],
  ['el-jem', 'Amphitheatre of El Jem', 'TN', 'Amphitheatre of El Jem', [0.5, 0.45]],
  ['sossusvlei', 'Sossusvlei', 'NA', 'Sossusvlei'],
  ['great-zimbabwe', 'Great Zimbabwe', 'ZW', 'Great Zimbabwe', [0.4, 0.4]],
  ['our-lady-of-peace', 'Basilica of Our Lady of Peace', 'CI', 'Basilica of Our Lady of Peace', [0.6, 0.4], 'Basilique notre Dame de la Paix de Yamoussoukro 9.jpg'],
  ['goree', 'Gorée', 'SN', 'Gorée', [0.5, 0.6]],
  ['karnak', 'Karnak', 'EG', 'Karnak', [0.6, 0.45]],
  ['leptis-magna', 'Leptis Magna', 'LY', 'Leptis Magna'],
  ['sidi-bou-said', 'Sidi Bou Said', 'TN', 'Sidi Bou Said', [0.75, 0.3], 'SidBS (47).JPG'],
  ['notre-dame-d-afrique', "Notre-Dame d'Afrique", 'DZ', "Notre-Dame d'Afrique", [0.45, 0.4]],
  ['chefchaouen', 'Chefchaouen', 'MA', 'Chefchaouen', [0.3, 0.65]],
  ['hassan-ii-mosque', 'Hassan II Mosque', 'MA', 'Hassan II Mosque', [0.53, 0.4], 'SOUR JDID, Casablanca, Morocco - panoramio (16).jpg'],
  ['fasil-ghebbi', 'Fasil Ghebbi, Gondar', 'ET', 'Fasil Ghebbi', [0.4, 0.5]],
  ['meroe-pyramids', 'Pyramids of Meroë', 'SD', 'Meroë', [0.45, 0.4]],
  ['blyde-river-canyon', 'Blyde River Canyon', 'ZA', 'Blyde River Canyon', [0.65, 0.5]],
  ['stone-town', 'Stone Town, Zanzibar', 'TZ', 'Stone Town', [0.82, 0.45]],
  ['le-morne', 'Le Morne Brabant', 'MU', 'Le Morne Brabant', [0.4, 0.6]],
  ['anse-source-d-argent', "Anse Source d'Argent", 'SC', "Anse Source d'Argent", [0.4, 0.6]],
  ['okavango-delta', 'Okavango Delta', 'BW', 'Okavango Delta', [0.75, 0.5], 'Travesía del delta del Okavango en makoro, Botsuana, 2018-08-01, DD 22.jpg'],
  ['kasubi-tombs', 'Kasubi Tombs', 'UG', 'Kasubi Tombs'],
  ['sphinx', 'Great Sphinx of Giza', 'EG', 'Great Sphinx of Giza'],
  ['jemaa-el-fnaa', 'Jemaa el-Fnaa', 'MA', 'Jemaa el-Fnaa'],
  ['kairouan-mosque', 'Great Mosque of Kairouan', 'TN', 'Great Mosque of Kairouan'],
  ['timgad', 'Timgad', 'DZ', 'Timgad'],
  ['agadez-mosque', 'Grand Mosque of Agadez', 'NE', 'Agadez Mosque'],
  ['bobo-dioulasso-mosque', 'Grand Mosque of Bobo-Dioulasso', 'BF', 'Grand Mosque of Bobo-Dioulasso'],
  ['cape-coast-castle', 'Cape Coast Castle', 'GH', 'Cape Coast Castle'],
  ['zuma-rock', 'Zuma Rock', 'NG', 'Zuma Rock'],
  ['african-renaissance-monument', 'African Renaissance Monument', 'SN', 'African Renaissance Monument'],
  ['lake-retba', 'Lake Retba', 'SN', 'Lake Retba'],
  ['fiat-tagliero', 'Fiat Tagliero Building, Asmara', 'ER', 'Fiat Tagliero Building'],
  ['lake-assal', 'Lake Assal', 'DJ', 'Lake Assal (Djibouti)', null, 'DjiboutiLacAssal.jpg'],
  ['mount-kenya', 'Mount Kenya', 'KE', 'Mount Kenya'],
  ['blue-nile-falls', 'Blue Nile Falls', 'ET', 'Blue Nile Falls'],
  ['tsingy', 'Tsingy de Bemaraha', 'MG', 'Tsingy de Bemaraha National Park'],
  ['fish-river-canyon', 'Fish River Canyon', 'NA', 'Fish River Canyon'],
  ['cape-of-good-hope', 'Cape of Good Hope', 'ZA', 'Cape of Good Hope'],
  ['island-of-mozambique', 'Island of Mozambique', 'MZ', 'Island of Mozambique'],
  // North America
  ['statue-of-liberty', 'Statue of Liberty', 'US', 'Statue of Liberty', [0.53, 0.3]],
  ['golden-gate-bridge', 'Golden Gate Bridge', 'US', 'Golden Gate Bridge', [0.5, 0.45]],
  ['mount-rushmore', 'Mount Rushmore', 'US', 'Mount Rushmore', [0.4, 0.45]],
  ['grand-canyon', 'Grand Canyon', 'US', 'Grand Canyon', [0.4, 0.55]],
  ['space-needle', 'Space Needle', 'US', 'Space Needle', [0.5, 0.3]],
  ['cn-tower', 'CN Tower', 'CA', 'CN Tower', [0.52, 0.4], 'Toronto - ON - Skyline bei Nacht.jpg'],
  ['chateau-frontenac', 'Château Frontenac', 'CA', 'Château Frontenac', [0.5, 0.5]],
  ['moraine-lake', 'Moraine Lake', 'CA', 'Moraine Lake', [0.5, 0.4]],
  ['chichen-itza', 'Chichén Itzá', 'MX', 'Chichen Itza', [0.5, 0.55]],
  ['teotihuacan', 'Teotihuacan', 'MX', 'Teotihuacan', [0.45, 0.6]],
  ['bellas-artes', 'Palacio de Bellas Artes', 'MX', 'Palacio de Bellas Artes', [0.5, 0.45]],
  ['hollywood-sign', 'Hollywood Sign', 'US', 'Hollywood Sign', [0.45, 0.6]],
  ['white-house', 'White House', 'US', 'White House', [0.4, 0.35], 'Tourists by WH.JPG'],
  ['times-square', 'Times Square', 'US', 'Times Square', [0.5, 0.6]],
  ['gateway-arch', 'Gateway Arch', 'US', 'Gateway Arch', [0.5, 0.4]],
  ['parliament-hill', 'Parliament Hill, Ottawa', 'CA', 'Parliament Hill', [0.55, 0.5]],
  ['tulum', 'Tulum', 'MX', 'Tulum', [0.4, 0.55]],
  ['empire-state-building', 'Empire State Building', 'US', 'Empire State Building'],
  ['lincoln-memorial', 'Lincoln Memorial', 'US', 'Lincoln Memorial'],
  ['delicate-arch', 'Delicate Arch', 'US', 'Delicate Arch'],
  ['devils-tower', 'Devils Tower', 'US', 'Devils Tower'],
  ['las-vegas-strip', 'Las Vegas Strip', 'US', 'Las Vegas Strip'],
  ['peggys-cove', "Peggy's Point Lighthouse", 'CA', 'Peggys Point Lighthouse'],
  ['notre-dame-montreal', 'Notre-Dame Basilica, Montreal', 'CA', 'Notre-Dame Basilica (Montreal)'],
  ['palenque', 'Palenque', 'MX', 'Palenque', null, 'Palenque Temple of Inscriptions.JPG'],
  ['monte-alban', 'Monte Albán', 'MX', 'Monte Albán'],
  // Central America
  ['tikal', 'Tikal', 'GT', 'Tikal', [0.7, 0.55]],
  ['santa-catalina-arch', 'Santa Catalina Arch, Antigua', 'GT', 'Antigua Guatemala', [0.5, 0.5]],
  ['panama-canal', 'Panama Canal', 'PA', 'Miraflores Locks', [0.6, 0.35], 'Panama Canal Miraflores Locks.jpg'],
  ['arenal', 'Arenal Volcano', 'CR', 'Arenal Volcano', [0.5, 0.4]],
  ['great-blue-hole', 'Great Blue Hole', 'BZ', 'Great Blue Hole', [0.5, 0.4]],
  ['copan', 'Copán', 'HN', 'Copán'],
  ['leon-cathedral', 'León Cathedral', 'NI', 'León Cathedral, Nicaragua', [0.4, 0.45]],
  ['lake-atitlan', 'Lake Atitlán', 'GT', 'Lake Atitlán', null, 'Lake Atitlan, Volcan Tolimán and Volcan Atitlán.jpg'],
  ['panama-viejo', 'Panamá Viejo', 'PA', 'Panamá Viejo'],
  // Caribbean
  ['el-capitolio', 'El Capitolio', 'CU', 'El Capitolio', [0.58, 0.35]],
  ['citadelle-laferriere', 'Citadelle Laferrière', 'HT', 'Citadelle Laferrière', [0.55, 0.35]],
  ['pitons', 'Pitons', 'LC', 'Pitons (Saint Lucia)', [0.72, 0.45]],
  ['dunns-river-falls', "Dunn's River Falls", 'JM', "Dunn's River Falls", [0.4, 0.45]],
  ['alcazar-de-colon', 'Alcázar de Colón', 'DO', 'Alcázar de Colón', [0.6, 0.45]],
  ['malecon-havana', 'Malecón, Havana', 'CU', 'Malecón, Havana'],
  ['altagracia-basilica', 'Basilica of Our Lady of Altagracia', 'DO', 'Basílica Catedral Nuestra Señora de la Altagracia'],
  ['atlantis-paradise-island', 'Atlantis Paradise Island', 'BS', 'Atlantis Paradise Island'],
  // South America
  ['machu-picchu', 'Machu Picchu', 'PE', 'Machu Picchu', [0.6, 0.6]],
  ['christ-the-redeemer', 'Christ the Redeemer', 'BR', 'Christ the Redeemer (statue)', [0.5, 0.35]],
  ['sugarloaf', 'Sugarloaf Mountain', 'BR', 'Sugarloaf Mountain', [0.45, 0.4]],
  ['moai', 'Moai (Easter Island)', 'CL', 'Moai', [0.4, 0.55]],
  ['torres-del-paine', 'Torres del Paine', 'CL', 'Torres del Paine National Park', [0.55, 0.45], 'Towers of Paine - Torres del Paine National Park 13.jpg'],
  ['salar-de-uyuni', 'Salar de Uyuni', 'BO', 'Salar de Uyuni'],
  ['angel-falls', 'Angel Falls', 'VE', 'Angel Falls', [0.5, 0.45]],
  ['perito-moreno', 'Perito Moreno Glacier', 'AR', 'Perito Moreno Glacier', [0.55, 0.55]],
  ['obelisco', 'Obelisco de Buenos Aires', 'AR', 'Obelisco de Buenos Aires', [0.5, 0.45]],
  ['las-lajas', 'Las Lajas Sanctuary', 'CO', 'Las Lajas Sanctuary', [0.62, 0.3]],
  ['kaieteur-falls', 'Kaieteur Falls', 'GY', 'Kaieteur Falls', [0.45, 0.35]],
  ['galapagos', 'Galápagos Islands', 'EC', 'Galápagos Islands', [0.55, 0.62]],
  ['brasilia-cathedral', 'Cathedral of Brasília', 'BR', 'Cathedral of Brasília', [0.5, 0.65]],
  ['cartagena', 'Walled City of Cartagena', 'CO', 'Cartagena, Colombia', [0.45, 0.4], 'Clock Tower CTG 11 2019 1352.jpg'],
  ['nazca-lines', 'Nazca Lines', 'PE', 'Nazca Lines', [0.3, 0.3]],
  ['rainbow-mountain', 'Rainbow Mountain (Vinicunca)', 'PE', 'Vinicunca', [0.4, 0.5]],
  ['valle-de-la-luna', 'Valle de la Luna, Atacama', 'CL', 'Valle de la Luna (Chile)', null, 'Anfiteatro, Valle de la Luna, San Pedro de Atacama, Chile, 2016-02-01, DD 176-178 HDR.JPG'],
  ['palacio-salvo', 'Palacio Salvo', 'UY', 'Palacio Salvo', [0.43, 0.3], 'Palacio Salvo 6.JPG'],
  ['panteon-de-los-heroes', 'National Pantheon of the Heroes', 'PY', 'National Pantheon of the Heroes', [0.5, 0.4]],
  ['tiwanaku', 'Tiwanaku', 'BO', 'Tiwanaku', [0.5, 0.4]],
  ['lencois-maranhenses', 'Lençóis Maranhenses', 'BR', 'Lençóis Maranhenses National Park'],
  ['teatro-amazonas', 'Teatro Amazonas', 'BR', 'Teatro Amazonas'],
  ['cotopaxi', 'Cotopaxi', 'EC', 'Cotopaxi'],
  ['casa-rosada', 'Casa Rosada', 'AR', 'Casa Rosada'],
  ['cano-cristales', 'Caño Cristales', 'CO', 'Caño Cristales'],
  ['sacsayhuaman', 'Sacsayhuamán', 'PE', 'Sacsayhuamán'],
  ['la-mano', 'La Mano, Punta del Este', 'UY', 'La Mano de Punta del Este'],
  ['paramaribo-cathedral', 'Cathedral of Saints Peter and Paul, Paramaribo', 'SR', 'Saint Peter and Paul Cathedral, Paramaribo'],
  // Oceania
  ['sydney-opera-house', 'Sydney Opera House', 'AU', 'Sydney Opera House', [0.62, 0.45]],
  ['uluru', 'Uluru', 'AU', 'Uluru', [0.5, 0.55]],
  ['twelve-apostles', 'Twelve Apostles', 'AU', 'The Twelve Apostles (Victoria)', [0.4, 0.62]],
  ['milford-sound', 'Milford Sound', 'NZ', 'Milford Sound'],
  ['sky-tower', 'Sky Tower', 'NZ', 'Sky Tower (Auckland)', [0.53, 0.2]],
  ['nan-madol', 'Nan Madol', 'FM', 'Nan Madol', [0.5, 0.55]],
  ['great-barrier-reef', 'Great Barrier Reef', 'AU', 'Great Barrier Reef', [0.4, 0.6], 'Amazing Great Barrier Reef 1.jpg'],
  ['sydney-harbour-bridge', 'Sydney Harbour Bridge', 'AU', 'Sydney Harbour Bridge', [0.5, 0.35]],
  ['aoraki', 'Aoraki / Mount Cook', 'NZ', 'Aoraki / Mount Cook'],
  ['hobbiton', 'Hobbiton Movie Set', 'NZ', 'Hobbiton Movie Set'],
  ['bungle-bungle', 'Bungle Bungle Range', 'AU', 'Bungle Bungle Range'],
  ['flinders-street-station', 'Flinders Street station', 'AU', 'Flinders Street railway station'],
  ['mount-yasur', 'Mount Yasur', 'VU', 'Mount Yasur'],
  ['rock-islands', 'Rock Islands', 'PW', 'Rock Islands'],
  ['haamonga', 'Haʻamonga ʻa Maui', 'TO', 'Haʻamonga ʻa Maui'],
  ['parliament-png', 'Parliament House, Port Moresby', 'PG', 'National Parliament House, Port Moresby'],
];

export const LANDMARKS: Landmark[] = RAW.map(([id, name, country, wiki, focus, file]) => ({
  id,
  name,
  country,
  wiki,
  ...(file ? { file } : {}),
  ...(focus ? { focus } : {}),
}));
