// Generated by worker/scripts/fetch-landmarks.mjs — do not edit (edit landmarks.ts and re-run).
export interface LandmarkMeta {
  lat: number | null;
  lon: number | null;
  /** Wikimedia Commons file */
  file: string;
  author: string;
  license: string;
  licenseUrl: string | null;
  /** Commons file page */
  source: string;
}

export const LANDMARK_META: Record<string, LandmarkMeta> = {
  "eiffel-tower": {
    "lat": 48.8582,
    "lon": 2.2945,
    "file": "Tour_Eiffel_Wikimedia_Commons_(cropped).jpg",
    "author": "Benh LIEU SONG",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wikimedia_Commons_(cropped).jpg"
  },
  "mont-saint-michel": {
    "lat": 48.636,
    "lon": -1.511,
    "file": "Mont-Saint-Michel_vu_du_ciel.jpg",
    "author": "Amaustan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mont-Saint-Michel_vu_du_ciel.jpg"
  },
  "colosseum": {
    "lat": 41.8903,
    "lon": 12.4922,
    "file": "Colosseo_2020.jpg",
    "author": "FeaturedPics",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Colosseo_2020.jpg"
  },
  "leaning-tower-of-pisa": {
    "lat": 43.7231,
    "lon": 10.3964,
    "file": "Italy_-_Pisa_-_Leaning_Tower.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Italy_-_Pisa_-_Leaning_Tower.jpg"
  },
  "sagrada-familia": {
    "lat": 41.4037,
    "lon": 2.1743,
    "file": "SF_maig_2_cropped.jpg",
    "author": "Canaan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SF_maig_2_cropped.jpg"
  },
  "alhambra": {
    "lat": 37.1775,
    "lon": -3.59,
    "file": "Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg",
    "author": "Jebulon",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg"
  },
  "big-ben": {
    "lat": 51.5007,
    "lon": -0.1245,
    "file": "Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg",
    "author": "Christian David",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg"
  },
  "stonehenge": {
    "lat": 51.1789,
    "lon": -1.8261,
    "file": "Stonehenge2007_07_30.jpg",
    "author": "garethwiscombe",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Stonehenge2007_07_30.jpg"
  },
  "tower-bridge": {
    "lat": 51.5056,
    "lon": -0.0753,
    "file": "Tower_Bridge_at_Dawn.jpg",
    "author": "Fuzzypiggy",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tower_Bridge_at_Dawn.jpg"
  },
  "brandenburg-gate": {
    "lat": 52.5163,
    "lon": 13.3777,
    "file": "Brandenburger_Tor_abends.jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Brandenburger_Tor_abends.jpg"
  },
  "neuschwanstein": {
    "lat": 47.5575,
    "lon": 10.7494,
    "file": "Schloss_Neuschwanstein_2013.jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Schloss_Neuschwanstein_2013.jpg"
  },
  "cologne-cathedral": {
    "lat": 50.9414,
    "lon": 6.9583,
    "file": "Kölner_Dom_-_Westfassade_2022_ohne_Gerüst-0968_b.jpg",
    "author": "Raimond Spekking",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:K%C3%B6lner_Dom_-_Westfassade_2022_ohne_Ger%C3%BCst-0968_b.jpg"
  },
  "parthenon": {
    "lat": 37.9715,
    "lon": 23.7266,
    "file": "The_Parthenon_in_Athens.jpg",
    "author": "Steve Swayne",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Parthenon_in_Athens.jpg"
  },
  "st-basils-cathedral": {
    "lat": 55.7525,
    "lon": 37.6231,
    "file": "Saint_Basil's_Cathedral_in_Moscow.jpg",
    "author": "Tsy1980",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Saint_Basil%27s_Cathedral_in_Moscow.jpg"
  },
  "charles-bridge": {
    "lat": 50.0864,
    "lon": 14.4119,
    "file": "Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg",
    "author": "A.Savin",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg"
  },
  "hungarian-parliament": {
    "lat": 47.5069,
    "lon": 19.0456,
    "file": "Hungarian_Parliament_Building_from_across_the_Danube,_2025-01-11.jpg",
    "author": "Kilyann Le Hen",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hungarian_Parliament_Building_from_across_the_Danube,_2025-01-11.jpg"
  },
  "belem-tower": {
    "lat": 38.6917,
    "lon": -9.2161,
    "file": "Torre_Belém_April_2009-4a.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Torre_Bel%C3%A9m_April_2009-4a.jpg"
  },
  "st-peters-basilica": {
    "lat": 41.9022,
    "lon": 12.4533,
    "file": "Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg"
  },
  "chapel-bridge": {
    "lat": 47.0517,
    "lon": 8.3075,
    "file": "Kapellbruecke.JPG",
    "author": "Simon Koopmann",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Kapellbruecke.JPG"
  },
  "kinderdijk": {
    "lat": 51.884,
    "lon": 4.639,
    "file": "KinderdijkMolens02.jpg",
    "author": "Lucas Hirschegger",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:KinderdijkMolens02.jpg"
  },
  "dubrovnik": {
    "lat": 42.641,
    "lon": 18.11,
    "file": "Dubrovnik_s_24.jpg",
    "author": "Miroslav.vajdic",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dubrovnik_s_24.jpg"
  },
  "hallgrimskirkja": {
    "lat": 64.1417,
    "lon": -21.9266,
    "file": "Hallgrimskirkja_mai_2026.jpg",
    "author": "Steinninn",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hallgrimskirkja_mai_2026.jpg"
  },
  "cliffs-of-moher": {
    "lat": 52.9718,
    "lon": -9.4263,
    "file": "Cliffs-Of-Moher-OBriens-From-South.JPG",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cliffs-Of-Moher-OBriens-From-South.JPG"
  },
  "geirangerfjord": {
    "lat": 62.121,
    "lon": 7.129,
    "file": "Geirangerfjord_.jpg",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Geirangerfjord_.jpg"
  },
  "atomium": {
    "lat": 50.8947,
    "lon": 4.3411,
    "file": "The_Atomium_during_civil_twilight_(DSCF1135).jpg",
    "author": "Trougnouf (Benoit Brummer)",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Atomium_during_civil_twilight_(DSCF1135).jpg"
  },
  "wawel-castle": {
    "lat": 50.0539,
    "lon": 19.9347,
    "file": "Wawel_(4).jpg",
    "author": "Monika Towiańska",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wawel_(4).jpg"
  },
  "schonbrunn": {
    "lat": 48.1845,
    "lon": 16.3119,
    "file": "Wien_-_Schloss_Schönbrunn.JPG",
    "author": "C.Stadler/Bwag",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wien_-_Schloss_Sch%C3%B6nbrunn.JPG"
  },
  "bran-castle": {
    "lat": 45.515,
    "lon": 25.3672,
    "file": "Castelul_Bran2.jpg",
    "author": "Dobre Cezar",
    "license": "CC BY-SA 3.0 ro",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/ro/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Castelul_Bran2.jpg"
  },
  "stari-most": {
    "lat": 43.3373,
    "lon": 17.815,
    "file": "Mostar_Old_Town_Panorama_2007.jpg",
    "author": "Ramirez",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mostar_Old_Town_Panorama_2007.jpg"
  },
  "louvre-pyramid": {
    "lat": 48.861,
    "lon": 2.3359,
    "file": "Louvre Museum Wikimedia Commons.jpg",
    "author": "Benh LIEU SONG (Flickr)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Louvre_Museum_Wikimedia_Commons.jpg"
  },
  "arc-de-triomphe": {
    "lat": 48.8738,
    "lon": 2.295,
    "file": "Arc_de_Triomphe_-_Août_2026.jpg",
    "author": "ZeusUpsistos",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arc_de_Triomphe_-_Ao%C3%BBt_2026.jpg"
  },
  "trevi-fountain": {
    "lat": 41.9008,
    "lon": 12.4831,
    "file": "Trevi_Fountain_-_Roma.jpg",
    "author": "NikonZ7II",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Trevi_Fountain_-_Roma.jpg"
  },
  "florence-cathedral": {
    "lat": 43.7731,
    "lon": 11.2569,
    "file": "Cattedrale_di_Santa_Maria_del_Fiore_–_Il_Duomo_di_Firenze.jpg",
    "author": "Gary Campbell-Hall",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cattedrale_di_Santa_Maria_del_Fiore_%E2%80%93_Il_Duomo_di_Firenze.jpg"
  },
  "grand-canal-venice": {
    "lat": 45.4375,
    "lon": 12.3358,
    "file": "View_of_the_Grand_Canal_from_Rialto_to_Ca'Foscari.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:View_of_the_Grand_Canal_from_Rialto_to_Ca%27Foscari.jpg"
  },
  "plaza-de-espana-seville": {
    "lat": 37.3769,
    "lon": -5.9869,
    "file": "Plaza_de_España_(Sevilla)_-_01.jpg",
    "author": "Carlos Delgado",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Plaza_de_Espa%C3%B1a_(Sevilla)_-_01.jpg"
  },
  "edinburgh-castle": {
    "lat": 55.9486,
    "lon": -3.2008,
    "file": "City_of_Edinburgh_-_Edinburgh_Castle_-_20140421004403.jpg",
    "author": "Enric",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:City_of_Edinburgh_-_Edinburgh_Castle_-_20140421004403.jpg"
  },
  "giants-causeway": {
    "lat": 55.2408,
    "lon": -6.5117,
    "file": "Causeway-code_poet-4.jpg",
    "author": "code poet on flickr.",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Causeway-code_poet-4.jpg"
  },
  "meteora": {
    "lat": 39.7142,
    "lon": 21.6311,
    "file": "Meteora's_monastery_2.jpg",
    "author": "Stathis floros",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Meteora%27s_monastery_2.jpg"
  },
  "oia-santorini": {
    "lat": 36.4667,
    "lon": 25.3667,
    "file": "Oia_sunset_-_panoramio_(2).jpg",
    "author": "TomasEE",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Oia_sunset_-_panoramio_(2).jpg"
  },
  "moscow-kremlin": {
    "lat": 55.7517,
    "lon": 37.6178,
    "file": "Moscow_Kremlin_(8281675670).jpg",
    "author": "Pavel Kazachkov from Moscow, Russia",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Moscow_Kremlin_(8281675670).jpg"
  },
  "peterhof": {
    "lat": 59.8844,
    "lon": 29.9089,
    "file": "Peterhof_Palace,_Saint_Petersburg,_Russia_(44408938295).jpg",
    "author": "Ninara from Helsinki, Finland",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Peterhof_Palace,_Saint_Petersburg,_Russia_(44408938295).jpg"
  },
  "nyhavn": {
    "lat": 55.6797,
    "lon": 12.5906,
    "file": "The_Nyhavn_Canal_3.jpg",
    "author": "European Commission",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Nyhavn_Canal_3.jpg"
  },
  "little-mermaid": {
    "lat": 55.6929,
    "lon": 12.5993,
    "file": "Denmark, Copenhagen, Little Mermaid, Langelinie Promenade 150422-25.jpg",
    "author": "Richardmaackphotography",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Denmark,_Copenhagen,_Little_Mermaid,_Langelinie_Promenade_150422-25.jpg"
  },
  "helsinki-cathedral": {
    "lat": 60.1703,
    "lon": 24.9522,
    "file": "Kirkko3.png",
    "author": "Manster323",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Kirkko3.png"
  },
  "chillon": {
    "lat": 46.4142,
    "lon": 6.9275,
    "file": "001_Chateau_de_Chillon_and_Dents_du_Midi_Photo_by_Giles_Laurent.jpg",
    "author": "Giles Laurent",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:001_Chateau_de_Chillon_and_Dents_du_Midi_Photo_by_Giles_Laurent.jpg"
  },
  "hallstatt": {
    "lat": 47.562,
    "lon": 13.649,
    "file": "Hallstatt_-_Zentrum_.JPG",
    "author": "C.Stadler/Bwag",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hallstatt_-_Zentrum_.JPG"
  },
  "prague-castle": {
    "lat": 50.09,
    "lon": 14.4,
    "file": "Karlův_most_Praha,_Staré_Město_20170810_007.jpg",
    "author": "Tilman2007",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Karl%C5%AFv_most_Praha,_Star%C3%A9_M%C4%9Bsto_20170810_007.jpg"
  },
  "plitvice": {
    "lat": 44.8806,
    "lon": 15.6161,
    "file": "View_in_Plitvice_Lakes_National_Park.jpg",
    "author": "Zysko serhii",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:View_in_Plitvice_Lakes_National_Park.jpg"
  },
  "rila-monastery": {
    "lat": 42.1333,
    "lon": 23.3403,
    "file": "Rila_Monastery,_August_2013.jpg",
    "author": "Raggatt2000",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rila_Monastery,_August_2013.jpg"
  },
  "pena-palace": {
    "lat": 38.7878,
    "lon": -9.3906,
    "file": "Sintra_Portugal_Palácio_da_Pena-01.jpg",
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sintra_Portugal_Pal%C3%A1cio_da_Pena-01.jpg"
  },
  "tallinn-old-town": {
    "lat": 59.4372,
    "lon": 24.7453,
    "file": "Old_Town_of_Tallinn,_Tallinn,_Estonia_-_panoramio_(58).jpg",
    "author": "Ben Bender",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Old_Town_of_Tallinn,_Tallinn,_Estonia_-_panoramio_(58).jpg"
  },
  "trakai": {
    "lat": 54.6525,
    "lon": 24.9331,
    "file": "Traku_pilis_by_Augustas_Didzgalvis.jpg",
    "author": "BigHead",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Traku_pilis_by_Augustas_Didzgalvis.jpg"
  },
  "bled": {
    "lat": 46.3644,
    "lon": 14.0947,
    "file": "Lake_Bled_from_the_Mountain.jpg",
    "author": "Canadianhockey91",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lake_Bled_from_the_Mountain.jpg"
  },
  "kaneo": {
    "lat": 41.1111,
    "lon": 20.7887,
    "file": "Church_of_St._John_at_Kaneo_6.jpg",
    "author": "kallerna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Church_of_St._John_at_Kaneo_6.jpg"
  },
  "valletta": {
    "lat": 35.8983,
    "lon": 14.5125,
    "file": "St_Sebastian_Curtain_(cropped).jpg",
    "author": "Mandyy88",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:St_Sebastian_Curtain_(cropped).jpg"
  },
  "vianden-castle": {
    "lat": 49.935,
    "lon": 6.2022,
    "file": "Burg_Vianden,_Luxemburg.jpg",
    "author": "Jeff Croisé",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Burg_Vianden,_Luxemburg.jpg"
  },
  "st-sophia-kyiv": {
    "lat": 50.4528,
    "lon": 30.5144,
    "file": "80-391-0151_Kyiv_St.Sophia's_Cathedral_RB_18_2_(cropped).jpg",
    "author": "Rbrechko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:80-391-0151_Kyiv_St.Sophia%27s_Cathedral_RB_18_2_(cropped).jpg"
  },
  "gergeti": {
    "lat": 42.6625,
    "lon": 44.6203,
    "file": "Gergeti_Trinity_Church_09.23.jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gergeti_Trinity_Church_09.23.jpg"
  },
  "khor-virap": {
    "lat": 39.8783,
    "lon": 44.5761,
    "file": "Monasterio_Khor_Virap,_Armenia,_2016-10-01,_DD_25.jpg",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Monasterio_Khor_Virap,_Armenia,_2016-10-01,_DD_25.jpg"
  },
  "taj-mahal": {
    "lat": 27.175,
    "lon": 78.0419,
    "file": "Taj_Mahal_(Edited).jpeg",
    "author": "Yann; edited by Jim Carter",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Taj_Mahal_(Edited).jpeg"
  },
  "golden-temple": {
    "lat": 31.62,
    "lon": 74.8764,
    "file": "The_Golden_Temple_of_Amrithsar_7.jpg",
    "author": "Shagil Kannur",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Golden_Temple_of_Amrithsar_7.jpg"
  },
  "great-wall": {
    "lat": 40.4314,
    "lon": 116.5644,
    "file": "The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
    "author": "Severin.stalder",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Great_Wall_of_China_at_Jinshanling-edit.jpg"
  },
  "forbidden-city": {
    "lat": 39.9158,
    "lon": 116.3908,
    "file": "Sunset of the Forbidden City 2006.JPG",
    "author": "User:kallgan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Sunset_of_the_Forbidden_City_2006.JPG"
  },
  "potala-palace": {
    "lat": 29.6578,
    "lon": 91.1169,
    "file": "Potala_Palace_HQ.jpg",
    "author": "Lhasa Government",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Potala_Palace_HQ.jpg"
  },
  "angkor-wat": {
    "lat": 13.4125,
    "lon": 103.8667,
    "file": "Angkor_Wat.jpg",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Angkor_Wat.jpg"
  },
  "petronas-towers": {
    "lat": 3.1578,
    "lon": 101.7117,
    "file": "2016 Kuala Lumpur, Petronas Towers (26).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Petronas_Towers_(26).jpg"
  },
  "burj-khalifa": {
    "lat": 25.1972,
    "lon": 55.2742,
    "file": "Dubai skyline 2015 (crop).jpg",
    "author": "Tim.Reckmann",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dubai_skyline_2015_(crop).jpg"
  },
  "mount-fuji": {
    "lat": 35.3608,
    "lon": 138.7275,
    "file": "View_of_Mount_Fuji_from_Ōwakudani_20211202.jpg",
    "author": "Suicasmo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg"
  },
  "fushimi-inari": {
    "lat": 34.9672,
    "lon": 135.7728,
    "file": "Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg"
  },
  "petra": {
    "lat": 30.3285,
    "lon": 35.4444,
    "file": "Al_Deir_Petra.JPG",
    "author": "Azurfrog",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Al_Deir_Petra.JPG"
  },
  "marina-bay-sands": {
    "lat": 1.2825,
    "lon": 103.86,
    "file": "Marina_Bay_Sands_(I).jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Sands_(I).jpg"
  },
  "borobudur": {
    "lat": -7.608,
    "lon": 110.204,
    "file": "Pradaksina.jpg",
    "author": "Heri nugroho",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pradaksina.jpg"
  },
  "hagia-sophia": {
    "lat": 41.0083,
    "lon": 28.98,
    "file": "Hagia_Sophia_(228968325).jpeg",
    "author": "Adli Wahid",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hagia_Sophia_(228968325).jpeg"
  },
  "shwedagon": {
    "lat": 16.7984,
    "lon": 96.1497,
    "file": "Shwedagon_Pagoda_2017.jpg",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Shwedagon_Pagoda_2017.jpg"
  },
  "wat-arun": {
    "lat": 13.7436,
    "lon": 100.4889,
    "file": "เจดีย์ประธานทรงปรางค์วัดอรุณ2.jpg",
    "author": "Mastertongapollo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%98%E0%B8%B2%E0%B8%99%E0%B8%97%E0%B8%A3%E0%B8%87%E0%B8%9B%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B9%8C%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AD%E0%B8%A3%E0%B8%B8%E0%B8%932.jpg"
  },
  "ha-long-bay": {
    "lat": 20.9,
    "lon": 107.2,
    "file": "Ha_Long_Bay_in_2019.jpg",
    "author": "Taewangkorea",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ha_Long_Bay_in_2019.jpg"
  },
  "registan": {
    "lat": 39.6547,
    "lon": 66.9756,
    "file": "RegistanSquare_Samarkand.jpg",
    "author": "Registan_-_Gusjer.jpg: Gustavo Jeronimo from Aranjuez, Spain derivative work: MrPanyGoff",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:RegistanSquare_Samarkand.jpg"
  },
  "taipei-101": {
    "lat": 25.0336,
    "lon": 121.5647,
    "file": "Taipei Taiwan Taipei-101-Tower-01.jpg",
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Taipei_Taiwan_Taipei-101-Tower-01.jpg"
  },
  "gyeongbokgung": {
    "lat": 37.5799,
    "lon": 126.9768,
    "file": "광화문_월대.jpg",
    "author": "서울관광 아카이브",
    "license": "KOGL Type 1",
    "licenseUrl": "http://www.kogl.or.kr/info/licenseType1.do",
    "source": "https://commons.wikimedia.org/wiki/File:%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg"
  },
  "sigiriya": {
    "lat": 7.9569,
    "lon": 80.7597,
    "file": "Sigiriya_(141688197).jpeg",
    "author": "Wrobell",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sigiriya_(141688197).jpeg"
  },
  "persepolis": {
    "lat": 29.935,
    "lon": 52.89,
    "file": "2018-09-21_Iran,_Persepolis,_Tachara_(from_the_southeast).jpg",
    "author": "Laurens R. Krol",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2018-09-21_Iran,_Persepolis,_Tachara_(from_the_southeast).jpg"
  },
  "tigers-nest": {
    "lat": 27.4919,
    "lon": 89.3635,
    "file": "Paro_Taktsang,_Bhutan_(edited).jpg",
    "author": "Original: Nina R from Africa Derivative work: UnpetitproleX",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Paro_Taktsang,_Bhutan_(edited).jpg"
  },
  "chocolate-hills": {
    "lat": 9.9167,
    "lon": 124.1667,
    "file": "Chocolate Hills overview.JPG",
    "author": "P199",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chocolate_Hills_overview.JPG"
  },
  "boudhanath": {
    "lat": 27.7214,
    "lon": 85.3619,
    "file": "Boudhanath_stupa_,_Kathmandu,_Nepal.jpg",
    "author": "Sumitbhatt222",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boudhanath_stupa_,_Kathmandu,_Nepal.jpg"
  },
  "himeji-castle": {
    "lat": 34.8394,
    "lon": 134.6939,
    "file": "Himeji_castle_in_may_2015.jpg",
    "author": "Nikos Kitsakis",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Himeji_castle_in_may_2015.jpg"
  },
  "terracotta-army": {
    "lat": 34.385,
    "lon": 109.2731,
    "file": "51714-Terracota-Army.jpg",
    "author": "xiquinhosilva",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:51714-Terracota-Army.jpg"
  },
  "temple-of-heaven": {
    "lat": 39.8822,
    "lon": 116.4066,
    "file": "Temple_of_Heaven_20160323_01.jpg",
    "author": "Shujianyang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Temple_of_Heaven_20160323_01.jpg"
  },
  "hawa-mahal": {
    "lat": 26.9239,
    "lon": 75.8267,
    "file": "East_facade_Hawa_Mahal_Jaipur_from_ground_level_(July_2022)_-_img_01.jpg",
    "author": "Chainwit.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:East_facade_Hawa_Mahal_Jaipur_from_ground_level_(July_2022)_-_img_01.jpg"
  },
  "gateway-of-india": {
    "lat": 18.922,
    "lon": 72.8347,
    "file": "Mumbai_03-2016_30_Gateway_of_India.jpg",
    "author": "A.Savin",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:Mumbai_03-2016_30_Gateway_of_India.jpg"
  },
  "bagan": {
    "lat": 21.1725,
    "lon": 94.86,
    "file": "Bagan,_Burma.jpg",
    "author": "Corto Maltese 1999",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bagan,_Burma.jpg"
  },
  "batu-caves": {
    "lat": 3.2374,
    "lon": 101.6839,
    "file": "Batu_Caves_stairs_2022-05.jpg",
    "author": "Chainwit.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Batu_Caves_stairs_2022-05.jpg"
  },
  "hegra": {
    "lat": 26.7917,
    "lon": 37.9528,
    "file": "Qasr al-Farid, a 1st-century AD Nabatean unfinished tomb carved into a giant boulder in Hegra (Mada'in Salih), the kingdom's second Nabatean capital after Petra, Saudi Arabia - 53535089614.jpg",
    "author": "Carole Raddato from FRANKFURT, Germany",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Qasr_al-Farid,_a_1st-century_AD_Nabatean_unfinished_tomb_carved_into_a_giant_boulder_in_Hegra_(Mada%27in_Salih),_the_kingdom%27s_second_Nabatean_capital_after_Petra,_Saudi_Arabia_-_53535089614.jpg"
  },
  "naqsh-e-jahan": {
    "lat": 32.6575,
    "lon": 51.6778,
    "file": "Sheikh Lotfallah Esfahan.JPG",
    "author": "Nicolas Hadjisavvas",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Sheikh_Lotfallah_Esfahan.JPG"
  },
  "cappadocia": {
    "lat": 38.6183,
    "lon": 34.8672,
    "file": "Cappadocia_balloon_trip,_Ortahisar_Castle_(11893715185).jpg",
    "author": "Arian Zwegers from Brussels, Belgium",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cappadocia_balloon_trip,_Ortahisar_Castle_(11893715185).jpg"
  },
  "pamukkale": {
    "lat": 37.9239,
    "lon": 29.1233,
    "file": "Pamukkale,_Denizli_2026_68.jpg",
    "author": "Biologg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pamukkale,_Denizli_2026_68.jpg"
  },
  "baalbek": {
    "lat": 34.0063,
    "lon": 36.2073,
    "file": "Temple_of_Bacchus,_Baalbek,_Lebanon_(49890013476).jpg",
    "author": "Lodo from Moscow, Russia",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Temple_of_Bacchus,_Baalbek,_Lebanon_(49890013476).jpg"
  },
  "badshahi-mosque": {
    "lat": 31.5881,
    "lon": 74.3094,
    "file": "Badshahi_Mosque_front_picture.jpg",
    "author": "Romero Maia",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Badshahi_Mosque_front_picture.jpg"
  },
  "wat-xieng-thong": {
    "lat": 19.8975,
    "lon": 102.1431,
    "file": "Temple_Wat_Xieng_Thong_-_Luang_Prabang_-_Laos.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Temple_Wat_Xieng_Thong_-_Luang_Prabang_-_Laos.jpg"
  },
  "n-seoul-tower": {
    "lat": 37.5512,
    "lon": 126.9883,
    "file": "Namsan Seoul Tower (49174492933).jpg",
    "author": "Matt Kieffer from London, United Kingdom",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Namsan_Seoul_Tower_(49174492933).jpg"
  },
  "genghis-khan-statue": {
    "lat": 47.8081,
    "lon": 107.5298,
    "file": "Genghis_Khan_Equestrian_Statue,_photo_by_Vaiz_Ha.jpg",
    "author": "Vaiz Ha",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Genghis_Khan_Equestrian_Statue,_photo_by_Vaiz_Ha.jpg"
  },
  "darvaza": {
    "lat": 40.2525,
    "lon": 58.4396,
    "file": "Darvasa_gas_crater_panorama.jpg",
    "author": "Tormod Sandtorv",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Darvasa_gas_crater_panorama.jpg"
  },
  "banaue": {
    "lat": 16.9,
    "lon": 121.05,
    "file": "Banaue-terrace.JPG",
    "author": "User: (WT-shared) Roundtheworld at wts wikivoyage",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Banaue-terrace.JPG"
  },
  "omar-ali-saifuddien-mosque": {
    "lat": 4.8894,
    "lon": 114.9392,
    "file": "Sultan_Omar_Ali_Saifuddin_Mosque_with_the_ceremonial_ship.jpg",
    "author": "Abdullah Geelah",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Sultan_Omar_Ali_Saifuddin_Mosque_with_the_ceremonial_ship.jpg"
  },
  "hoi-an": {
    "lat": 15.8771,
    "lon": 108.326,
    "file": "2024_Hội_An_-_Japanese_Covered_Bridge_(Chùa_Cầu)_after_renovation_-_img_11.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2024_H%E1%BB%99i_An_-_Japanese_Covered_Bridge_(Ch%C3%B9a_C%E1%BA%A7u)_after_renovation_-_img_11.jpg"
  },
  "grand-palace-bangkok": {
    "lat": 13.7501,
    "lon": 100.492,
    "file": "0005574_-_Wat_Phra_Kaew_006.jpg",
    "author": "Preecha.MJ",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:0005574_-_Wat_Phra_Kaew_006.jpg"
  },
  "pyramids-of-giza": {
    "lat": 29.9761,
    "lon": 31.1328,
    "file": "Pyramids_of_the_Giza_Necropolis.jpg",
    "author": "KennyOMG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pyramids_of_the_Giza_Necropolis.jpg"
  },
  "abu-simbel": {
    "lat": 22.3369,
    "lon": 31.6256,
    "file": "Ramsis,_Aswan_Governorate,_Egypt_-_panoramio.jpg",
    "author": "youssef_alam",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ramsis,_Aswan_Governorate,_Egypt_-_panoramio.jpg"
  },
  "table-mountain": {
    "lat": -33.9622,
    "lon": 18.4099,
    "file": "Table_Mountain_DanieVDM.jpg",
    "author": "Danie van der Merwe from Cape Town, South Africa",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Table_Mountain_DanieVDM.jpg"
  },
  "kilimanjaro": {
    "lat": -3.0674,
    "lon": 37.3556,
    "file": "Kilimanjaro_from_Amboseli.jpg",
    "author": "Sergey Pesterev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kilimanjaro_from_Amboseli.jpg"
  },
  "djenne-mosque": {
    "lat": 13.9053,
    "lon": -4.5556,
    "file": "Djenne_great_mud_mosque.jpg",
    "author": "Ruud Zwart",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Djenne_great_mud_mosque.jpg"
  },
  "ait-benhaddou": {
    "lat": 31.0472,
    "lon": -7.1289,
    "file": "Ksar_Aït_Benhaddou,_Marocco_(أيت_بن_حدو،_المغرب,_ⴰⵢⵜ_ⵃⴰⴷⴷⵓ).jpg",
    "author": "Petar Milošević",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ksar_A%C3%AFt_Benhaddou,_Marocco_(%D8%A3%D9%8A%D8%AA_%D8%A8%D9%86_%D8%AD%D8%AF%D9%88%D8%8C_%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8,_%E2%B4%B0%E2%B5%A2%E2%B5%9C_%E2%B5%83%E2%B4%B0%E2%B4%B7%E2%B4%B7%E2%B5%93).jpg"
  },
  "lalibela": {
    "lat": 12.0317,
    "lon": 39.0411,
    "file": "Lalibela,_san_giorgio,_esterno_24.jpg",
    "author": "Sailko",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lalibela,_san_giorgio,_esterno_24.jpg"
  },
  "avenue-of-the-baobabs": {
    "lat": -20.25,
    "lon": 44.4194,
    "file": "Adansonia_grandidieri_Pat_Hooper.jpg",
    "author": "Pat Hooper from Chicago, IL, USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Adansonia_grandidieri_Pat_Hooper.jpg"
  },
  "el-jem": {
    "lat": 35.2964,
    "lon": 10.7069,
    "file": "The_Amphitheatre_of_El_Jem,_built_around_AD_238_in_Thysdrus_in_Africa_Proconsularis,_the_estimated_capacity_is_35,000,_Tunisia_-_52717762494.jpg",
    "author": "Carole Raddato",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Amphitheatre_of_El_Jem,_built_around_AD_238_in_Thysdrus_in_Africa_Proconsularis,_the_estimated_capacity_is_35,000,_Tunisia_-_52717762494.jpg"
  },
  "sossusvlei": {
    "lat": -24.7398,
    "lon": 15.2877,
    "file": "Sossusvlei.jpg",
    "author": "Ikiwaner",
    "license": "GFDL 1.2",
    "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
    "source": "https://commons.wikimedia.org/wiki/File:Sossusvlei.jpg"
  },
  "great-zimbabwe": {
    "lat": -20.2667,
    "lon": 30.9333,
    "file": "Conical_Tower_-_Great_Enclosure_III_(33736918448).jpg",
    "author": "Andrew Moore from Johannesburg, South Africa",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Conical_Tower_-_Great_Enclosure_III_(33736918448).jpg"
  },
  "our-lady-of-peace": {
    "lat": 6.8111,
    "lon": -5.2969,
    "file": "Basilique notre Dame de la Paix de Yamoussoukro 9.jpg",
    "author": "Didierwiki",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Basilique_notre_Dame_de_la_Paix_de_Yamoussoukro_9.jpg"
  },
  "goree": {
    "lat": 14.6669,
    "lon": -17.3983,
    "file": "Ile-de-goree.jpg",
    "author": "Gregor Rom",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ile-de-goree.jpg"
  },
  "karnak": {
    "lat": 25.7183,
    "lon": 32.6583,
    "file": "Temple_de_Louxor_68.jpg",
    "author": "René Hourdry",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Temple_de_Louxor_68.jpg"
  },
  "leptis-magna": {
    "lat": 32.6392,
    "lon": 14.2906,
    "file": "Leptis_Magna_(29)_(8288918733).jpg",
    "author": "joepyrek from Richmond, Va, USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Leptis_Magna_(29)_(8288918733).jpg"
  },
  "sidi-bou-said": {
    "lat": 36.8717,
    "lon": 10.3472,
    "file": "SidBS (47).JPG",
    "author": "Hajotthu 14:41, 22. Feb. 2009 (CET)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:SidBS_(47).JPG"
  },
  "notre-dame-d-afrique": {
    "lat": 36.8011,
    "lon": 3.0425,
    "file": "Notre_Dame_d'Afrique2_cropped.jpg",
    "author": "Chettouh Nabil",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Notre_Dame_d%27Afrique2_cropped.jpg"
  },
  "chefchaouen": {
    "lat": 35.1714,
    "lon": -5.2697,
    "file": "Chefchaouen-the-blue-city-of-morocco-with-palm-trees-and-the-mountain-view-in-the-backrgound.jpg",
    "author": "Badr Rachadi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chefchaouen-the-blue-city-of-morocco-with-palm-trees-and-the-mountain-view-in-the-backrgound.jpg"
  },
  "hassan-ii-mosque": {
    "lat": 33.6085,
    "lon": -7.6327,
    "file": "SOUR JDID, Casablanca, Morocco - panoramio (16).jpg",
    "author": "karel291",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:SOUR_JDID,_Casablanca,_Morocco_-_panoramio_(16).jpg"
  },
  "fasil-ghebbi": {
    "lat": 12.6075,
    "lon": 37.47,
    "file": "Fasilides_Palace_01.jpg",
    "author": "Bernard Gagnon",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Fasilides_Palace_01.jpg"
  },
  "meroe-pyramids": {
    "lat": 16.9333,
    "lon": 33.7264,
    "file": "NubianMeroePyramids30sep2005(2).jpg",
    "author": "Wufei07",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:NubianMeroePyramids30sep2005(2).jpg"
  },
  "blyde-river-canyon": {
    "lat": -24.58,
    "lon": 30.8,
    "file": "20131119_162543b.jpg",
    "author": "Claudirene",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:20131119_162543b.jpg"
  },
  "stone-town": {
    "lat": -6.1624,
    "lon": 39.1913,
    "file": "Zanzibar_sultan_palace.jpg",
    "author": "No machine-readable author provided. Mbz1 assumed (based on copyright claims).",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Zanzibar_sultan_palace.jpg"
  },
  "le-morne": {
    "lat": -20.4519,
    "lon": 57.3283,
    "file": "Le_Morne_Peninsula_in_Mauritius_(53697779236).jpg",
    "author": "\"dronepicr\"",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Le_Morne_Peninsula_in_Mauritius_(53697779236).jpg"
  },
  "anse-source-d-argent": {
    "lat": -4.3715,
    "lon": 55.8272,
    "file": "La_Digue_asv2024-10_img22_Union_Estate.jpg",
    "author": "A.Savin",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:La_Digue_asv2024-10_img22_Union_Estate.jpg"
  },
  "okavango-delta": {
    "lat": -19.4,
    "lon": 22.9,
    "file": "Travesía del delta del Okavango en makoro, Botsuana, 2018-08-01, DD 22.jpg",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Traves%C3%ADa_del_delta_del_Okavango_en_makoro,_Botsuana,_2018-08-01,_DD_22.jpg"
  },
  "kasubi-tombs": {
    "lat": 0.3292,
    "lon": 32.5533,
    "file": "Kampala_Kasubi_Tombs.jpg",
    "author": "not not phil from SF, CA, US",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kampala_Kasubi_Tombs.jpg"
  },
  "statue-of-liberty": {
    "lat": 40.6892,
    "lon": -74.0444,
    "file": "Front_view_of_Statue_of_Liberty_(cropped).jpg",
    "author": "AskALotl",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Front_view_of_Statue_of_Liberty_(cropped).jpg"
  },
  "golden-gate-bridge": {
    "lat": 37.8197,
    "lon": -122.4786,
    "file": "Golden_Gate_Bridge_as_seen_from_Battery_East.jpg",
    "author": "Frank Schulenburg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Golden_Gate_Bridge_as_seen_from_Battery_East.jpg"
  },
  "mount-rushmore": {
    "lat": 43.8789,
    "lon": -103.4592,
    "file": "Mount_Rushmore_detail_view_(100MP).jpg",
    "author": "Thomas Wolf, www.foto-tw.de",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mount_Rushmore_detail_view_(100MP).jpg"
  },
  "grand-canyon": {
    "lat": 36.3,
    "lon": -112.75,
    "file": "Canyon_River_Tree_(165872763).jpeg",
    "author": "Lennart Sikkema",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Canyon_River_Tree_(165872763).jpeg"
  },
  "space-needle": {
    "lat": 47.6204,
    "lon": -122.3491,
    "file": "Space_Needle_2011-07-04.jpg",
    "author": "Jordon Kalilich",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Space_Needle_2011-07-04.jpg"
  },
  "cn-tower": {
    "lat": 43.6426,
    "lon": -79.3871,
    "file": "Toronto - ON - Skyline bei Nacht.jpg",
    "author": "Wladyslaw (talk)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Toronto_-_ON_-_Skyline_bei_Nacht.jpg"
  },
  "chateau-frontenac": {
    "lat": 46.8119,
    "lon": -71.205,
    "file": "Château_Frontenac_02.jpg",
    "author": "Bernard Gagnon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_Frontenac_02.jpg"
  },
  "moraine-lake": {
    "lat": 51.3225,
    "lon": -116.1856,
    "file": "Moraine_Lake_17092005.jpg",
    "author": "Gorgo",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Moraine_Lake_17092005.jpg"
  },
  "chichen-itza": {
    "lat": 20.6831,
    "lon": -88.5686,
    "file": "Chichen_Itza_3.jpg",
    "author": "Daniel Schwen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chichen_Itza_3.jpg"
  },
  "teotihuacan": {
    "lat": 19.6925,
    "lon": -98.8439,
    "file": "ZA77_Teotihuacán_edo_de_mex_Herberto_de_la_rosa.jpg",
    "author": "Hdlrosa",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:ZA77_Teotihuac%C3%A1n_edo_de_mex_Herberto_de_la_rosa.jpg"
  },
  "bellas-artes": {
    "lat": 19.4353,
    "lon": -99.1414,
    "file": "Bellas_Artes_01.jpg",
    "author": "Xavier Quetzalcoatl Contreras Castillo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bellas_Artes_01.jpg"
  },
  "hollywood-sign": {
    "lat": 34.1341,
    "lon": -118.3216,
    "file": "Hollywood_sign_(8485145044).jpg",
    "author": "Gnaphron",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hollywood_sign_(8485145044).jpg"
  },
  "white-house": {
    "lat": 38.8978,
    "lon": -77.0364,
    "file": "Tourists by WH.JPG",
    "author": "me",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Tourists_by_WH.JPG"
  },
  "times-square": {
    "lat": 40.7575,
    "lon": -73.9858,
    "file": "New_york_times_square-terabass.jpg",
    "author": "Terabass",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:New_york_times_square-terabass.jpg"
  },
  "gateway-arch": {
    "lat": 38.6246,
    "lon": -90.185,
    "file": "St_Louis_night_expblend_cropped.jpg",
    "author": "St_Louis_night_expblend.jpg: Daniel Schwen derivative work: ←fetchcomms",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:St_Louis_night_expblend_cropped.jpg"
  },
  "parliament-hill": {
    "lat": 45.4247,
    "lon": -75.6994,
    "file": "Ottawa_-_ON_-_Stadtansicht.jpg",
    "author": "Wladyslaw",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Ottawa_-_ON_-_Stadtansicht.jpg"
  },
  "tulum": {
    "lat": 20.2147,
    "lon": -87.4289,
    "file": "Tulum_2.jpg",
    "author": "Popo le Chien",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tulum_2.jpg"
  },
  "tikal": {
    "lat": 17.2219,
    "lon": -89.6236,
    "file": "Tikal_3.jpg",
    "author": "Mundo Maya",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tikal_3.jpg"
  },
  "santa-catalina-arch": {
    "lat": 14.5575,
    "lon": -90.7333,
    "file": "Antigua_-_Arco.jpg",
    "author": "Juan Francisco",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Antigua_-_Arco.jpg"
  },
  "panama-canal": {
    "lat": 8.9971,
    "lon": -79.5919,
    "file": "Panama Canal Miraflores Locks.jpg",
    "author": "User:Stan Shebs",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Panama_Canal_Miraflores_Locks.jpg"
  },
  "arenal": {
    "lat": 10.4625,
    "lon": -84.7033,
    "file": "Arenal_volcano_(70785p)_(cropped).jpg",
    "author": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arenal_volcano_(70785p)_(cropped).jpg"
  },
  "great-blue-hole": {
    "lat": 17.3153,
    "lon": -87.5344,
    "file": "Great_Blue_Hole.jpg",
    "author": "U.S. Geological Survey (USGS)",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Great_Blue_Hole.jpg"
  },
  "copan": {
    "lat": 14.8375,
    "lon": -89.1425,
    "file": "Copan_sculpture.jpg",
    "author": "Adalberto Hernandez Vega from Copan Ruinas, Honduras",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Copan_sculpture.jpg"
  },
  "leon-cathedral": {
    "lat": 12.435,
    "lon": -86.8781,
    "file": "Nicaragua_2017-03-13_(33663091692).jpg",
    "author": "Guillaume Baviere from Uppsala, Sweden",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nicaragua_2017-03-13_(33663091692).jpg"
  },
  "el-capitolio": {
    "lat": 23.1353,
    "lon": -82.3594,
    "file": "El_Capitolio_Havana_Cuba.jpg",
    "author": "Nigel Pacquette",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:El_Capitolio_Havana_Cuba.jpg"
  },
  "citadelle-laferriere": {
    "lat": 19.5736,
    "lon": -72.2439,
    "file": "Citadelle_Laferrière.jpg",
    "author": "Rémi Kaupp",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Citadelle_Laferri%C3%A8re.jpg"
  },
  "pitons": {
    "lat": 13.81,
    "lon": -61.0656,
    "file": "Pitons-aerial.jpg",
    "author": "Caribbeandy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pitons-aerial.jpg"
  },
  "dunns-river-falls": {
    "lat": 18.4158,
    "lon": -77.1381,
    "file": "Dunns_River_Falls_climb.JPG",
    "author": "Breakyunit at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Dunns_River_Falls_climb.JPG"
  },
  "alcazar-de-colon": {
    "lat": 18.4775,
    "lon": -69.8828,
    "file": "Maison_du_gouverneur_Don_Diego_Colomb.jpg",
    "author": "Caribeanvybz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Maison_du_gouverneur_Don_Diego_Colomb.jpg"
  },
  "machu-picchu": {
    "lat": -13.1633,
    "lon": -72.5456,
    "file": "Machu_Picchu,_2023_(012).jpg",
    "author": "Draceane",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Machu_Picchu,_2023_(012).jpg"
  },
  "christ-the-redeemer": {
    "lat": -22.9519,
    "lon": -43.2106,
    "file": "Christ_the_Redeemer_-_Cristo_Redentor.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Christ_the_Redeemer_-_Cristo_Redentor.jpg"
  },
  "sugarloaf": {
    "lat": -22.9494,
    "lon": -43.1567,
    "file": "Pão_de_Açucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg",
    "author": "Arne Müseler",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:P%C3%A3o_de_A%C3%A7ucar_-_Sugarloaf_Mountain_-_Zuckerhut_-_2022.jpg"
  },
  "moai": {
    "lat": -27.1258,
    "lon": -109.2767,
    "file": "AhuTongariki.JPG",
    "author": "Ian Sewell",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:AhuTongariki.JPG"
  },
  "torres-del-paine": {
    "lat": -51,
    "lon": -73,
    "file": "Towers of Paine - Torres del Paine National Park 13.jpg",
    "author": "Thomas Fuhrmann",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Towers_of_Paine_-_Torres_del_Paine_National_Park_13.jpg"
  },
  "salar-de-uyuni": {
    "lat": -20.1338,
    "lon": -67.4891,
    "file": "Salar_Uyuni_au01.jpg",
    "author": "Anouchka Unel",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "source": "https://commons.wikimedia.org/wiki/File:Salar_Uyuni_au01.jpg"
  },
  "angel-falls": {
    "lat": 5.9675,
    "lon": -62.5356,
    "file": "SaltoAngel1.jpg",
    "author": "Rich Childs",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:SaltoAngel1.jpg"
  },
  "perito-moreno": {
    "lat": -50.5,
    "lon": -73.1333,
    "file": "Perito_Moreno_Glacier_2023.jpg",
    "author": "Fernando",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Perito_Moreno_Glacier_2023.jpg"
  },
  "obelisco": {
    "lat": -34.6036,
    "lon": -58.3817,
    "file": "Buenos_Aires_(20234294752).jpg",
    "author": "Rodrigo Paredes from Ciudad Autónoma de Buenos Aires, Argentina",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Buenos_Aires_(20234294752).jpg"
  },
  "las-lajas": {
    "lat": 0.8055,
    "lon": -77.586,
    "file": "Santuario_de_Las_Lajas,_Ipiales,_Colombia,_2015-07-21,_DD_26-27_HDR.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Santuario_de_Las_Lajas,_Ipiales,_Colombia,_2015-07-21,_DD_26-27_HDR.JPG"
  },
  "kaieteur-falls": {
    "lat": 5.175,
    "lon": -59.4805,
    "file": "GuyanaKaieteurFalls2004.jpg",
    "author": "Sorenriise at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:GuyanaKaieteurFalls2004.jpg"
  },
  "galapagos": {
    "lat": -0.5,
    "lon": -90.5,
    "file": "Lobo_marino_(Zalophus_californianus_wollebaeki),_Punta_Pitt,_isla_de_San_Cristóbal,_islas_Galápagos,_Ecuador,_2015-07-24,_DD_11.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lobo_marino_(Zalophus_californianus_wollebaeki),_Punta_Pitt,_isla_de_San_Crist%C3%B3bal,_islas_Gal%C3%A1pagos,_Ecuador,_2015-07-24,_DD_11.JPG"
  },
  "brasilia-cathedral": {
    "lat": -15.7983,
    "lon": -47.8756,
    "file": "Catedral_Metropolitana_de_Brasilia.jpg",
    "author": "Tissiana de A. de Souza",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Catedral_Metropolitana_de_Brasilia.jpg"
  },
  "cartagena": {
    "lat": 10.4,
    "lon": -75.5,
    "file": "Clock Tower CTG 11 2019 1352.jpg",
    "author": "Mariordo (Mario Roberto Durán Ortiz)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Clock_Tower_CTG_11_2019_1352.jpg"
  },
  "nazca-lines": {
    "lat": -14.6975,
    "lon": -75.135,
    "file": "Líneas_de_Nazca,_Nazca,_Perú,_2015-07-29,_DD_49.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:L%C3%ADneas_de_Nazca,_Nazca,_Per%C3%BA,_2015-07-29,_DD_49.JPG"
  },
  "rainbow-mountain": {
    "lat": -13.8702,
    "lon": -71.303,
    "file": "Montañaarcoirisperuabanto.jpg",
    "author": "Diego Aldrin Abanto Ricce",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Monta%C3%B1aarcoirisperuabanto.jpg"
  },
  "valle-de-la-luna": {
    "lat": -22.9112,
    "lon": -68.323,
    "file": "Anfiteatro, Valle de la Luna, San Pedro de Atacama, Chile, 2016-02-01, DD 176-178 HDR.JPG",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Anfiteatro,_Valle_de_la_Luna,_San_Pedro_de_Atacama,_Chile,_2016-02-01,_DD_176-178_HDR.JPG"
  },
  "palacio-salvo": {
    "lat": -34.9067,
    "lon": -56.1983,
    "file": "Palacio Salvo 6.JPG",
    "author": "Maximasu",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Palacio_Salvo_6.JPG"
  },
  "panteon-de-los-heroes": {
    "lat": -25.2822,
    "lon": -57.6352,
    "file": "ASUNCION_PANTEON_NACIONAL_DE_LOS_HÉROES.jpg",
    "author": "Felipe Antonio",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:ASUNCION_PANTEON_NACIONAL_DE_LOS_H%C3%89ROES.jpg"
  },
  "tiwanaku": {
    "lat": -16.5547,
    "lon": -68.6733,
    "file": "PUERTA_DEL_SOL_TIWANAKU.jpg",
    "author": "CLAUDIOLD",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:PUERTA_DEL_SOL_TIWANAKU.jpg"
  },
  "sydney-opera-house": {
    "lat": -33.8568,
    "lon": 151.2151,
    "file": "Sydney_Australia._(21339175489).jpg",
    "author": "Bernard Spragg. NZ from Christchurch, New Zealand",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Sydney_Australia._(21339175489).jpg"
  },
  "uluru": {
    "lat": -25.345,
    "lon": 131.0361,
    "file": "ULURU.jpg",
    "author": "Ek2030372672",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:ULURU.jpg"
  },
  "twelve-apostles": {
    "lat": -38.665,
    "lon": 143.105,
    "file": "The_Twelve_Apostles_2011.jpg",
    "author": "Michael J Fromholtz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Twelve_Apostles_2011.jpg"
  },
  "milford-sound": {
    "lat": -44.6481,
    "lon": 167.9056,
    "file": "Milford_Sound_(New_Zealand).JPG",
    "author": "Maros M r a z (Maros)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Milford_Sound_(New_Zealand).JPG"
  },
  "sky-tower": {
    "lat": -36.8485,
    "lon": 174.7623,
    "file": "01_Auckland_New_Zealand-1000137.jpg",
    "author": "QFSE Media",
    "license": "CC BY-SA 3.0 nz",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/nz/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:01_Auckland_New_Zealand-1000137.jpg"
  },
  "nan-madol": {
    "lat": 6.8419,
    "lon": 158.3322,
    "file": "Nan_madol.jpg",
    "author": "NOAA",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Nan_madol.jpg"
  },
  "great-barrier-reef": {
    "lat": -16.4,
    "lon": 145.8,
    "file": "Amazing Great Barrier Reef 1.jpg",
    "author": "Sarah_Ackerman",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Amazing_Great_Barrier_Reef_1.jpg"
  },
  "sydney-harbour-bridge": {
    "lat": -33.8522,
    "lon": 151.2106,
    "file": "Sydney_Harbour_Bridge-16_October_2025.jpg",
    "author": "Servite et contribuere",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Sydney_Harbour_Bridge-16_October_2025.jpg"
  },
  "kimono": {
    "lat": 35.01,
    "lon": 135.77,
    "file": "Two_young_maiko_in_Seirai-in_Temple_02.jpg",
    "author": "Takaaki Kawai",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Two_young_maiko_in_Seirai-in_Temple_02.jpg"
  },
  "hanbok": {
    "lat": 37.58,
    "lon": 126.98,
    "file": "Female Hanbok From South Korea.jpg",
    "author": "IssamBarhoumi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Female_Hanbok_From_South_Korea.jpg"
  },
  "ao-dai": {
    "lat": 16.46,
    "lon": 107.59,
    "file": "Áo_dài_hoa_phượng_-_Phát_Trương_-_51231007393_(cropped).jpg",
    "author": "Phát Trương",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:%C3%81o_d%C3%A0i_hoa_ph%C6%B0%E1%BB%A3ng_-_Ph%C3%A1t_Tr%C6%B0%C6%A1ng_-_51231007393_(cropped).jpg"
  },
  "gho": {
    "lat": 27.47,
    "lon": 89.64,
    "file": "Boys_in_Bhutan_national_dress.jpg",
    "author": "Keith Mason",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Boys_in_Bhutan_national_dress.jpg"
  },
  "deel": {
    "lat": 47.92,
    "lon": 106.92,
    "file": "Sędziowie w deel na lokalnym festiwalu Naadam (03).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:S%C4%99dziowie_w_deel_na_lokalnym_festiwalu_Naadam_(03).jpg"
  },
  "barong-tagalog": {
    "lat": 14.6,
    "lon": 120.98,
    "file": "Barong Tagalog.png",
    "author": "Inkallyoucan0922",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Barong_Tagalog.png"
  },
  "longyi": {
    "lat": 16.84,
    "lon": 96.17,
    "file": "Longyi.jpg",
    "author": "Unknown author",
    "license": "Public domain",
    "licenseUrl": null,
    "source": "https://commons.wikimedia.org/wiki/File:Longyi.jpg"
  },
  "kilt": {
    "lat": 56.8,
    "lon": -4.2,
    "file": "Piper (4945825081).jpg",
    "author": "xlibber",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Piper_(4945825081).jpg"
  },
  "bunad": {
    "lat": 61,
    "lon": 8.5,
    "file": "Young girls in bunad.jpg",
    "author": "Elin",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Young_girls_in_bunad.jpg"
  },
  "traje-de-flamenca": {
    "lat": 37.39,
    "lon": -5.98,
    "file": "Flamenca_001.jpg",
    "author": "Schnobby",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Flamenca_001.jpg"
  },
  "vyshyvanka": {
    "lat": 50.45,
    "lon": 30.52,
    "file": "Solomiya.jpg",
    "author": "Vladimir Yaitskiy",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solomiya.jpg"
  },
  "fustanella": {
    "lat": 37.975,
    "lon": 23.737,
    "file": "Evzones at Changing of the Guard, Syntagma Square, Athens.JPG",
    "author": "Marshallhenrie",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Evzones_at_Changing_of_the_Guard,_Syntagma_Square,_Athens.JPG"
  },
  "habesha-kemis": {
    "lat": 9.03,
    "lon": 38.74,
    "file": "Shewa_Amhara_girl_wearing_Shewa_Amhara_dress.jpg",
    "author": "Zenithmuhaba",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Shewa_Amhara_girl_wearing_Shewa_Amhara_dress.jpg"
  },
  "himba": {
    "lat": -18.06,
    "lon": 13.84,
    "file": "Namibie_Himba_0717a.jpg",
    "author": "Yves Picq http://veton.picq.fr",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Namibie_Himba_0717a.jpg"
  },
  "charro": {
    "lat": 20.67,
    "lon": -103.35,
    "file": "CharroMexicano2115.jpg",
    "author": "México en Fotos",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:CharroMexicano2115.jpg"
  },
  "pollera": {
    "lat": 7.77,
    "lon": -80.27,
    "file": "PanamenianPollera.JPG",
    "author": "Anelsalas at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:PanamenianPollera.JPG"
  },
  "cholita": {
    "lat": -16.5,
    "lon": -68.15,
    "file": "Urfolk i Bolivia.jpg",
    "author": "Norsk Folkehjelp Norwegian People's Aid",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Urfolk_i_Bolivia.jpg"
  },
  "huaso": {
    "lat": -34.17,
    "lon": -70.74,
    "file": "Joven de Vicuña, Chile, vestido de huaso para las celebraciones conmemorativas del Combate Naval de Iquique.jpg",
    "author": "Unknown author",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Joven_de_Vicu%C3%B1a,_Chile,_vestido_de_huaso_para_las_celebraciones_conmemorativas_del_Combate_Naval_de_Iquique.jpg"
  },
  "kapa-haka": {
    "lat": -38.14,
    "lon": 176.25,
    "file": "Maori girl in traditional dress.jpg",
    "author": "Seth Mazow",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Maori_girl_in_traditional_dress.jpg"
  },
  "huli": {
    "lat": -5.85,
    "lon": 142.95,
    "file": "Huli_wigman.jpg",
    "author": "Nomadtales",
    "license": "CC BY 2.1 au",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.1/au/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Huli_wigman.jpg"
  }
};
