// Generated by shared/scripts/fetch-sentences.mjs — do not edit (edit languages.ts and re-run).
// Sentences from Tatoeba (https://tatoeba.org), CC BY 2.0 FR. `id` is the Tatoeba sentence id.
export interface Sentence {
  id: number;
  text: string;
  /** English translation */
  en: string;
}

export const SENTENCES: Record<string, Sentence[]> = {
  "cmn": [
    {
      "id": 504940,
      "text": "我根本不在乎我的简历。",
      "en": "I don't give a damn about my CV."
    },
    {
      "id": 10336105,
      "text": "湯姆說了你會來的。",
      "en": "Tom said you'd come."
    },
    {
      "id": 8882024,
      "text": "他为自己的利益行事。",
      "en": "He is acting on his own behalf."
    },
    {
      "id": 4815166,
      "text": "你是说你放弃了吗？",
      "en": "Are you saying that you give up?"
    },
    {
      "id": 6060708,
      "text": "她買了一雙山地靴。",
      "en": "She bought a pair of walking boots."
    },
    {
      "id": 792854,
      "text": "这是我知道的最好的餐馆。",
      "en": "This is the best restaurant that I know."
    },
    {
      "id": 408473,
      "text": "你是怎么认识他的？",
      "en": "How did you get to know him?"
    },
    {
      "id": 8743567,
      "text": "如果系统工程师继续离开，公司的竞争优势将会被削弱。",
      "en": "The company's competitive edge will be eroded if system engineers continue to leave."
    }
  ],
  "hin": [
    {
      "id": 443037,
      "text": "मेरे पास एक कुत्ता है।",
      "en": "I have a dog."
    },
    {
      "id": 2083521,
      "text": "अगर आप चाहो तो आप जा सकते हैं।",
      "en": "If you wish, you can go."
    },
    {
      "id": 9842004,
      "text": "क्या आपको नहीं लगता कि हमें थोड़ी ज़्यादा देर रुकना चाहिए था?",
      "en": "Don't you think that we should've stayed a little longer?"
    },
    {
      "id": 3617323,
      "text": "आपके पास एक घंटा है।",
      "en": "You've got an hour."
    },
    {
      "id": 588464,
      "text": "आज बादल कल से ज़्यादा हैं।",
      "en": "There are more clouds today than yesterday."
    },
    {
      "id": 3617833,
      "text": "तुम्हारी बीवी कैसी है, टॉम?",
      "en": "How's your wife, Tom?"
    },
    {
      "id": 3216575,
      "text": "हम आपकी रक्षा करने के लिए यहाँ आए हैं।",
      "en": "We're here to protect you."
    },
    {
      "id": 588565,
      "text": "मेरी केन से कल मुलाकात हुई थी।",
      "en": "I met Ken yesterday."
    }
  ],
  "spa": [
    {
      "id": 1371477,
      "text": "En realidad, la tierra se está calentando.",
      "en": "Actually, the earth is getting warmer."
    },
    {
      "id": 1343167,
      "text": "¿Quién es tu pareja de baile?",
      "en": "Who is your dance partner?"
    },
    {
      "id": 1355810,
      "text": "Tom ya se ha inscrito para ese curso.",
      "en": "Tom has already signed up for that class."
    },
    {
      "id": 1559593,
      "text": "Su voz suena muy bello.",
      "en": "Her voice sounds very beautiful."
    },
    {
      "id": 13521233,
      "text": "¿Te gustan los mejillones?",
      "en": "Do you like mussels?"
    },
    {
      "id": 1355613,
      "text": "Existen muchos factores.",
      "en": "There are many factors."
    },
    {
      "id": 9929178,
      "text": "El anciano sentado en aquel banco es mi abuelo.",
      "en": "The old man sitting on the bench over there is my grandfather."
    },
    {
      "id": 2947044,
      "text": "Juan partió a Francia ayer.",
      "en": "John left for France yesterday."
    }
  ],
  "ara": [
    {
      "id": 6994427,
      "text": "وُلد ابن ليلى في هذه العيادة.",
      "en": "Layla's baby was born in this clinic."
    },
    {
      "id": 11248740,
      "text": "بإمكاننا الحديث عن ذلك مرة أخرى إن شئت.",
      "en": "We can talk about this another time if you want."
    },
    {
      "id": 11984288,
      "text": "لماذا يريدون العمل هنا؟",
      "en": "Why do they want to work here?"
    },
    {
      "id": 454738,
      "text": "جاءت متأخرة كالعادة.",
      "en": "She came late as usual."
    },
    {
      "id": 9631417,
      "text": "توم كان قد قتل بشكل مروع خلال الأيام الأخيرة من الحرب.",
      "en": "Tom was horribly killed during the last days of the war."
    },
    {
      "id": 11987425,
      "text": "كارلوس هو من اختطف ريمة.",
      "en": "Carlos was the one who kidnapped Rima."
    },
    {
      "id": 6980750,
      "text": "سيبدأ الفيلم الموسيقي قريبا.",
      "en": "The musical is starting soon."
    },
    {
      "id": 12018397,
      "text": "كان ياني صبورا مع سكورا.",
      "en": "Yanni was patient with Skura."
    }
  ],
  "fra": [
    {
      "id": 8703346,
      "text": "L'accident s'est produit hier matin.",
      "en": "The accident occurred yesterday morning."
    },
    {
      "id": 11102165,
      "text": "Je ne savais pas où tu étais.",
      "en": "I didn't know where you were."
    },
    {
      "id": 7293796,
      "text": "Tom ne voulait rien avoir à faire avec moi.",
      "en": "Tom didn't want to have anything to do with me."
    },
    {
      "id": 7045296,
      "text": "J'ai fait ça car on me l'a ordonné.",
      "en": "I did that because I was ordered to."
    },
    {
      "id": 3445322,
      "text": "Elles ne virent rien.",
      "en": "They didn't see anything."
    },
    {
      "id": 4779759,
      "text": "Nous avons été préoccupés.",
      "en": "We were concerned."
    },
    {
      "id": 10580583,
      "text": "Tu es trop jeune pour comprendre ces choses-là.",
      "en": "You're too young to understand such things."
    },
    {
      "id": 7776425,
      "text": "C'est exactement ce qu'on veut.",
      "en": "That's exactly what we want."
    }
  ],
  "ben": [
    {
      "id": 5589372,
      "text": "তুমি কটার সময় ঘুমাতে যাও?",
      "en": "What time do you go to bed?"
    },
    {
      "id": 3195575,
      "text": "আমি সহজেই ওর বাড়ি খুজে পেয়েছিলাম।",
      "en": "I found his house easily."
    },
    {
      "id": 11475538,
      "text": "আপনি অস্ট্রেলিয়ায় চলে যাওয়ার সময় আপনার সন্তানদের বয়স কত ছিল?",
      "en": "How old were your kids when you moved to Australia?"
    },
    {
      "id": 3175824,
      "text": "টম না হাসার চেষ্টা করছিলেন।",
      "en": "Tom tried to keep from smiling."
    },
    {
      "id": 5520009,
      "text": "আপনার দুধটা খেয়ে নিন।",
      "en": "Drink up your milk."
    },
    {
      "id": 3325105,
      "text": "আমরা খালি টমের সাথে কথা বলতে চাই।",
      "en": "We just want to talk to Tom."
    },
    {
      "id": 5556200,
      "text": "আমার এটা প্রয়োজন ছিলো।",
      "en": "I wanted this."
    },
    {
      "id": 5582085,
      "text": "আমি কি তোমাকে কিছু প্রশ্ন জিজ্ঞাসা করতে পারি?",
      "en": "Can I ask you some questions?"
    }
  ],
  "por": [
    {
      "id": 6793425,
      "text": "Eu nunca mais vou cometer tal erro.",
      "en": "I will never make such a mistake again."
    },
    {
      "id": 6141782,
      "text": "Eu desenhei uma espaçonave.",
      "en": "I drew a picture of a spaceship."
    },
    {
      "id": 12147845,
      "text": "Quero saber por que você não estava aqui para ajudar a gente ontem.",
      "en": "I want to know why you weren't here to help us yesterday."
    },
    {
      "id": 8924659,
      "text": "Tom disse que ele estaria aqui amanhã.",
      "en": "Tom said that he'd be here tomorrow."
    },
    {
      "id": 3489643,
      "text": "Como estão as crianças?",
      "en": "How are the children?"
    },
    {
      "id": 8162272,
      "text": "A escritura não é muito cara.",
      "en": "The deed is not too expensive."
    },
    {
      "id": 8632465,
      "text": "Os dois idiomas têm muito em comum.",
      "en": "The two languages have a lot in common."
    },
    {
      "id": 4785852,
      "text": "Ele é o homem que eu vi ontem.",
      "en": "He is the man I saw yesterday."
    }
  ],
  "rus": [
    {
      "id": 8452635,
      "text": "Том, вообще-то, действительно так сказал.",
      "en": "Tom did actually say that."
    },
    {
      "id": 7310349,
      "text": "Не могу поверить, что ты женился.",
      "en": "I can't believe you got married."
    },
    {
      "id": 4781794,
      "text": "Он взял меня за руку и посмотрел мне в глаза.",
      "en": "He took me by the arm and looked me in the eye."
    },
    {
      "id": 10016463,
      "text": "Вы получили мою открытку?",
      "en": "Did you get my postcard?"
    },
    {
      "id": 13799093,
      "text": "Предложение должно начинаться с большой буквы.",
      "en": "The sentence must start with a capital letter."
    },
    {
      "id": 497527,
      "text": "Она упала в обморок, увидев ДТП.",
      "en": "She blacked out on seeing the scene of the accident."
    },
    {
      "id": 12909749,
      "text": "Слова бьют больнее кулаков.",
      "en": "Words hurt more than fists."
    },
    {
      "id": 2615874,
      "text": "Я думал, что у вас свидание.",
      "en": "I thought you had a date."
    }
  ],
  "ind": [
    {
      "id": 11133054,
      "text": "Tuangkan air mendidih pada kantung teh.",
      "en": "Pour the boiling water over the teabag."
    },
    {
      "id": 11666609,
      "text": "Apakah kakek dan nenek Anda masih hidup?",
      "en": "Are your grandparents still alive?"
    },
    {
      "id": 7850511,
      "text": "Setengah dari penduduk dunia tinggal di perkotaan.",
      "en": "Half of the world’s population lives in cities."
    },
    {
      "id": 9941649,
      "text": "Dia ingin mengubah hidupnya.",
      "en": "He wanted to change his life."
    },
    {
      "id": 11191111,
      "text": "Sekaranglah kesempatanmu melakukan itu.",
      "en": "Now's your chance to do that."
    },
    {
      "id": 3483976,
      "text": "Tom berjanji padaku bahwa dia tidak akan melakukan hal itu lagi.",
      "en": "Tom promised me he wouldn't do that again."
    },
    {
      "id": 10000263,
      "text": "Aku tinggal di Tahiti.",
      "en": "I live in Tahiti."
    },
    {
      "id": 1033737,
      "text": "Tambahkan gula dan vanili pada krim kemudian kocok sampai krimnya mengental.",
      "en": "Add the sugar and vanilla to the cream and beat vigorously until the cream thickens."
    }
  ],
  "urd": [
    {
      "id": 3561882,
      "text": "تم مجھے خون دو ، میں تمھیں آزادی دونگا ۔",
      "en": "Give me your blood, I will give you freedom."
    },
    {
      "id": 1832868,
      "text": "آپ نے کبھی سنیما میں چیخ ماری ہے؟",
      "en": "Have you ever screamed in a movie theater?"
    },
    {
      "id": 1474910,
      "text": "کچھ لوگوں کے لیئے زندگی فرحت بخش ہے اور کچھ کے لیئے آزمائش۔",
      "en": "To some life is pleasure, to others suffering."
    },
    {
      "id": 4185249,
      "text": "میں نے یہ سویٹر کل خریدا تھا۔",
      "en": "I bought this sweater yesterday."
    },
    {
      "id": 2078351,
      "text": "زمین بارش کے بعد گیلی ہو چکی ہے۔",
      "en": "The ground is wet after rain."
    },
    {
      "id": 1733370,
      "text": "کیا تم ڈاکٹر کو بلا سکتی ہو؟",
      "en": "Could you call a doctor, please?"
    },
    {
      "id": 1620941,
      "text": "کرسی کھڑکی کے پاس نہیں ہے۔",
      "en": "The chair is not near the window."
    },
    {
      "id": 10823961,
      "text": "ٹوم بین الاقوامی کونفرنس میں حاضر تھا۔",
      "en": "Tom attended an international conference."
    }
  ],
  "deu": [
    {
      "id": 13064219,
      "text": "Minderjährige müssen das Formular von einem Elternteil oder Vormund unterschreiben lassen.",
      "en": "Minors must have a parent or guardian sign the form."
    },
    {
      "id": 8992757,
      "text": "Das ist eine meiner Lieblingssendungen.",
      "en": "That's one of my favorite shows."
    },
    {
      "id": 13407981,
      "text": "Darf man hier schwimmen?",
      "en": "May we swim here?"
    },
    {
      "id": 3246041,
      "text": "Hier dürft ihr nicht bleiben.",
      "en": "You must not stay here."
    },
    {
      "id": 10233591,
      "text": "Du musst dir keine Sorgen mehr um mich machen.",
      "en": "You don't have to worry about me anymore."
    },
    {
      "id": 7022456,
      "text": "Tom hätte sich fast an seinem Kaffee verschluckt.",
      "en": "Tom almost choked on his coffee."
    },
    {
      "id": 2636836,
      "text": "Macht euch das glücklich?",
      "en": "Does that make you happy?"
    },
    {
      "id": 13404016,
      "text": "Dort lebt er im Winter und danach reist er nach Bahia.",
      "en": "There he'll live during the winter, and after that time he'll travel to Bahia."
    }
  ],
  "jpn": [
    {
      "id": 223773,
      "text": "このことばを君はどう考えますか。",
      "en": "How would you take these words?"
    },
    {
      "id": 1108004,
      "text": "こないだ生まれて初めて釣りに行った。",
      "en": "The other day I went fishing for the first time in my life."
    },
    {
      "id": 10040706,
      "text": "私の文を翻訳してくれてありがとう！",
      "en": "Thanks for translating my sentences!"
    },
    {
      "id": 106445,
      "text": "彼は私がうそつきであるかのように言った。",
      "en": "He made me out to be a liar."
    },
    {
      "id": 170775,
      "text": "最悪でも平均点は取れるだろう。",
      "en": "At worst, I will get an average mark."
    },
    {
      "id": 154607,
      "text": "私は犯人と疑われた。",
      "en": "I was suspected to be the criminal."
    },
    {
      "id": 3320353,
      "text": "世界で一番愛してる。",
      "en": "I love you more than anything in the world."
    },
    {
      "id": 11124419,
      "text": "何故私を責めるのですか。",
      "en": "Why are you blaming me for what happened?"
    }
  ],
  "mar": [
    {
      "id": 13694266,
      "text": "मला फक्त तू हवा आहेस.",
      "en": "I only want you."
    },
    {
      "id": 8684544,
      "text": "मेन्नादची मुलगी लेस्बियन असल्याकारणाने त्याने तिला बाहेर काढून टाकलं.",
      "en": "Mennad kicked his daughter out because she was a lesbian."
    },
    {
      "id": 2087775,
      "text": "तुमचा वाढदिवस कधी आहे?",
      "en": "When is your birthday?"
    },
    {
      "id": 13336501,
      "text": "तू कुठे होतास हे मी टॉमला सांगितलं नाही.",
      "en": "I didn't tell Tom where you were."
    },
    {
      "id": 9195182,
      "text": "यान्नी स्वयंपाकघरात आला.",
      "en": "Yanni entered the kitchen."
    },
    {
      "id": 7958887,
      "text": "कोणीतरी तुम्हाला वाचवेल.",
      "en": "Someone will save you."
    },
    {
      "id": 6895447,
      "text": "मला माझ्या प्रश्नाचं उत्तर कधीच मिळालं नाही.",
      "en": "I never got an answer to my question."
    },
    {
      "id": 4728868,
      "text": "तिने स्पॅगेटी बनवली.",
      "en": "She made spaghetti."
    }
  ],
  "vie": [
    {
      "id": 8981796,
      "text": "Bạn đã bao giờ trốn học chưa?",
      "en": "Have you ever skipped school?"
    },
    {
      "id": 11385011,
      "text": "Lẽ ra bạn nên gọi điện thoại cho tôi khi bạn đến.",
      "en": "You should have called me when you arrived."
    },
    {
      "id": 620651,
      "text": "Tôi cũng biết cưỡi ngựa.",
      "en": "I also know how to ride a horse."
    },
    {
      "id": 510400,
      "text": "Xin đừng nói nhanh như vậy.",
      "en": "Please don't speak so fast."
    },
    {
      "id": 9011023,
      "text": "Hôm nay tôi có nhiều bài tập phải làm.",
      "en": "I have a lot of assignments to do today."
    },
    {
      "id": 563068,
      "text": "Tôi cảm thấy cô đơn.",
      "en": "I'm lonely."
    },
    {
      "id": 1567301,
      "text": "Chúng tôi không thể hưởng thụ những điều đó.",
      "en": "It should not be possible for us to enjoy them."
    },
    {
      "id": 12006955,
      "text": "Nhớ cho kỹ rằng đây không phải là trò chơi đâu đấy nhé.",
      "en": "Remember that this isn't a game."
    }
  ],
  "tel": [
    {
      "id": 7204906,
      "text": "ఇది నన్ను చాలా బాధ పెట్టింది",
      "en": "This made me very sad."
    },
    {
      "id": 3717202,
      "text": "సముద్రంలో ద్వీపాలు ఉన్నాయి.",
      "en": "There are islands in the sea."
    },
    {
      "id": 13350003,
      "text": "నేను టామ్‌ను చూడాలి.",
      "en": "I've got to see Tom."
    },
    {
      "id": 13348846,
      "text": "టామ్ గుహలోకి వెళ్ళాడు.",
      "en": "Tom went into the cave."
    },
    {
      "id": 7210928,
      "text": "ఆమెకి అబద్దం ఎందుకు చెప్పావు ?",
      "en": "Why did you lie to her?"
    },
    {
      "id": 13348814,
      "text": "వాళ్ళు నా గురించి మాట్లాడుతున్నారనుకుంట.",
      "en": "I think they were talking about me."
    },
    {
      "id": 7207700,
      "text": "నేను అతన్ని ఎప్పుడూ చూడలేదు",
      "en": "I never actually saw him."
    },
    {
      "id": 7207611,
      "text": "మేము రోజుల తరబడి నిద్రపోలేదు",
      "en": "We haven't slept in days."
    }
  ],
  "hau": [
    {
      "id": 10895824,
      "text": "Sun yi min alƙawarin za su yi.",
      "en": "They promised me they'd do it."
    },
    {
      "id": 10842519,
      "text": "Wani mugun abu na faruwa.",
      "en": "Something has gone terribly wrong."
    },
    {
      "id": 10884180,
      "text": "Yesu Kristi, shi ke nan mai nadar mai kyau a nan wajen.",
      "en": "Jesus Christ, that's some next-level nightmare fuel right there."
    },
    {
      "id": 10896131,
      "text": "Shin za ku iya haƙura da ci gaba da tafiya cikin jirgin ruwan nan na ci da wuta?",
      "en": "Did everyone manage to flee the burning ship?"
    },
    {
      "id": 10889584,
      "text": "Idan kana so ka rayu, kuma kana son mutuwa; idan ba haka ba, ba ka fahimci menene rayuwa.",
      "en": "If you want to live, you also want to die; otherwise you don't understand what life is."
    },
    {
      "id": 10811438,
      "text": "Hoton ya nuna siffar kyakkyawar mace.",
      "en": "The portrait shows the profile of a beautiful woman."
    },
    {
      "id": 10898158,
      "text": "Juan dan ƙasar Mexico ne.",
      "en": "Juan is a Mexican citizen."
    },
    {
      "id": 10852784,
      "text": "Yaushe kuka fahimci hakan?",
      "en": "When did you realize that?"
    }
  ],
  "tur": [
    {
      "id": 1463366,
      "text": "O, ayda iki ya da üç kez golf oynar.",
      "en": "He plays golf two or three times a month."
    },
    {
      "id": 4179722,
      "text": "İskambil oynamak bir hobidir.",
      "en": "Playing cards is a hobby."
    },
    {
      "id": 4269890,
      "text": "Senden çocuğum olacak.",
      "en": "I'll have your baby."
    },
    {
      "id": 4073213,
      "text": "Komşu hiçbir şey görmemiş.",
      "en": "The neighbor didn't see anything."
    },
    {
      "id": 4765145,
      "text": "Dan oraya gitmek bile istemiyordu.",
      "en": "Dan didn't even want to go there."
    },
    {
      "id": 6209537,
      "text": "Beni iki saat beklettin.",
      "en": "You've kept me waiting for two hours."
    },
    {
      "id": 4976424,
      "text": "Zaten yeni bir tane almak istiyordum.",
      "en": "I wanted to buy a new one anyway."
    },
    {
      "id": 5249785,
      "text": "Birçok sınıf arkadaşım benim aptal olduğumu düşünürler.",
      "en": "A lot of my classmates think that I'm dumb."
    }
  ],
  "pan": [
    {
      "id": 2057552,
      "text": "ਮੈਂ ਇਹ ਕਹ ਰਿਹਾ ਸੀ ਕੇ ਮੈਨੂੰ ਓਹ ਅਜੀਬ ਨਹੀ ਲਗਾ।",
      "en": "I was saying that I didn't think that it was weird at all."
    },
    {
      "id": 3790689,
      "text": "ਜੇ ਮੈਂ ਕਦੇ ਸ਼ਰਾਬ ਦਾ ਅਾਦੀ ਹੋੲਿਅਾ ਤਾਂ ਲਾਜ਼ਮੀ ਛੁੱਟੀਅਾਂ ਤੇ ਅੰਤਾਲਿਅਾ ਜਾਵਾਂਗਾ ।",
      "en": "If I ever turn into an alcoholic, I'll surely go on vacation to Antalya."
    },
    {
      "id": 3880080,
      "text": "ਮੇਰਾ ੳੁਸ ਨਾਲ ਹੁਣ ਕੋੲੀ ਰਾਬਤਾ ਨਹੀਂ ।",
      "en": "I have no contact with her."
    },
    {
      "id": 3786248,
      "text": "ਅਸਵੀਕਾਰ ਕਰਨਾ ਇਨਸਾਨ ਦਾ ਬਚਾਓ ਕਰਨ ਦੇ ਸਬ ਤੋ ਤਕੜੇ ਤਰੀਕਿਆਂ ਵਿਚੋਂ ਇਕ ਹੈ।",
      "en": "Denial is one of the strongest human defence mechanisms."
    },
    {
      "id": 3081406,
      "text": "ਮੇਰੇ ਕੋਲ ਦੋ ਬਿੱਲੀਆਂ ਹਨ|",
      "en": "I have two cats."
    },
    {
      "id": 3788586,
      "text": "ਝਟਕੇ ਲੲੀ ਤਿਅਾਰ ਹੋ ਜਾੳੁ।",
      "en": "Get ready for a shock."
    },
    {
      "id": 2066044,
      "text": "ਜਦੋਂ ਓਹ ਆਏਗਾ ਤਾ ਮੈਂ ਉਸਨੂੰ ਦੱਸ ਦੇਵਾਂਗੀ।",
      "en": "I'll tell him so when he comes."
    },
    {
      "id": 3788105,
      "text": "ਖੈਰ, ਮੈਂ ਤਾ ਸਿਰਫ਼ ਟੋਸਟ ਅਤੇ ਕਾਫ਼ੀ ਲਵਾਂਗਾ।",
      "en": "Well, I'll only take toast and coffee."
    }
  ],
  "swh": [
    {
      "id": 10848069,
      "text": "Mbona usiingie ili tunywe chai?",
      "en": "Why don't you come in and have a cup of coffee?"
    },
    {
      "id": 10896473,
      "text": "Ni mimi, Shangazi Wong.",
      "en": "This is me, Aunt Wong."
    },
    {
      "id": 10811957,
      "text": "Ndege ya jeti ilitua kufuatia maagizo ya mnara wa kudhibiti.",
      "en": "The jet plane landed following the instructions of the control tower."
    },
    {
      "id": 10807185,
      "text": "Sherehe hufanyika wakati wa mazao ya mchele.",
      "en": "A festival is held at the rice harvest."
    },
    {
      "id": 10889257,
      "text": "Kuna uwezako mkubwa sana kwamba bei zetu zitapanda mwezi ujao.",
      "en": "There's a good chance that our prices will be going up next month."
    },
    {
      "id": 10814056,
      "text": "Alikuwa ni mtu wa mwisho nilitarajia kumwona leo.",
      "en": "She was the last person I expected to meet that day."
    },
    {
      "id": 10826702,
      "text": "Mapato ya kijumla ya mwaka uliopita yalikuwa aje?",
      "en": "What was the gross income in the previous calendar year?"
    },
    {
      "id": 10825430,
      "text": "\"Uko sahihi, hakika unaonekana haikuingia leo.\" \"Eh! Unaweza kusema kitu kama hicho? \"",
      "en": "\"You're right, certainly you don't seem to have been into it today.\" \"Eh! You can tell that sort of thing?\""
    }
  ],
  "tgl": [
    {
      "id": 11655508,
      "text": "May matibay na alibay si Tom.",
      "en": "Tom has a solid alibi."
    },
    {
      "id": 11737924,
      "text": "May kakayahan po ang agham na baguhin ang mundo.",
      "en": "Science has the power to change the world."
    },
    {
      "id": 11476704,
      "text": "Patapos na ang kontrata.",
      "en": "The contract will expire soon."
    },
    {
      "id": 11805781,
      "text": "Wala po akong ibang pinagsabihan.",
      "en": "I didn't tell anyone else."
    },
    {
      "id": 11538116,
      "text": "Ang ganitong halaman ay matatagpuan lang sa Brasil.",
      "en": "Such a plant can only be found in Brazil."
    },
    {
      "id": 11588677,
      "text": "May tinutugis na nakawalang bilanggo ang mga pulis.",
      "en": "The police are pursuing an escaped prisoner."
    },
    {
      "id": 11612232,
      "text": "Nag-aalaga po ako ng baka.",
      "en": "I raise cattle."
    },
    {
      "id": 11768432,
      "text": "Hindi ko maaaring ibahin ang mga plano.",
      "en": "I can't alter the plans."
    }
  ],
  "tam": [
    {
      "id": 4157506,
      "text": "அவள் போகத் தீர்மானித்தாள்",
      "en": "She decided to go."
    },
    {
      "id": 4155262,
      "text": "அவர்கள் எல்லோரும் அங்கே சென்றார்கள்",
      "en": "All of them went there."
    },
    {
      "id": 3425839,
      "text": "டோம் அதைப் பற்றி பள்ளி செய்தித்தாளில் ஒரு கட்டுரை எழுதினான்.",
      "en": "Tom wrote an article about it in the school newspaper."
    },
    {
      "id": 4159902,
      "text": "அவன் வழி காட்டப் பட்டுக் கொண்டு இருக்கிறான்",
      "en": "He is being guided."
    },
    {
      "id": 3425716,
      "text": "\"நீ ஏன் தூங்கவில்லை?\" \"எனக்குத் தூக்கம் வராததால் நான் தூங்கவில்லை.\"",
      "en": "\"Why didn't you sleep?\" \"I didn't sleep because I wasn't sleepy.\""
    },
    {
      "id": 10722055,
      "text": "அவள் குழந்தையை முத்தமிட்டாள்.",
      "en": "She kissed her baby."
    },
    {
      "id": 4165446,
      "text": "அவள் அவனுக்கு நிச்சயிக்கப் பட்டாள்",
      "en": "She got engaged to him."
    },
    {
      "id": 10720894,
      "text": "மெதுவாக சாப்பிடுங்கள்",
      "en": "Eat slowly."
    }
  ],
  "yue": [
    {
      "id": 12112188,
      "text": "狗屋係畀狗住嘅屋。",
      "en": "A doghouse is a house for a dog."
    },
    {
      "id": 3499717,
      "text": "睇吓！廚房到有一隻貓。",
      "en": "Look! There is a cat in the kitchen."
    },
    {
      "id": 2217692,
      "text": "請問去京都站點行呀？",
      "en": "May I ask how can I go to Kyoto from here?"
    },
    {
      "id": 3364478,
      "text": "柒少陣當幫忙啦。",
      "en": "Do me a favour; just stop being so fucking dumb for a minute."
    },
    {
      "id": 10650633,
      "text": "我哋一齊飲咗杯茶。",
      "en": "We had a cup of tea together."
    },
    {
      "id": 392965,
      "text": "佢出盡力噉嗌話：「呢場仗，我哋唔可以輸！」",
      "en": "He shouted at the top of his voice, \"This is a battle we cannot lose.\""
    },
    {
      "id": 417779,
      "text": "三嘅三次方係廿七。",
      "en": "3 cubed is 27."
    },
    {
      "id": 5355345,
      "text": "我哋盡量聽朝嚟啦。",
      "en": "We'll try to stop by sometime tomorrow morning."
    }
  ],
  "pes": [
    {
      "id": 12643410,
      "text": "وقتی تام را بوسیدی چندساله بودی؟",
      "en": "How old were you when you first kissed Tom?"
    },
    {
      "id": 1883266,
      "text": "او دانشجوی دانشگاه است.",
      "en": "He is a university student."
    },
    {
      "id": 12123788,
      "text": "الآن از پستخانه برگشته‌ام.",
      "en": "I have just returned from the post office."
    },
    {
      "id": 12232275,
      "text": "تام هیچی حالیش نیست.",
      "en": "Tom is a dummy."
    },
    {
      "id": 10601885,
      "text": "بفرمایین اینم کلیدتون.",
      "en": "Here is your key."
    },
    {
      "id": 11120103,
      "text": "آیا تو یک میز را در رستوران رزرو کردی؟",
      "en": "Did you reserve a table at the restaurant?"
    },
    {
      "id": 773724,
      "text": "باید در مبارزه با گرم شدن کره‌ی زمین نقش فعال‌تری ایفا کنیم.",
      "en": "We should play a more active role in combating global warming."
    },
    {
      "id": 1674334,
      "text": "یک چای با لیمو، لطفاً.",
      "en": "A tea with lemon, please."
    }
  ],
  "kor": [
    {
      "id": 11107601,
      "text": "우리는 항상 어떠한 위험 속에 처해 있다.",
      "en": "We're always in some kind of danger."
    },
    {
      "id": 4748446,
      "text": "걔가 보스턴으로 이사하고 나서는 못봤어.",
      "en": "I haven't seen her since she moved to Boston."
    },
    {
      "id": 11106083,
      "text": "나는 방 안으로 들어가는 어떤 남자를 보았다.",
      "en": "I saw a man enter the room."
    },
    {
      "id": 13187823,
      "text": "봄을 좋아해요, 아니면 가을을 좋아해요?",
      "en": "Do you like spring or autumn?"
    },
    {
      "id": 11110633,
      "text": "나는 톰이 오후에 뭘 할 건지 궁금하다.",
      "en": "I wonder what Tom is going to do this afternoon."
    },
    {
      "id": 6295632,
      "text": "독서는 더 이상 소수의 전유물이 아니게 되었다.",
      "en": "Reading books ceased to be the privilege of a minority."
    },
    {
      "id": 9803420,
      "text": "그것을 오늘 안해도 될것같다는 걸 알아",
      "en": "I know that I might not have to do that today."
    },
    {
      "id": 13118498,
      "text": "나는 볼리비아에서 왔어. 나는 볼리비아 사람이고 스페인어를 해.",
      "en": "I come from Bolivia. I'm Bolivian, and I speak Spanish."
    }
  ],
  "tha": [
    {
      "id": 7789805,
      "text": "ฉันกำลังมองหาคนซักเสื้อผ้าสำหรับฉัน",
      "en": "I'm looking for someone to do my laundry for me."
    },
    {
      "id": 10202185,
      "text": "คุณชอบบ้านหลังนี้ไหม",
      "en": "Do you like this house?"
    },
    {
      "id": 7878380,
      "text": "นั่นเป็นเพราะว่าคุณเป็นผู้หญิง",
      "en": "That's because you're a girl."
    },
    {
      "id": 8669318,
      "text": "ปัญหาคือคุณยังเด็กเกินไป",
      "en": "The trouble is that you are too young."
    },
    {
      "id": 10615164,
      "text": "ผมคิดว่าทอมไม่รู้อะไรเลย",
      "en": "I don't think Tom knows anything."
    },
    {
      "id": 2866385,
      "text": "พวกเราต้องไปอย่างระมัดระวัง",
      "en": "We'll have to go about it with care."
    },
    {
      "id": 10681040,
      "text": "คุณเคยได้รับการถ่ายเลือดหรือไม่",
      "en": "Have you ever received a blood transfusion?"
    },
    {
      "id": 8720110,
      "text": "กรุณาให้นมฉันหนึ่งถ้วย",
      "en": "Please give me a cup of milk."
    }
  ],
  "jav": [
    {
      "id": 3939832,
      "text": "Gendérané wis munggah.",
      "en": "The flag is up."
    },
    {
      "id": 3939835,
      "text": "Bètèng iki diadegaké supaya wong-wong ora bisa mlebu apa ora bisa metu?",
      "en": "Was this wall built to keep people out or to keep them in?"
    },
    {
      "id": 10125794,
      "text": "Asu iku lanang ta wadon?",
      "en": "Is that dog male or female?"
    },
    {
      "id": 3984085,
      "text": "Tak pikir Tom kuwi nèng omah turu.",
      "en": "I thought Tom was home asleep."
    },
    {
      "id": 9665265,
      "text": "ꦄꦗꦭꦭꦶꦔꦶꦫꦶꦩꦏꦺꦭꦪꦁꦏꦸꦮꦶ꧉",
      "en": "Don't forget to send that letter."
    },
    {
      "id": 3960185,
      "text": "Kowe ra bisa meksa Tom nulungi Mary",
      "en": "You can't force Tom to help Mary."
    },
    {
      "id": 12028029,
      "text": "Saben dina Kemis, awak dhéwé ngombé bir.",
      "en": "On Thursdays, we drink beer."
    },
    {
      "id": 8864873,
      "text": "Bojo anyarmu ya wong Kanada ora?",
      "en": "Is your new wife Canadian, too?"
    }
  ],
  "ita": [
    {
      "id": 3783690,
      "text": "Io ho dormito fino all'alba.",
      "en": "I slept till dawn."
    },
    {
      "id": 4551510,
      "text": "Non sono uscito con lei per la sua intelligenza.",
      "en": "I didn't date her for her brains."
    },
    {
      "id": 6683411,
      "text": "Gli dissi quale era il piano.",
      "en": "I told him what the plan was."
    },
    {
      "id": 2617912,
      "text": "Tom non è mai in ritardo.",
      "en": "Tom is never late."
    },
    {
      "id": 5537274,
      "text": "Mary non ascolterà i consigli del suo amico.",
      "en": "Mary won't listen to her friend's advice."
    },
    {
      "id": 1953220,
      "text": "Io non sono così stupida!",
      "en": "I'm not that stupid!"
    },
    {
      "id": 2925441,
      "text": "Voi siete liberi di usare il mio yacht.",
      "en": "You are welcome to the use of my yacht."
    },
    {
      "id": 1106734,
      "text": "Potresti svegliarmi tutte le mattine?",
      "en": "Would you wake me up every morning?"
    }
  ],
  "guj": [
    {
      "id": 5688479,
      "text": "માલિક ને મસકા મારે છે.",
      "en": "He is buttering up to his boss."
    },
    {
      "id": 3268750,
      "text": "મારે બોસ્ટન જવું છે.",
      "en": "I want to go to Boston."
    },
    {
      "id": 6171981,
      "text": "તેણીએ પોતાની બહેનને બચાવવા લોહી આપ્યું",
      "en": "She gave blood in order to save her sister."
    },
    {
      "id": 5683540,
      "text": "હુ ફરિયાદ ને ધિક્કારુ છું.",
      "en": "I hate to complain."
    },
    {
      "id": 5683587,
      "text": "કોની પાછળ આંઘળો થ્યો છે.",
      "en": "What are you driving at?"
    },
    {
      "id": 6171978,
      "text": "તેણીએ પોતાના ભાઈને બચાવવા લોહી આપ્યું",
      "en": "She gave blood in order to save her sibling."
    },
    {
      "id": 3244338,
      "text": "અમદાવાદ ગુજરાતનું સૌથી મોટુ શહેર છે.",
      "en": "Ahmedabad is the largest city in Gujarat."
    },
    {
      "id": 6171310,
      "text": "તે મને વધારે હેરાન નહીં કરે",
      "en": "It doesn't bother me anymore."
    }
  ],
  "amh": [
    {
      "id": 12975489,
      "text": "ሁሉም ሰው እንግሊዝኛ ይናገራል።",
      "en": "Everyone speaks English."
    },
    {
      "id": 3642774,
      "text": "ወደ ትምሕርት ቤት እየሄድኩ ነው።",
      "en": "I'm going to school."
    },
    {
      "id": 12975503,
      "text": "እህቶቼ ስለ ሳይንስ ማውራት ይወዳሉ።",
      "en": "My sisters love to talk about science."
    },
    {
      "id": 3783762,
      "text": "እኔም ወደ ትምህርት ቤት እየሄድኩ ነው።",
      "en": "I'm also going to school."
    },
    {
      "id": 3316135,
      "text": "አነጋግሬ ለየት ያለ ሊሆን ይችላል።",
      "en": "My accent is probably strange."
    },
    {
      "id": 2722289,
      "text": "ባለፈው ሳምንት ከአሜሪካ አንዳንድ ማስታወሻ ላኩለት።",
      "en": "Last week, I mailed him some souvenirs from the U.S."
    },
    {
      "id": 6804707,
      "text": "እንኳን ለአለም አቀፍ የሴቶች ቀን አደረሰን",
      "en": "Happy International Women's Day!"
    },
    {
      "id": 3085366,
      "text": "በሳምንት ከሁለት እስካስር ብር ነው።",
      "en": "It is from two to ten birrs a week."
    }
  ],
  "kan": [
    {
      "id": 4776847,
      "text": "ನನ್ನ ತಂದೆ ಹಾಗು ನನ್ನ ಅಣ್ಣ ಈ ಕಾರ್ಖಾನೆಯಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತಾರೆ.",
      "en": "My father and my brother work in this factory."
    },
    {
      "id": 8903002,
      "text": "ನಿಮಗೆ ಏನು ಅನ್ನಿಸುತ್ತೆ",
      "en": "What do you think about it?"
    },
    {
      "id": 4774595,
      "text": "ಯಾವಾಗ ನಿನಗೆ ದುಡ್ಡು ಬೇಕಾದರೆ ಮಾತ್ರ ನೀನು ನನ್ನ ಜೊತೆ ಮಾತನಾಡುತ್ತೇಯ.",
      "en": "The only time you talk to me is when you need some money."
    },
    {
      "id": 4784782,
      "text": "ನಮ್ಮಲ್ಲಿ ಒಬ್ಬರು ಹೋಗಲೇ ಬೇಕಾಗುತ್ತದೆ.",
      "en": "One of us will have to go."
    },
    {
      "id": 13223989,
      "text": "ನಾನು ಒಬ್ಬಳೇ ಹೋಗುತ್ತೇನೆ.",
      "en": "I'll go alone."
    },
    {
      "id": 4783912,
      "text": "ಅದನ್ನು ಎಂದಿಗೂ ಮಾಡಬೇಡವೆಂದು ನಂಬೋಣ.",
      "en": "Let's hope we never have to do that."
    },
    {
      "id": 12484463,
      "text": "ಬೈಡನ್ ಕುಟುಂಬ ಭ್ರಷ್ಟ ಕುಟುಂಬವಾಗಿದೆ.",
      "en": "The Biden family is corrupt."
    },
    {
      "id": 13224122,
      "text": "ನನಗೆ ಮಸಾಲೆ ದೋಸೆ ಬೇಕು.",
      "en": "I want a masala dosa."
    }
  ],
  "nld": [
    {
      "id": 6090343,
      "text": "Mijn huis is jouw huis.",
      "en": "My home is your home."
    },
    {
      "id": 10891129,
      "text": "Waarom zou Ziri dat doen?",
      "en": "Why would Ziri do that?"
    },
    {
      "id": 8234587,
      "text": "Tom zette zijn leven op het spel om de verdrinkende jongen te redden.",
      "en": "Tom risked his life to save the drowning boy."
    },
    {
      "id": 7694333,
      "text": "Is er iemand in deze kamer?",
      "en": "Is there anyone in this room?"
    },
    {
      "id": 9526112,
      "text": "Doe de kerstboomlichten uit als u het huis verlaat.",
      "en": "Turn the Christmas tree lights off when you leave the house."
    },
    {
      "id": 10215596,
      "text": "Hoe had je het kunnen weten?",
      "en": "How could you have known?"
    },
    {
      "id": 3872360,
      "text": "Ik voel me verloren.",
      "en": "I feel lost."
    },
    {
      "id": 7536292,
      "text": "De meeste spinnen weven webben.",
      "en": "Most spiders weave webs."
    }
  ],
  "pol": [
    {
      "id": 998691,
      "text": "Trzeba ci wiedzieć, że jestem obsesyjnie punktualny.",
      "en": "One thing you should know about me is that I'm obsessed with punctuality."
    },
    {
      "id": 3607040,
      "text": "Ona uczy się esperanta.",
      "en": "She's learning Esperanto."
    },
    {
      "id": 7610484,
      "text": "Czy Tom na prawdę myśli, że to się wydarzy?",
      "en": "Does Tom really think that'll happen?"
    },
    {
      "id": 11267774,
      "text": "Przeszliśmy już większość drogi.",
      "en": "We've already gone most of the way."
    },
    {
      "id": 12036990,
      "text": "Przejdź do rzeczy, proszę.",
      "en": "Get to the point, please."
    },
    {
      "id": 11284921,
      "text": "Mam pewność, że jego nauczyciel chemii by go oblał, gdyby przeżyli tragiczny wybuch.",
      "en": "I'm sure his chemistry teacher would have failed him had they survived the tragic explosion."
    },
    {
      "id": 3584607,
      "text": "Zawołaj mnie, gdy będziesz gotowa.",
      "en": "Call me when you're ready."
    },
    {
      "id": 1359755,
      "text": "Jego torba jest tutaj, to nie mógł on jeszcze pójść do szkoły.",
      "en": "His bag is right here, so he cannot have gone to school yet."
    }
  ],
  "ukr": [
    {
      "id": 6312794,
      "text": "Можливо, вже час сказати Тому.",
      "en": "Maybe it's time to tell Tom."
    },
    {
      "id": 512302,
      "text": "Я спробую зробити це.",
      "en": "I will give it a try."
    },
    {
      "id": 7118171,
      "text": "Я знаю, що ти намагаєшся допомогти Тому.",
      "en": "I know you're trying to help Tom."
    },
    {
      "id": 6362228,
      "text": "Будь-хто може визватися добровольцем.",
      "en": "Anyone can volunteer."
    },
    {
      "id": 6038791,
      "text": "Ти не мусиш робити того, що каже Том.",
      "en": "You don't have to do what Tom says."
    },
    {
      "id": 7806673,
      "text": "Що ви знаєте про Ізраїль?",
      "en": "What do you know about Israel?"
    },
    {
      "id": 6556606,
      "text": "Я люблю свою країну.",
      "en": "I love my country."
    },
    {
      "id": 9108292,
      "text": "Тут іде дощ, і я бачу твою машину.",
      "en": "It’s raining where I am, and I’m looking at your car."
    }
  ],
  "ell": [
    {
      "id": 5565229,
      "text": "Ο Τομ δεν μπόρεσε να κρύψει τον θυμό του.",
      "en": "Tom couldn't hide his anger."
    },
    {
      "id": 3179363,
      "text": "Πείτε μου το όνομά σας.",
      "en": "Tell me your name."
    },
    {
      "id": 11527761,
      "text": "Πότε γίνονται οι εθνικές εκλογές;",
      "en": "When do the national elections take place?"
    },
    {
      "id": 10165172,
      "text": "Δεν ήξερα ότι ήσουν ομοφυλόφιλος.",
      "en": "I didn't know you were gay."
    },
    {
      "id": 3513035,
      "text": "Τα παπούτσια μου είναι πάρα πολύ μικρά.",
      "en": "My shoes are too small."
    },
    {
      "id": 3513034,
      "text": "Δεν υπάρχει σχέδιο Β, καθότι δεν υπάρχει πλανήτης Β.",
      "en": "There is no Plan B because there is no Planet B."
    },
    {
      "id": 5639404,
      "text": "Όλοι τους μιλάνε Γαλλικά.",
      "en": "They all speak French."
    },
    {
      "id": 5365761,
      "text": "Ευχαριστώ για τα εισιτήρια!",
      "en": "Thanks for the tickets!"
    }
  ],
  "swe": [
    {
      "id": 926250,
      "text": "Vem röstade du på i valet?",
      "en": "Who did you vote for in the election?"
    },
    {
      "id": 2786289,
      "text": "De allierade kontrollerade alla större irakiska städer.",
      "en": "The allies controlled all major Iraqi cities."
    },
    {
      "id": 10713170,
      "text": "Varför hjälpte du inte dem?",
      "en": "Why didn't you help them?"
    },
    {
      "id": 3068789,
      "text": "Bakteriekultur är den enda kultur somliga besitter.",
      "en": "Bacteria are the only culture some people have."
    },
    {
      "id": 4344286,
      "text": "Jag gjorde det redan.",
      "en": "I already did it."
    },
    {
      "id": 3745322,
      "text": "Det här är deras hus.",
      "en": "This is their house."
    },
    {
      "id": 3739442,
      "text": "Tom kan inte ställa sig upp.",
      "en": "Tom can't stand up."
    },
    {
      "id": 11163929,
      "text": "Tom gillar majschips.",
      "en": "Tom likes corn chips."
    }
  ],
  "nob": [
    {
      "id": 9211121,
      "text": "Jeg lar deg bestemme.",
      "en": "I'll let you decide."
    },
    {
      "id": 1865891,
      "text": "Det er gjemt under sengen.",
      "en": "It's hidden under the bed."
    },
    {
      "id": 3503709,
      "text": "De tjente penger ved å selge narkotika til det enorme markedet.",
      "en": "They made money by selling drugs into the huge market."
    },
    {
      "id": 8807798,
      "text": "Av og til, bruker jeg saks som boksåpner.",
      "en": "I sometimes use scissors as a can opener."
    },
    {
      "id": 6364705,
      "text": "Det var det jeg hadde lovet.",
      "en": "That was my promise."
    },
    {
      "id": 3306749,
      "text": "Tom lyttes til på grunn av sin overbevisningskraft.",
      "en": "Tom is listened to because of his persuasive power."
    },
    {
      "id": 2925592,
      "text": "Jeg er ihvertfall eldre enn deg.",
      "en": "At least I'm older than you."
    },
    {
      "id": 815853,
      "text": "Han bor i en leilighet for tiden.",
      "en": "He is living in an apartment at present."
    }
  ],
  "dan": [
    {
      "id": 3315356,
      "text": "Spanien lammetæver Holland.",
      "en": "Spain wallops Netherlands."
    },
    {
      "id": 6944267,
      "text": "Jeg skal have gjort badeværelset rent.",
      "en": "I have to clean the bathroom."
    },
    {
      "id": 8172441,
      "text": "Denne verden styres af ondsindede kræfter.",
      "en": "This world is controlled by malevolent forces."
    },
    {
      "id": 12307524,
      "text": "En sygeplejerske tog min temperatur.",
      "en": "A nurse took my temperature."
    },
    {
      "id": 3116455,
      "text": "De stod af ved det følgende busstoppested.",
      "en": "They got off at the next bus stop."
    },
    {
      "id": 4407792,
      "text": "Det er en af livets realiteter.",
      "en": "It's a fact of life."
    },
    {
      "id": 12120975,
      "text": "Denne atlet er stærk og adræt.",
      "en": "This athlete is strong and agile."
    },
    {
      "id": 10485151,
      "text": "Det kan jeg ikke leve med.",
      "en": "I can't live with it."
    }
  ],
  "fin": [
    {
      "id": 3781745,
      "text": "Minulla on tässä vähän muuta tekemistä.",
      "en": "I'm kind of busy."
    },
    {
      "id": 7889914,
      "text": "Eilen oli todella kuuma päivä.",
      "en": "Yesterday was a very hot day."
    },
    {
      "id": 9781622,
      "text": "Lensimme Atlantin yli.",
      "en": "We flew across the Atlantic."
    },
    {
      "id": 3276646,
      "text": "Voisitko sanoa sen kirjain kirjaimelta, kiitos!",
      "en": "Could you spell it, please?"
    },
    {
      "id": 10053279,
      "text": "Tomilla oli vain pyyhe yllään.",
      "en": "Tom was only wearing a towel."
    },
    {
      "id": 3349123,
      "text": "Flunssa iski suurkapunkialueelle.",
      "en": "The flu struck the metropolitan area."
    },
    {
      "id": 10037559,
      "text": "Tomia on puukotettu.",
      "en": "Tom has been stabbed."
    },
    {
      "id": 4143968,
      "text": "Tom huomasi, että Mari itki.",
      "en": "Tom could see that Mary was crying."
    }
  ],
  "hun": [
    {
      "id": 7291232,
      "text": "Te tényleg Tomra akarsz szavazni?",
      "en": "Do you really want to vote for Tom?"
    },
    {
      "id": 10672726,
      "text": "Portugáliába megyünk idén a lakóautóval.",
      "en": "We're taking the camper van to Portugal this year."
    },
    {
      "id": 2579925,
      "text": "Önök mégis tévednek.",
      "en": "You are wrong, however."
    },
    {
      "id": 6330081,
      "text": "- Tomi megkérte a kezem. - Na végre!",
      "en": "\"Tom made me an offer of marriage.\" \"At long last!\""
    },
    {
      "id": 4747873,
      "text": "A nevelés otthon kezdődik.",
      "en": "Education starts at home."
    },
    {
      "id": 7527105,
      "text": "Tamás ma nem jön iskolába.",
      "en": "Tom won't come to school today."
    },
    {
      "id": 5367609,
      "text": "Hazánkban ő jól ismert.",
      "en": "He is well known in our country."
    },
    {
      "id": 10555245,
      "text": "Rájuk csörgötök ti majd?",
      "en": "Are you going to call them?"
    }
  ],
  "ces": [
    {
      "id": 7793634,
      "text": "Je mu dvanáct. Na svůj věk je velký.",
      "en": "He is twelve. He is tall for his age."
    },
    {
      "id": 12831603,
      "text": "Nechci, aby to místo mě dělal Tom.",
      "en": "I don't want Tom to do it instead of me."
    },
    {
      "id": 13050378,
      "text": "Jak o tom mohl Tom vědět?",
      "en": "How could Tom have known about it?"
    },
    {
      "id": 10204020,
      "text": "Tom ztratil veškerou svoji důstojnost.",
      "en": "Tom lost all his dignity."
    },
    {
      "id": 8979735,
      "text": "Nevím jistě, jestli to Tom tak řekl.",
      "en": "I'm not sure that was what Tom said."
    },
    {
      "id": 1761598,
      "text": "Otázkou je, co udělat dále.",
      "en": "What to do next is our question."
    },
    {
      "id": 13508851,
      "text": "Mělo by se to ihned odstranit.",
      "en": "It should be removed immediately."
    },
    {
      "id": 3018063,
      "text": "Tom neví jistě, kdy Mary přijde.",
      "en": "Tom doesn't know for sure when Mary will come."
    }
  ],
  "ron": [
    {
      "id": 8636592,
      "text": "Nu avea nimic de a face cu asta.",
      "en": "It had nothing to do with this."
    },
    {
      "id": 1185103,
      "text": "N-am spus nimic care să-i rănească sentimentele.",
      "en": "I didn't say anything to hurt his feelings."
    },
    {
      "id": 405844,
      "text": "L-am văzut pe Ion la bibliotecă.",
      "en": "I saw John at the library."
    },
    {
      "id": 12360372,
      "text": "Cunoști pe cineva care vorbește franceza?",
      "en": "Do you know anyone who speaks French?"
    },
    {
      "id": 10792980,
      "text": "Sami i-a trimis separat un mesaj lui Layla.",
      "en": "Sami separately texted Layla."
    },
    {
      "id": 14047338,
      "text": "Băiașul supraveghează piscina.",
      "en": "The pool attendant supervises the swimming pool."
    },
    {
      "id": 10787662,
      "text": "Ce vrea să facă mâine?",
      "en": "What does she want to do tomorrow?"
    },
    {
      "id": 8269440,
      "text": "Am încercat să-mi fac datoria.",
      "en": "I've tried to do my duty."
    }
  ],
  "heb": [
    {
      "id": 12653825,
      "text": "הוא שינה את מסלול הכדור בחבטה קלה.",
      "en": "He redirected the ball with a flick."
    },
    {
      "id": 5758729,
      "text": "היא נזפה בו שלא הכין את שיעורי הבית.",
      "en": "She scolded him for not doing his homework."
    },
    {
      "id": 5492480,
      "text": "לקח לי זמן רב למצוא עבודה כלבבי.",
      "en": "It took me a long time to find a job I like."
    },
    {
      "id": 1075777,
      "text": "יש חנות בגן החיות הזה?",
      "en": "Is there a shop at this zoo?"
    },
    {
      "id": 8124775,
      "text": "מרי הבטיחה לתום שתעזור לו.",
      "en": "Mary promised Tom that she'd help him."
    },
    {
      "id": 6116962,
      "text": "אני שונאת שיעורי בית.",
      "en": "I hate homework."
    },
    {
      "id": 6001304,
      "text": "לא אסבול שום רשלנות.",
      "en": "I won't tolerate any sloppiness."
    },
    {
      "id": 5965429,
      "text": "כמה עולות שתי סופגניות הדבש האלה?",
      "en": "How much do these two honey doughnuts cost?"
    }
  ],
  "zul": [
    {
      "id": 9210316,
      "text": "Ngabe izingane zakho lezi?",
      "en": "Are these your children?"
    },
    {
      "id": 9208691,
      "text": "Sinifisela uKhisimusi omuhle nonyaka omusha omuhle.",
      "en": "We wish you a happy Christmas and a happy New Year."
    },
    {
      "id": 2887179,
      "text": "Ngingumfundi enyunivesini.",
      "en": "I'm a student in a university."
    },
    {
      "id": 4805150,
      "text": "Burj Khalifa yibhilidi elide kwengca wonkhe emhlabeni.",
      "en": "Burj Khalifa is currently the tallest skyscraper in the world."
    },
    {
      "id": 9210329,
      "text": "Uma imoto yakho yephuka ngokushesha, into yokuqala oyenzayo ukungenwa ingebhe.",
      "en": "When your car suddenly breaks down, your first reaction is often to panic."
    },
    {
      "id": 9208695,
      "text": "Nina zingane ningabangi umsindo ongaka!",
      "en": "You children mustn’t make so much noise!"
    },
    {
      "id": 9204394,
      "text": "Iseduzane noxhaxha lwezitolo.",
      "en": "It’s next to the shopping mall."
    },
    {
      "id": 2887234,
      "text": "Ngiyabhukuda olwandle.",
      "en": "I'm swimming in the ocean."
    }
  ],
  "yor": [
    {
      "id": 3143486,
      "text": "Ẹṣin yìí kìí ṣe funfun.",
      "en": "This horse is not white."
    },
    {
      "id": 3154939,
      "text": "Owó rẹ̀ wà ní bánkì.",
      "en": "His money is in the bank."
    },
    {
      "id": 3352030,
      "text": "Ẹni tó bá ńjẹ nínú ọlà ẹnìkan nií pèé ní anímáṣaun.",
      "en": "It's one who shares in another's wealth that hails him as a generous person."
    },
    {
      "id": 3714005,
      "text": "Mo ní àwọn arákunrin.",
      "en": "I have brothers."
    },
    {
      "id": 11984165,
      "text": "Ó jẹ́ ọmọ ilẹ̀ Potogí.",
      "en": "He is Portuguese."
    },
    {
      "id": 3713991,
      "text": "Àwọn erékùṣù wà ní òkun.",
      "en": "There are islands in the sea."
    },
    {
      "id": 4536795,
      "text": "Ṣé o lọ sọjà ni àna?",
      "en": "Did you go to the market yesterday?"
    },
    {
      "id": 3143483,
      "text": "Ẹṣin yìí jẹ́ funfun.",
      "en": "This horse is white."
    }
  ],
  "lat": [
    {
      "id": 6909834,
      "text": "Thomas ex consuetudine caffeam sine saccharo sumit.",
      "en": "Tom usually drinks coffee without sugar."
    },
    {
      "id": 7031061,
      "text": "Non dubito quin Maria Thomae non placeat.",
      "en": "I'm sure Tom doesn't like Mary."
    },
    {
      "id": 3977135,
      "text": "Didymus Mariam expectavit.",
      "en": "Tom has been expecting Mary."
    },
    {
      "id": 11139538,
      "text": "Ubi eōs minātī estis?",
      "en": "Where did you threaten them?"
    },
    {
      "id": 8505324,
      "text": "In Brasilia natus sum.",
      "en": "I was born in Brazil."
    },
    {
      "id": 4103189,
      "text": "Didymus pedulia non gerit.",
      "en": "Tom isn't wearing socks."
    },
    {
      "id": 1915744,
      "text": "Fructum nostrum videt.",
      "en": "He sees our fruit."
    },
    {
      "id": 8889942,
      "text": "Librum, quem mihi commodavisti, perlegi.",
      "en": "I've finished reading the book you lent me."
    }
  ]
};
